// @generated by archebuild — do not edit. Regenerated each build.

import { ResolveError } from '../resolve_error';
import { ResolveTokensRequest } from '../resolve_tokens_request';
import { ResolvedDiagram } from '../resolved_diagram';
import { Err, Ok, Result } from '@archeglyph/proto/util/result';
import { Tokens } from '@archeglyph/proto/gen/theme_pb';
import { TokenResolver } from './schema_gen';

const TOKEN_REF_RE = /^\$[a-zA-Z_][a-zA-Z0-9_]*(\.[a-zA-Z_][a-zA-Z0-9_]*)*$/;
const PALETTE_REF_RE = /^\$palette\.([a-zA-Z_][a-zA-Z0-9_]*)$/;

export class TokenResolverImpl implements TokenResolver {
  resolveTokens(request: ResolveTokensRequest): Result<ResolvedDiagram, ResolveError> {
    const resolved = request.resolved;
    if (resolved === undefined) {
      return Err({ message: 'resolveTokens: request.resolved is required' });
    }
    const tokens = request.tokens;
    if (tokens === undefined) {
      return Ok(resolved);
    }
    // Collected, not thrown: one pass reports every bad reference.
    const unresolved: string[] = [];
    walk(resolved, tokens, unresolved);
    walk(resolved.canvas, tokens, unresolved);
    if (unresolved.length > 0) {
      const listed = [...new Set(unresolved)].sort().join(', ');
      return Err({ message: `unresolved token reference(s): ${listed}` });
    }
    return Ok(resolved);
  }
}

// A theme's components must resolve against THAT theme's tokens, so this
// runs per theme before the cascade merges components into elements. After
// merging, which theme a value came from is no longer recoverable.
export function resolveTokensIn(obj: unknown, tokens: Tokens): string[] {
  const unresolved: string[] = [];
  walk(obj, tokens, unresolved);
  return unresolved;
}

function walk(obj: unknown, tokens: Tokens, unresolved: string[]): void {
  if (obj === null || obj === undefined) return;
  if (typeof obj !== 'object') return;
  if (Array.isArray(obj)) {
    for (let i = 0; i < obj.length; i++) {
      const v = obj[i];
      if (typeof v === 'string') {
        obj[i] = resolveRef(v, tokens, unresolved);
      } else {
        walk(v, tokens, unresolved);
      }
    }
    return;
  }
  const record = obj as Record<string, unknown>;
  for (const key of Object.keys(record)) {
    if (key === '$typeName' || key === '$unknown') continue;
    const v = record[key];
    if (typeof v === 'string') {
      record[key] = resolveRef(v, tokens, unresolved);
    } else {
      walk(v, tokens, unresolved);
    }
  }
}

function resolveRef(value: string, tokens: Tokens, unresolved: string[]): string {
  if (!TOKEN_REF_RE.test(value)) return value;
  const dot = value.indexOf('.');
  if (dot < 0) return value;
  const looked = lookup(tokens, value.substring(1, dot), value.substring(dot + 1));
  // Nothing downstream guards stroke, fill or text colour against a '$'.
  if (looked === undefined) {
    unresolved.push(value);
    return value;
  }
  if (typeof looked === 'number') return String(looked);
  return looked;
}

function lookup(tokens: Tokens, table: string, key: string): string | number | undefined {
  switch (table) {
    // Depth is 1: a palette value is literal, so the result is never chased.
    case 'roles': {
      const role = tokens.roles[key];
      if (role === undefined) return undefined;
      const hop = PALETTE_REF_RE.exec(role);
      return hop === null ? role : tokens.palette[hop[1]];
    }
    case 'palette': return tokens.palette[key];
    // Tokens.fonts holds a structured FontSpec, but every consumer of a font
    // token is a string field (Typography.font). The family is the only part
    // that can be substituted into one, so that is what $fonts.<name> means.
    case 'fonts': return tokens.fonts[key]?.family;
    case 'sizes': return tokens.sizes[key];
    case 'dashes': return tokens.dashes[key];
    case 'shape_paths': return tokens.shapePaths[key];
    default: return undefined;
  }
}
