// SPDX-License-Identifier: AGPL-3.0-or-later

// @generated by archebuild — do not edit. Regenerated each build.

import { create } from '@bufbuild/protobuf';
import { FontSpecSchema, NodeComponentSchema, EdgeComponentSchema, Theme, ThemeSchema, TokensSchema } from '@archeglyph/proto/gen/theme_pb';
import { ColorSchema, FillSchema, Glyph1DSchema, Glyph2DSchema, ShapeType, StrokeSchema } from '@archeglyph/proto/gen/style_pb';

// Default starter vocabulary: one node look, one edge look, both named "glyph"
// per bind's implicit default. Deliberately the most geometric/boring shape
// (plain square outline + fill) — theme.proto has no default_* or
// kind_to_*_component mapping (design.md L1138), so this is just a starting
// palette, not a schema-mandated shape. dark flips the two colors so the
// shape still reads against the theme's own (dark) canvas.
function glyphNodeComponent(strokeColor: string, fillColor: string) {
  return create(NodeComponentSchema, {
    name: 'glyph',
    shape: create(Glyph2DSchema, {
      shapeKind: { case: 'standard', value: ShapeType.SHAPE_RECT },
      cornerRadius: 0,
      stroke: create(StrokeSchema, { paint: { case: 'color', value: create(ColorSchema, { value: strokeColor }) } }),
      fill: create(FillSchema, { paint: { case: 'color', value: create(ColorSchema, { value: fillColor }) } }),
    }),
  });
}

function glyphEdgeComponent(strokeColor: string) {
  return create(EdgeComponentSchema, {
    name: 'glyph',
    connection: create(Glyph1DSchema, {
      stroke: create(StrokeSchema, { paint: { case: 'color', value: create(ColorSchema, { value: strokeColor }) } }),
    }),
  });
}

export function darkTheme(): Theme {
  return create(ThemeSchema, {
    schemaVersion: 1,
    name: 'dark',
    tokens: create(TokensSchema, {
      colors: {
        background: '#1a1b26',
        foreground: '#c0caf5',
        muted: '#565f89',
        primary: '#7aa2f7',
        accent: '#bb9af7',
        success: '#9ece6a',
        warning: '#e0af68',
        danger: '#f7768e',
      },
      fonts: {
        body: create(FontSpecSchema, {
          family: '-apple-system, BlinkMacSystemFont, Segoe UI, Helvetica, Arial, sans-serif',
        }),
        mono: create(FontSpecSchema, {
          family: "'Noto Sans Mono', ui-monospace, Menlo, Consolas, Liberation Mono, monospace",
        }),
      },
      sizes: {
        stroke_thin: 1.0,
        stroke_normal: 1.5,
        font_small: 11.0,
        font_normal: 13.0,
        font_large: 16.0,
      },
      spacings: {
        node_padding: 12.0,
        label_offset: 6.0,
        node_spacing: 24.0,
      },
      dashes: {
        dashed: '6,4',
        dotted: '2,3',
      },
      shapePaths: {},
    }),
    nodeComponents: [glyphNodeComponent('#FFFFFF', '#000000')],
    edgeComponents: [glyphEdgeComponent('#FFFFFF')],
  });
}
export function lightTheme(): Theme {
  const tokens = create(TokensSchema, {
    colors: {
      background: '#F5F5F5',
      foreground: '#1E1E1E',
      muted: '#8A8A8A',
      primary: '#0066CC',
      accent: '#7C3AED',
      success: '#16A34A',
      warning: '#D97706',
      danger: '#DC2626',
    },
    fonts: {
      body: create(FontSpecSchema, { family: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif" }),
      mono: create(FontSpecSchema, { family: "'Noto Sans Mono', ui-monospace, Menlo, 'Cascadia Code', Consolas, monospace" }),
    },
    sizes: {
      stroke_thin: 1,
      stroke_normal: 2,
      font_small: 11,
      font_normal: 13,
      font_large: 16,
    },
    spacings: {
      node_padding: 12,
      label_offset: 6,
      node_spacing: 24,
    },
    dashes: {
      dashed: '6,4',
      dotted: '2,3',
    },
    shapePaths: {},
  });
  return create(ThemeSchema, {
    schemaVersion: 1,
    name: 'light',
    tokens,
    nodeComponents: [glyphNodeComponent('#000000', '#FFFFFF')],
    edgeComponents: [glyphEdgeComponent('#000000')],
  });
}
export function getBundledTheme(name: string): Theme {
  if (name === 'dark') return darkTheme();
  return lightTheme();
}
