// @generated by archebuild — do not edit. Regenerated each build.

export enum ViolationKind {
  GroupCycle,
  EdgeSourceMissing,
  EdgeTargetMissing,
  NodeParentGroupMissing,
  GroupParentGroupMissing,
}

export class Violation {
  kind!: ViolationKind;
  location!: string;
  message!: string;
}
