// @generated by archebuild — do not edit. Regenerated each build.

export enum ViolationKind {
  GROUP_CYCLE = 'GROUP_CYCLE',
  EDGE_SOURCE_MISSING = 'EDGE_SOURCE_MISSING',
  EDGE_TARGET_MISSING = 'EDGE_TARGET_MISSING',
  NODE_PARENT_GROUP_MISSING = 'NODE_PARENT_GROUP_MISSING',
  GROUP_PARENT_GROUP_MISSING = 'GROUP_PARENT_GROUP_MISSING',
}

// Declaration order for deterministic violation sort. Mirrors the enum above.
export const VIOLATION_KIND_ORDER: Record<ViolationKind, number> = {
  [ViolationKind.GROUP_CYCLE]: 0,
  [ViolationKind.EDGE_SOURCE_MISSING]: 1,
  [ViolationKind.EDGE_TARGET_MISSING]: 2,
  [ViolationKind.NODE_PARENT_GROUP_MISSING]: 3,
  [ViolationKind.GROUP_PARENT_GROUP_MISSING]: 4,
};

export class Violation {
  kind!: ViolationKind;
  location!: string;
  message!: string;
}
