// SPDX-License-Identifier: MPL-2.0
// @generated by archebuild — do not edit. Regenerated each build.

import { Localization } from '@archeglyph/proto/gen/content_pb';
import { Glyph2D, NodeLayout, Typography } from '@archeglyph/proto/gen/style_pb';
import type { Vec2 } from '../../geometry/vec2';

export class LaidOutNode {
  id!: string;
  parentGroup?: string;
  position!: Vec2;
  size!: Vec2;
  shape!: Glyph2D;
  typography!: Typography;
  label: Localization[] = [];
  layout?: NodeLayout;
}
