// SPDX-License-Identifier: AGPL-3.0-or-later
// @generated by archebuild — do not edit. Regenerated each build.

import { Localization } from '@archeglyph/proto/gen/content_pb';
import { Glyph2D, NodeLayout, Typography, Vec2 } from '@archeglyph/proto/gen/style_pb';

export class LaidOutNode {
  id!: string;
  parentGroup?: string;
  position!: Vec2;
  size!: Vec2;
  shape!: Glyph2D;
  typography!: Typography;
  label: Localization[] = [];
  layout?: NodeLayout;
}
