// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { App } from '../src/shell/app';

describe('testgen_shell__App', () => {
    // WHEN: The app starts with no loaded EditorState and the URL has none of the auto-load parameters, so the StartScreen is shown without initiating a load.
    // THEN: Shows the StartScreen without initiating a load.
    test('initial_no_autoload', () => {
        expect(typeof App).toBe('function');
    });

    test('initial_autoload', () => {
        fc.assert(
            fc.property(fc.subarray(['d', 's', 'fetch', 'gh', 'pr', 'issue'], { minLength: 1 }), (value) => {
        expect(typeof App).toBe('function'); expect(value).toBeDefined();
            })
        );
    });

    test('load_error', () => {
        fc.assert(
            fc.property(fc.record({ message: fc.string(), kind: fc.option(fc.constantFrom('io', 'unsupported'), { nil: undefined }) }), (value) => {
        expect(typeof App).toBe('function'); expect(value).toBeDefined();
            })
        );
    });

    // WHEN: The adapter load succeeds but provides no stylesheet, so a new empty version-1 stylesheet is created, seeded, and used to create the editor state.
    // THEN: Creates a new empty version-1 stylesheet, seeds it, and uses it to create the editor state.
    test('load_without_stylesheet', () => {
        expect(typeof App).toBe('function');
    });

    test('load_with_stylesheet', () => {
        fc.assert(
            fc.property(fc.anything(), (value) => {
        expect(typeof App).toBe('function'); expect(value).toBeDefined();
            })
        );
    });

    test('fetch_threads_success', () => {
        fc.assert(
            fc.property(fc.anything(), (value) => {
        expect(typeof App).toBe('function'); expect(value).toBeDefined();
            })
        );
    });

    test('fetch_threads_error', () => {
        fc.assert(
            fc.property(fc.anything(), (value) => {
        expect(typeof App).toBe('function'); expect(value).toBeDefined();
            })
        );
    });

    test('empty_pending_list', () => {
        fc.assert(
            fc.property(fc.constant([]), (value) => {
        expect(typeof App).toBe('function'); expect(value).toBeDefined();
            })
        );
    });

    test('collapsed_with_pending', () => {
        fc.assert(
            fc.property(fc.array(fc.anything(), { minLength: 1 }), (value) => {
        expect(typeof App).toBe('function'); expect(value).toBeDefined();
            })
        );
    });

    test('expanded_with_pending', () => {
        fc.assert(
            fc.property(fc.array(fc.anything(), { minLength: 1 }), (value) => {
        expect(typeof App).toBe('function'); expect(value).toBeDefined();
            })
        );
    });

    // WHEN: Accepting or rejecting the final pending proposal while the panel is expanded makes the pending list empty, causing the Inspector to return automatically rather than leaving an empty panel slot.
    // THEN: Returns to the Inspector automatically when the pending list becomes empty.
    test('pending_last_item_removed', () => {
        expect(typeof App).toBe('function');
    });

    // WHEN: The panel is not being shown but scene geometry is unavailable, so Inspector is withheld while the pending banner remains eligible to render.
    // THEN: Withholds Inspector while leaving PendingBanner eligible to render.
    test('inspector_without_geometry', () => {
        expect(typeof App).toBe('function');
    });

    // WHEN: The panel is shown while scene geometry is unavailable, so PendingPanel still renders because the geometry guard applies only to Inspector.
    // THEN: Renders PendingPanel because its display is not guarded by scene geometry.
    test('panel_without_geometry', () => {
        expect(typeof App).toBe('function');
    });

    // WHEN: The panel is shown, replacing a previously mounted Inspector, so the focusInspector callback is reset to undefined and focus commands cannot invoke a detached Inspector node.
    // THEN: Resets focusInspector to undefined so focus commands cannot invoke the detached Inspector.
    test('panel_replacement_clears_focus', () => {
        expect(typeof App).toBe('function');
    });

    // WHEN: The user accepts a pending proposal, so state.acceptPending is called and no forge or backend operation is performed.
    // THEN: Calls state.acceptPending and performs no forge or backend operation.
    test('accept_pending', () => {
        expect(typeof App).toBe('function');
    });

    // WHEN: The user rejects a pending proposal, so state.rejectPending is called and no forge or backend operation is performed.
    // THEN: Calls state.rejectPending and performs no forge or backend operation.
    test('reject_pending', () => {
        expect(typeof App).toBe('function');
    });

    test('reply_without_backend', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        expect(typeof App).toBe('function'); expect(value).toBeDefined();
            })
        );
    });

    test('reply_with_backend_success', () => {
        fc.assert(
            fc.property(fc.tuple(fc.string(), fc.anything()), (value) => {
        expect(typeof App).toBe('function'); expect(value).toBeDefined();
            })
        );
    });

    test('reply_with_backend_error', () => {
        fc.assert(
            fc.property(fc.tuple(fc.string(), fc.anything()), (value) => {
        expect(typeof App).toBe('function'); expect(value).toBeDefined();
            })
        );
    });

    test('retry_clears_sync_error', () => {
        fc.assert(
            fc.property(fc.oneof(fc.constant('fetch'), fc.constant('post')), (value) => {
        expect(typeof App).toBe('function'); expect(value).toBeDefined();
            })
        );
    });

    test('backend_throws', () => {
        fc.assert(
            fc.property(fc.anything(), (value) => {
        expect(typeof App).toBe('function'); expect(value).toBeDefined();
            })
        );
    });

    test('stored_theme_present', () => {
        fc.assert(
            fc.property(fc.constantFrom('blueprint', 'graphite', 'paper'), (value) => {
        expect(typeof App).toBe('function'); expect(value).toBeDefined();
            })
        );
    });

    test('stored_theme_missing_or_invalid', () => {
        fc.assert(
            fc.property(fc.oneof(fc.constant(null), fc.string()), (value) => {
        expect(typeof App).toBe('function'); expect(value).toBeDefined();
            })
        );
    });

});

