// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';

import { EditorState } from '../src/state/editor_state';

describe('testgen_state__version', () => {
    test.skip('read_current_counter', () => {
        // test generation failed: symbol \'version\' is not reachable from a generated test file (not exported)
    });

    test.skip('read_without_write', () => {
        // test generation failed: symbol \'version\' is not reachable from a generated test file (not exported)
    });

    test.skip('after_single_write', () => {
        // test generation failed: symbol \'version\' is not reachable from a generated test file (not exported)
    });

    test.skip('after_multiple_writes', () => {
        // test generation failed: symbol \'version\' is not reachable from a generated test file (not exported)
    });

});

