// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';

import { EditorState } from '../src/state/editor_state';

describe('testgen_state__rejectPending', () => {
    test.skip('matching_pending_proposal', () => {
        // test generation failed: symbol \'rejectPending\' is not reachable from a generated test file (not exported)
    });

    test.skip('missing_pending_proposal', () => {
        // test generation failed: symbol \'rejectPending\' is not reachable from a generated test file (not exported)
    });

});

