// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { ContextMenu } from '../src/shell/context_menu';

describe('testgen_shell__ContextMenu', () => {
    test.skip('non_empty_items', () => {
        // test generation failed: generated body does not reference the bound value `value`
    });

    // WHEN: An empty items array is provided; the component renders nothing rather than an empty menu box.
    // THEN: Renders nothing instead of an empty menu box.
    test('empty_items', () => {
        expect(ContextMenu).toBeDefined();
    });

    test.skip('arrow_down_with_room', () => {
        // test generation failed: generated body does not reference the bound value `value`
    });

    // WHEN: ArrowDown is pressed while the last row is highlighted; the highlight remains on the last row and the key event does not propagate.
    // THEN: Keeps the highlight on the last row and stops propagation.
    test('arrow_down_at_end', () => {
        expect(ContextMenu).toBeDefined();
    });

    test.skip('arrow_up_with_room', () => {
        // test generation failed: generated body does not reference the bound value `value`
    });

    // WHEN: ArrowUp is pressed while the first row is highlighted; the highlight remains on the first row and the key event does not propagate.
    // THEN: Keeps the highlight on the first row and stops propagation.
    test('arrow_up_at_start', () => {
        expect(ContextMenu).toBeDefined();
    });

    test.skip('enter_highlighted_row', () => {
        // test generation failed: generated body does not reference the bound value `value`
    });

    // WHEN: Escape is pressed while the menu is open; onClose is called and the key event is stopped so the document escape handler does not also clear the selection.
    // THEN: Calls onClose and stops propagation so the document escape handler does not clear the selection.
    test('escape_open_menu', () => {
        expect(ContextMenu).toBeDefined();
    });

    // WHEN: A click occurs anywhere outside the menu; onClose is called.
    // THEN: Calls onClose when a click occurs outside the menu.
    test('outside_click', () => {
        expect(ContextMenu).toBeDefined();
    });

    // WHEN: A scroll occurs while the menu is open; onClose is called instead of leaving the menu pinned to a stale client point.
    // THEN: Calls onClose instead of leaving the menu pinned to a stale client point.
    test('scroll_while_open', () => {
        expect(ContextMenu).toBeDefined();
    });

    // WHEN: A resize occurs while the menu is open; onClose is called instead of leaving the menu pinned to a stale client point.
    // THEN: Calls onClose instead of leaving the menu pinned to a stale client point.
    test('resize_while_open', () => {
        expect(ContextMenu).toBeDefined();
    });

    test.skip('position_within_window', () => {
        // test generation failed: generated body does not reference the bound value `value`
    });

    test.skip('right_edge_clamping', () => {
        // test generation failed: generated body does not reference the bound value `value`
    });

    test.skip('bottom_edge_clamping', () => {
        // test generation failed: generated body does not reference the bound value `value`
    });

    test.skip('negative_clamped_position', () => {
        // test generation failed: generated body does not reference the bound value `value`
    });

    test.skip('menu_taller_than_window', () => {
        // test generation failed: generated body does not reference the bound value `value`
    });

});

