// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { EDITOR_THEMES } from '../src/shell/editor_theme';
import { FileIsland, FileIslandProps } from '../src/shell/file_island';

describe('testgen_shell__FileIsland', () => {
    test('file_name_rendered', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        expect(typeof FileIsland).toBe("function");
        expect(typeof value).toBe("string");
            })
        );
    });

    // WHEN: Status is idle; no status text is rendered.
    // THEN: Renders no status text when the status is idle.
    test('idle_status', () => {
        expect(typeof FileIsland).toBe("function");
    });

    // WHEN: Status is saving; the status text is rendered as "Saving...".
    // THEN: Renders the status text "Saving..." when saving.
    test('saving_status', () => {
        expect(typeof FileIsland).toBe("function");
    });

    // WHEN: Status is saved; the status text is rendered as "Saved".
    // THEN: Renders the status text "Saved" when saved.
    test('saved_status', () => {
        expect(typeof FileIsland).toBe("function");
    });

    // WHEN: Status is unsaved; the status text is rendered as "Unsaved".
    // THEN: Renders the status text "Unsaved" when unsaved.
    test('unsaved_status', () => {
        expect(typeof FileIsland).toBe("function");
    });

    // WHEN: Status is error; the status text is rendered as "Save failed", using --ag-danger, and the error indicator replaces the dirty dot.
    // THEN: Renders "Save failed" in --ag-danger and replaces the dirty dot with the error indicator.
    test('error_status', () => {
        expect(typeof FileIsland).toBe("function");
    });

    // WHEN: The document is not dirty; the --ag-teal dirty dot is not shown.
    // THEN: Does not show the --ag-teal dirty dot when the document is clean.
    test('clean_document', () => {
        expect(typeof FileIsland).toBe("function");
    });

    test('dirty_document', () => {
        fc.assert(
            fc.property(fc.constantFrom("idle", "saving", "saved", "unsaved"), (value) => {
        expect(typeof FileIsland).toBe("function");
        expect(["idle", "saving", "saved", "unsaved"]).toContain(value);
            })
        );
    });

    test('dirty_saving_or_saved', () => {
        fc.assert(
            fc.property(fc.constantFrom("saving", "saved"), (value) => {
        expect(typeof FileIsland).toBe("function");
        expect(["saving", "saved"]).toContain(value);
            })
        );
    });

    // WHEN: canSave is true; the Save button is rendered and can provide the real click needed to initiate the first file write.
    // THEN: Renders a Save button that provides the real click needed to initiate the first file write.
    test('save_available', () => {
        expect(typeof FileIsland).toBe("function");
    });

    // WHEN: canSave is false; the Save button is not rendered.
    // THEN: Does not render the Save button when canSave is false.
    test('save_unavailable', () => {
        expect(typeof FileIsland).toBe("function");
    });

    test('theme_picker_options', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        expect(typeof FileIsland).toBe("function");
        expect(typeof value).toBe("string");
            })
        );
    });

    test('theme_selection_change', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        expect(typeof FileIsland).toBe("function");
        expect(typeof value).toBe("string");
            })
        );
    });

});

