// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import { create } from '@bufbuild/protobuf';
import * as fc from 'fast-check';

import { editableChanges } from '../src/state/editable_changes';
import { Diagram } from '../../proto/src/gen/content_pb';
import { StyleEdit } from '../../proto/src/gen/style_pb';
import { DiagramSchema, Edge, EdgeSchema, GraphSchema, Group, GroupSchema, Node, NodeSchema } from '../../proto/src/gen/content_pb';
import { AnnotationStyleChange, AnnotationStyleChangeSchema, EdgeStyleChange, EdgeStyleChangeSchema, GroupStyleChange, GroupStyleChangeSchema, NodeStyleChange, NodeStyleChangeSchema, StyleEditSchema } from '../../proto/src/gen/style_pb';

describe('testgen_state__editableChanges', () => {
    const makeAnnotationChange = (id: string): AnnotationStyleChange => create(AnnotationStyleChangeSchema, {annotationId: id});

    const makeDiagram = (nodeIds: string[], edgeIds: string[], groupIds: string[]): Diagram => create(DiagramSchema, {graph: create(GraphSchema, {nodes: Object.fromEntries(nodeIds.map((id: string): [string, Node] => [id, create(NodeSchema, {id})])), edges: Object.fromEntries(edgeIds.map((id: string): [string, Edge] => [id, create(EdgeSchema, {id})])), groups: Object.fromEntries(groupIds.map((id: string): [string, Group] => [id, create(GroupSchema, {id})]))})});

    const makeEdgeChange = (id: string): EdgeStyleChange => create(EdgeStyleChangeSchema, {edgeId: id});

    const makeEdit = (nodeChanges: NodeStyleChange[], edgeChanges: EdgeStyleChange[], groupChanges: GroupStyleChange[], annotationChanges: AnnotationStyleChange[]): StyleEdit => create(StyleEditSchema, {nodeChanges, edgeChanges, groupChanges, annotationChanges});

    const makeGroupChange = (id: string): GroupStyleChange => create(GroupStyleChangeSchema, {groupId: id});

    const makeNodeChange = (id: string): NodeStyleChange => create(NodeStyleChangeSchema, {nodeId: id});

    test('matching_node_change', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const change: NodeStyleChange = makeNodeChange(value);
        const diagram: Diagram = makeDiagram([value], [], []);
        const result: StyleEdit = editableChanges(makeEdit([change], [], [], []), diagram);
        expect(result.nodeChanges).toEqual([change]);
            })
        );
    });

    test('stale_node_change', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const change: NodeStyleChange = makeNodeChange(value);
        const diagram: Diagram = makeDiagram([], [], []);
        const result: StyleEdit = editableChanges(makeEdit([change], [], [], []), diagram);
        expect(result.nodeChanges).toEqual([]);
            })
        );
    });

    test('matching_edge_change', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const change: EdgeStyleChange = makeEdgeChange(value);
        const diagram: Diagram = makeDiagram([], [value], []);
        const result: StyleEdit = editableChanges(makeEdit([], [change], [], []), diagram);
        expect(result.edgeChanges).toEqual([change]);
            })
        );
    });

    test('stale_edge_change', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const change: EdgeStyleChange = makeEdgeChange(value);
        const diagram: Diagram = makeDiagram([], [], []);
        const result: StyleEdit = editableChanges(makeEdit([], [change], [], []), diagram);
        expect(result.edgeChanges).toEqual([]);
            })
        );
    });

    test('matching_group_change', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const change: GroupStyleChange = makeGroupChange(value);
        const diagram: Diagram = makeDiagram([], [], [value]);
        const result: StyleEdit = editableChanges(makeEdit([], [], [change], []), diagram);
        expect(result.groupChanges).toEqual([change]);
            })
        );
    });

    test('stale_group_change', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const change: GroupStyleChange = makeGroupChange(value);
        const diagram: Diagram = makeDiagram([], [], []);
        const result: StyleEdit = editableChanges(makeEdit([], [], [change], []), diagram);
        expect(result.groupChanges).toEqual([]);
            })
        );
    });

    test('mixed_edit_entries', () => {
        fc.assert(
            fc.property(fc.record({node: fc.string(), edge: fc.string(), group: fc.string()}), (value) => {
        const nodePresent: string = `${value.node}-present`;
        const nodeAbsent: string = `${value.node}-absent`;
        const edgePresent: string = `${value.edge}-present`;
        const edgeAbsent: string = `${value.edge}-absent`;
        const groupPresent: string = `${value.group}-present`;
        const groupAbsent: string = `${value.group}-absent`;
        const nodePresentChange: NodeStyleChange = makeNodeChange(nodePresent);
        const nodeAbsentChange: NodeStyleChange = makeNodeChange(nodeAbsent);
        const edgePresentChange: EdgeStyleChange = makeEdgeChange(edgePresent);
        const edgeAbsentChange: EdgeStyleChange = makeEdgeChange(edgeAbsent);
        const groupPresentChange: GroupStyleChange = makeGroupChange(groupPresent);
        const groupAbsentChange: GroupStyleChange = makeGroupChange(groupAbsent);
        const diagram: Diagram = makeDiagram([nodePresent], [edgePresent], [groupPresent]);
        const result: StyleEdit = editableChanges(makeEdit([nodePresentChange, nodeAbsentChange], [edgePresentChange, edgeAbsentChange], [groupPresentChange, groupAbsentChange], []), diagram);
        expect(result.nodeChanges).toEqual([nodePresentChange]);
        expect(result.edgeChanges).toEqual([edgePresentChange]);
        expect(result.groupChanges).toEqual([groupPresentChange]);
            })
        );
    });

    test('annotation_changes_unfiltered', () => {
        fc.assert(
            fc.property(fc.array(fc.string()), (value) => {
        const changes: AnnotationStyleChange[] = value.map((id: string): AnnotationStyleChange => makeAnnotationChange(id));
        const diagram: Diagram = makeDiagram([], [], []);
        const result: StyleEdit = editableChanges(makeEdit([], [], [], changes), diagram);
        expect(result.annotationChanges).toEqual(changes);
            })
        );
    });

    test('metadata_preserved', () => {
        fc.assert(
            fc.property(fc.record({id: fc.string(), baseHash: fc.option(fc.string(), {nil: undefined})}), (value) => {
        const edit: StyleEdit = makeEdit([], [], [], []);
        edit.id = value.id;
        if (value.baseHash === undefined) {
          edit.baseHash = undefined;
        } else {
          edit.baseHash = value.baseHash;
        }
        const result: StyleEdit = editableChanges(edit, makeDiagram([], [], []));
        expect(result.id).toBe(value.id);
        expect(result.baseHash).toBe(value.baseHash);
            })
        );
    });

    test('all_lists_empty', () => {
        fc.assert(
            fc.property(fc.array(fc.string()), (value) => {
        const nodeChanges: NodeStyleChange[] = value.map((id: string): NodeStyleChange => makeNodeChange(`stale-${id}`));
        const result: StyleEdit = editableChanges(makeEdit(nodeChanges, [], [], []), makeDiagram([], [], []));
        expect(result.nodeChanges).toEqual([]);
        expect(result.edgeChanges).toEqual([]);
        expect(result.groupChanges).toEqual([]);
        expect(result.annotationChanges).toEqual([]);
            })
        );
    });

    test('annotation_only_edit', () => {
        fc.assert(
            fc.property(fc.array(fc.string(), {minLength: 1}), (value) => {
        const changes: AnnotationStyleChange[] = value.map((id: string): AnnotationStyleChange => makeAnnotationChange(id));
        const result: StyleEdit = editableChanges(makeEdit([], [], [], changes), makeDiagram([], [], []));
        expect(result.nodeChanges).toEqual([]);
        expect(result.edgeChanges).toEqual([]);
        expect(result.groupChanges).toEqual([]);
        expect(result.annotationChanges).toEqual(changes);
            })
        );
    });

    test('base_only_target_is_filtered', () => {
        fc.assert(
            fc.property(fc.constantFrom('node', 'edge', 'group'), (value) => {
        const diagram: Diagram = makeDiagram([], [], []);
        if (value === 'node') {
          const change: NodeStyleChange = makeNodeChange('absent-node');
          const result: StyleEdit = editableChanges(makeEdit([change], [], [], []), diagram);
          expect(result.nodeChanges).toEqual([]);
        } else if (value === 'edge') {
          const change: EdgeStyleChange = makeEdgeChange('absent-edge');
          const result: StyleEdit = editableChanges(makeEdit([], [change], [], []), diagram);
          expect(result.edgeChanges).toEqual([]);
        } else {
          const change: GroupStyleChange = makeGroupChange('absent-group');
          const result: StyleEdit = editableChanges(makeEdit([], [], [change], []), diagram);
          expect(result.groupChanges).toEqual([]);
        }
            })
        );
    });

});

