// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';

import { createUiState } from '../src/ui_state/ui_state';

describe('testgen_ui_state__createUiState', () => {
    // WHEN: Calling createUiState initializes the overlay signal to undefined and returns both the overlay signal and its setter on the UI state handle.
    // THEN: Calling createUiState initializes the overlay signal to undefined and returns both the overlay signal and its setter on the UI state handle.
    test('initial_overlay_undefined', () => {
        const state = createUiState();
        expect(state.overlay()).toBeUndefined();
        expect(typeof state.setOverlay).toBe('function');
    });

});

