// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import { create } from '@bufbuild/protobuf';
import * as fc from 'fast-check';

import { UrlParamDiagramSource } from '../src/diff/url_param_diagram_source';

describe('testgen_diff__UrlParamDiagramSource', () => {
    test('inline_value_precedence', () => {
        fc.assert(
            fc.property(fc.record({ inline: fc.integer().map((n) => btoa(JSON.stringify({ version: n }))), remote: fc.option(fc.string(), { nil: null }) }), (value) => {
        const inline = value.inline;
        const remote = value.remote;
        const originalFetch = globalThis.fetch;
        let fetchCalls = 0;
        globalThis.fetch = (async (..._args: Parameters<typeof fetch>): Promise<Response> => {
          fetchCalls += 1;
          return new Response('{}', { status: 200 });
        }) as typeof fetch;
        const source = new UrlParamDiagramSource(inline, remote);
        return source.load().then((result) => {
          expect(result.ok).toBe(true);
          expect(fetchCalls).toBe(0);
        }).finally(() => {
          globalThis.fetch = originalFetch;
        });
            })
        );
    });

    test('remote_success', () => {
        fc.assert(
            fc.property(fc.record({ url: fc.string(), status: fc.integer({ min: 200, max: 299 }) }), (value) => {
        const originalFetch = globalThis.fetch;
        let requestedUrl: string | undefined;
        globalThis.fetch = (async (input: RequestInfo | URL): Promise<Response> => {
          requestedUrl = String(input);
          return new Response('{}', { status: value.status });
        }) as typeof fetch;
        const source = new UrlParamDiagramSource(null, value.url);
        return source.load().then((result) => {
          expect(requestedUrl).toBe(value.url);
          expect(result.ok).toBe(true);
        }).finally(() => {
          globalThis.fetch = originalFetch;
        });
            })
        );
    });

    test('remote_fetch_failure', () => {
        fc.assert(
            fc.property(fc.record({ url: fc.string(), status: fc.oneof(fc.integer({ min: 100, max: 199 }), fc.integer({ min: 300, max: 599 })) }), (value) => {
        const originalFetch = globalThis.fetch;
        globalThis.fetch = (async (_input: RequestInfo | URL): Promise<Response> => {
          return new Response('', { status: value.status });
        }) as typeof fetch;
        const source = new UrlParamDiagramSource(null, value.url);
        return source.load().then((result) => {
          expect(result.ok).toBe(false);
          if (!result.ok) {
            expect(result.error.kind).toBe('io');
            expect(result.error.message).toContain(value.url);
            expect(result.error.message).toContain(String(value.status));
          }
        }).finally(() => {
          globalThis.fetch = originalFetch;
        });
            })
        );
    });

    // WHEN: Both the inline value and remote URL are null; load returns Err rather than an empty diagram because the link is malformed.
    // THEN: Returns Err because neither diagram source exists, rather than rendering an empty diagram.
    test('missing_diagram_source', () => {
        const source = new UrlParamDiagramSource(null, null);
        return source.load().then((result) => {
          expect(result.ok).toBe(false);
        });
    });

});

