// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { modalDelta } from '../src/gestures/modal_aim';

describe('testgen_gestures__modalDelta', () => {
    test('undefined_direction', () => {
        fc.assert(
            fc.property(fc.array(fc.integer({ min: 0, max: 9 }), { minLength: 0, maxLength: 6 }).map((digits: number[]): string => digits.join('')), (value) => {
        expect(modalDelta({ kind: 'grab', refs: [], direction: undefined, digits: value })).toEqual({ x: 0, y: 0 });
            })
        );
    });

    // WHEN: The direction is 'up' and the distance digits are empty; magnitude is 0 and the result is { x: 0, y: 0 }.
    // THEN: Returns { x: 0, y: 0 } because the empty distance has magnitude 0.
    test('up_empty_distance', () => {
        expect(modalDelta({ kind: 'grab', refs: [], direction: 'up', digits: '' })).toEqual({ x: 0, y: 0 });
    });

    test('up_typed_distance', () => {
        fc.assert(
            fc.property(fc.array(fc.integer({ min: 0, max: 9 }), { minLength: 1, maxLength: 6 }).map((digits: number[]): string => digits.join('')), (value) => {
        const magnitude: number = Number.parseInt(value, 10);
        expect(modalDelta({ kind: 'grab', refs: [], direction: 'up', digits: value })).toEqual({ x: 0, y: magnitude === 0 ? 0 : -magnitude });
            })
        );
    });

    // WHEN: The direction is 'down' and the distance digits are empty; magnitude is 0 and the result is { x: 0, y: 0 }.
    // THEN: Returns { x: 0, y: 0 } because the empty distance has magnitude 0.
    test('down_empty_distance', () => {
        expect(modalDelta({ kind: 'grab', refs: [], direction: 'down', digits: '' })).toEqual({ x: 0, y: 0 });
    });

    test('down_typed_distance', () => {
        fc.assert(
            fc.property(fc.array(fc.integer({ min: 0, max: 9 }), { minLength: 1, maxLength: 6 }).map((digits: number[]): string => digits.join('')), (value) => {
        const magnitude: number = Number.parseInt(value, 10);
        expect(modalDelta({ kind: 'grab', refs: [], direction: 'down', digits: value })).toEqual({ x: 0, y: magnitude });
            })
        );
    });

    // WHEN: The direction is 'left' and the distance digits are empty; magnitude is 0 and the result is { x: 0, y: 0 }.
    // THEN: Returns { x: 0, y: 0 } because the empty distance has magnitude 0.
    test('left_empty_distance', () => {
        expect(modalDelta({ kind: 'grab', refs: [], direction: 'left', digits: '' })).toEqual({ x: 0, y: 0 });
    });

    test('left_typed_distance', () => {
        fc.assert(
            fc.property(fc.array(fc.integer({ min: 0, max: 9 }), { minLength: 1, maxLength: 6 }).map((digits: number[]): string => digits.join('')), (value) => {
        const magnitude: number = Number.parseInt(value, 10);
        expect(modalDelta({ kind: 'grab', refs: [], direction: 'left', digits: value })).toEqual({ x: magnitude === 0 ? 0 : -magnitude, y: 0 });
            })
        );
    });

    // WHEN: The direction is 'right' and the distance digits are empty; magnitude is 0 and the result is { x: 0, y: 0 }.
    // THEN: Returns { x: 0, y: 0 } because the empty distance has magnitude 0.
    test('right_empty_distance', () => {
        expect(modalDelta({ kind: 'grab', refs: [], direction: 'right', digits: '' })).toEqual({ x: 0, y: 0 });
    });

    test('right_typed_distance', () => {
        fc.assert(
            fc.property(fc.array(fc.integer({ min: 0, max: 9 }), { minLength: 1, maxLength: 6 }).map((digits: number[]): string => digits.join('')), (value) => {
        const magnitude: number = Number.parseInt(value, 10);
        expect(modalDelta({ kind: 'grab', refs: [], direction: 'right', digits: value })).toEqual({ x: magnitude, y: 0 });
            })
        );
    });

});

