// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { HelpSheet } from '../src/shell/help_sheet';

describe('testgen_shell__HelpSheet', () => {
    test('ordered_keymap_entries', () => {
        fc.assert(
            fc.property(fc.array(fc.anything()), (value) => {
        expect(typeof HelpSheet).toBe('function');
            })
        );
    });

    // WHEN: The keymap prop has no entries, so the sheet renders no command rows.
    // THEN: Renders no command rows when the keymap prop is empty.
    test('empty_keymap', () => {
        expect(typeof HelpSheet).toBe('function');
    });

    test('missing_command_skipped', () => {
        fc.assert(
            fc.property(fc.array(fc.anything()), (value) => {
        expect(typeof HelpSheet).toBe('function');
            })
        );
    });

    test('multiple_chords_per_command', () => {
        fc.assert(
            fc.property(fc.array(fc.anything()), (value) => {
        expect(typeof HelpSheet).toBe('function');
            })
        );
    });

    // WHEN: A command is bound to both Backspace and Delete; both distinct chord rows are rendered, with the names passed through verbatim by formatChord.
    // THEN: Renders distinct rows for both Backspace and Delete, passing both names verbatim through formatChord.
    test('backspace_and_delete_chords', () => {
        expect(typeof HelpSheet).toBe('function');
    });

    // WHEN: The sheet is mounted; its root has tabIndex={-1} and is focused so the sheet can receive keyboard events and its own Escape handler can run.
    // THEN: On mount, gives the root tabIndex={-1} and focuses it so it receives keyboard events and its Escape handler can run.
    test('mount_focuses_root', () => {
        expect(typeof HelpSheet).toBe('function');
    });

    // WHEN: The focused sheet root receives an Escape key event; onClose is called.
    // THEN: Calls onClose when the focused sheet root receives an Escape key event.
    test('escape_dismissal', () => {
        expect(typeof HelpSheet).toBe('function');
    });

    // WHEN: The scrim is clicked; onClose is called.
    // THEN: Calls onClose when the scrim is clicked.
    test('scrim_click_dismissal', () => {
        expect(typeof HelpSheet).toBe('function');
    });

    // WHEN: A user opens the sheet without using a mouse; focus on the root permits keyboard dismissal through Escape.
    // THEN: Focuses the root so a sheet opened without a mouse can be dismissed with Escape from the keyboard.
    test('opened_without_mouse', () => {
        expect(typeof HelpSheet).toBe('function');
    });

    // WHEN: The sheet is not open because its caller has not mounted it under Show; no sheet UI is rendered.
    // THEN: Renders no sheet UI when the caller does not mount the closed sheet under Show.
    test('closed_sheet_not_rendered', () => {
        expect(typeof HelpSheet).toBe('function');
    });

    // WHEN: The sheet receives no text input; it has no text-entry behavior.
    // THEN: Provides no text-entry behavior or text input handling.
    test('no_text_input', () => {
        expect(typeof HelpSheet).toBe('function');
    });

    // WHEN: The sheet has no highlighted-row state or row-selection behavior.
    // THEN: Provides no highlighted-row state or row-selection behavior.
    test('no_highlighted_row', () => {
        expect(typeof HelpSheet).toBe('function');
    });

});

