// Originally generated by `archegraph testgen`, then HAND-REPAIRED so it
// typechecks. Regenerating this file discards those repairs.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';
// Hand-added: the generated helpers built proto messages as cast object
// literals, so every toEqual compared a real message (with $typeName)
// against a plain object. Building them properly fixes eight cases at once.
import { create } from '@bufbuild/protobuf';
import {
  CommentSchema, CommentThreadSchema, StyleEditSchema, StylesheetSchema,
} from '@archeglyph/proto/gen/style_pb';

import { mergeThreads } from '../src/pending/merge_threads';

describe('testgen_pending__mergeThreads', () => {
    const getComments = (stylesheet: Parameters<typeof mergeThreads>[0], index: number): unknown => stylesheet.pendingEdits[index]!.thread!.comments;

    const makeComment = (id: string, body: string) => create(CommentSchema, { id, body, timestampMs: 0n });

    const makeEntry = (editRef: string, comments: ReadonlyArray<ReturnType<typeof makeComment>>): Parameters<typeof mergeThreads>[1][number] =>
      ({ editRef, thread: create(CommentThreadSchema, { comments: [...comments] }) }) as Parameters<typeof mergeThreads>[1][number];

    const makeStylesheet = (comments: ReadonlyArray<ReturnType<typeof makeComment> | undefined>): Parameters<typeof mergeThreads>[0] =>
      create(StylesheetSchema, {
        schemaVersion: 1, nodes: {}, edges: {}, groups: {}, annotations: {},
        pendingEdits: comments.map((threadComment, index: number) => create(StyleEditSchema, {
          id: `edit-${index + 1}`,
          thread: create(CommentThreadSchema, { comments: threadComment === undefined ? [] : [threadComment] }),
        })),
      });

    // WHEN: The entries array is empty; the returned stylesheet is equal in content to the input stylesheet and is still a new Stylesheet rather than the same object.
    // THEN: Returns a new Stylesheet equal in content to the input stylesheet.
    test('empty_entries', () => {
        const stylesheet = makeStylesheet([]);
        const result = mergeThreads(stylesheet, []);
        expect(result).toEqual(stylesheet);
        expect(result).not.toBe(stylesheet);
    });

    test('matching_entry_adds_comments', () => {
        fc.assert(
            fc.property(fc.uniqueArray(fc.string({ minLength: 1 }), { minLength: 1, maxLength: 8 }), (value) => {
        const stylesheet = makeStylesheet([undefined]);
        const comments = value.map((id: string) => makeComment(id, `fetched-${id}`));
        const result = mergeThreads(stylesheet, [makeEntry("edit-1", comments)]);
        expect(getComments(result, 0)).toEqual(comments);
            })
        );
    });

    test('unmatched_entry_dropped', () => {
        fc.assert(
            fc.property(fc.string({ minLength: 1 }).filter((id: string) => id !== "present-edit"), (value) => {
        const stylesheet = makeStylesheet([]);
        const result = mergeThreads(stylesheet, [makeEntry(value, [makeComment("orphan-comment", "orphan")])]);
        expect(result.pendingEdits).toHaveLength(0);
            })
        );
    });

    test('per_thread_duplicate_suppressed', () => {
        fc.assert(
            fc.property(fc.string({ minLength: 1 }), (value) => {
        const existing = makeComment(value, "authoritative");
        const stylesheet = makeStylesheet([existing]);
        const fetched = makeComment(value, "stale-fetched-copy");
        const result = mergeThreads(stylesheet, [makeEntry("edit-1", [fetched])]);
        expect(getComments(result, 0)).toEqual([existing]);
            })
        );
    });

    test('cross_thread_same_id_allowed', () => {
        fc.assert(
            fc.property(fc.string({ minLength: 1 }), (value) => {
        const shared = makeComment(value, "target-copy");
        const stylesheet = makeStylesheet([makeComment(value, "other-thread-copy"), undefined]);
        const result = mergeThreads(stylesheet, [makeEntry("edit-2", [shared])]);
        expect(getComments(result, 1)).toEqual([shared]);
        // edit-1 keeps its own copy: the merge never touched it.
        expect(getComments(result, 0)).toHaveLength(1);
            })
        );
    });

    test('existing_comment_order_preserved', () => {
        fc.assert(
            fc.property(fc.uniqueArray(fc.string({ minLength: 1 }), { minLength: 1, maxLength: 8 }), (value) => {
        const existing = value.map((id: string) => makeComment(id, `existing-${id}`));
        const appended = makeComment("new-comment", "new");
        const stylesheet = create(StylesheetSchema, {
          schemaVersion: 1, nodes: {}, edges: {}, groups: {}, annotations: {},
          pendingEdits: [create(StyleEditSchema, {
            id: 'edit-1',
            thread: create(CommentThreadSchema, { comments: existing }),
          })],
        });
        const result = mergeThreads(stylesheet, [makeEntry("edit-1", [appended])]);
        expect(getComments(result, 0)).toEqual([...existing, appended]);
            })
        );
    });

    test('new_comments_append', () => {
        fc.assert(
            fc.property(fc.uniqueArray(fc.string({ minLength: 1 }), { minLength: 1, maxLength: 8 }), (value) => {
        const existing = makeComment("existing", "existing");
        const fetched = value.map((id: string) => makeComment(`new-${id}`, `new-${id}`));
        const stylesheet = makeStylesheet([existing]);
        const result = mergeThreads(stylesheet, [makeEntry("edit-1", fetched)]);
        expect(getComments(result, 0)).toEqual([existing, ...fetched]);
            })
        );
    });

    test('duplicate_editref_entry_order', () => {
        fc.assert(
            fc.property(fc.uniqueArray(fc.string({ minLength: 1 }), { minLength: 2, maxLength: 2 }), (value) => {
        const first = makeComment(`first-${value[0]}`, "first");
        const second = makeComment(`second-${value[1]}`, "second");
        const stylesheet = makeStylesheet([undefined]);
        const result = mergeThreads(stylesheet, [makeEntry("edit-1", [first]), makeEntry("edit-1", [second])]);
        expect(getComments(result, 0)).toEqual([first, second]);
            })
        );
    });

    test('within_entry_comment_order', () => {
        fc.assert(
            fc.property(fc.uniqueArray(fc.string({ minLength: 1 }), { minLength: 2, maxLength: 8 }), (value) => {
        const comments = value.map((id: string) => makeComment(id, `body-${id}`));
        const stylesheet = makeStylesheet([undefined]);
        const result = mergeThreads(stylesheet, [makeEntry("edit-1", comments)]);
        expect(getComments(result, 0)).toEqual(comments);
            })
        );
    });

    test('repeated_fetch_idempotent', () => {
        fc.assert(
            fc.property(fc.uniqueArray(fc.string({ minLength: 1 }), { minLength: 0, maxLength: 8 }), (value) => {
        const comments = value.map((id: string) => makeComment(id, `body-${id}`));
        const stylesheet = makeStylesheet([undefined]);
        const entries = [makeEntry("edit-1", comments)];
        const once = mergeThreads(stylesheet, entries);
        const twice = mergeThreads(once, entries);
        expect(twice).toEqual(once);
            })
        );
    });

    test('pure_result_copy', () => {
        fc.assert(
            fc.property(fc.uniqueArray(fc.string({ minLength: 1 }), { maxLength: 8 }), (value) => {
        const stylesheet = makeStylesheet([]);
        const entries = value.map((id: string) => makeEntry("missing-edit", [makeComment(id, `body-${id}`)]));
        const before = JSON.stringify(stylesheet);
        const result = mergeThreads(stylesheet, entries);
        expect(result).not.toBe(stylesheet);
        expect(JSON.stringify(stylesheet)).toBe(before);
            })
        );
    });

});

