// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { StateIsland, StateIslandProps } from '../src/shell/state_island';

describe('testgen_shell__StateIsland', () => {
    test('error_with_dismiss', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        expect(typeof StateIsland).toBe("function");
        expect(typeof value).toBe("string");
            })
        );
    });

    test('error_without_dismiss', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        expect(typeof StateIsland).toBe("function");
        expect(typeof value).toBe("string");
            })
        );
    });

    test('error_over_mode', () => {
        fc.assert(
            fc.property(fc.record({ error: fc.string(), mode: fc.string(), withDismiss: fc.boolean() }), (value) => {
        expect(typeof StateIsland).toBe("function");
        expect(typeof value.error).toBe("string");
        expect(typeof value.mode).toBe("string");
        expect(typeof value.withDismiss).toBe("boolean");
            })
        );
    });

    test('mode_only', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        expect(typeof StateIsland).toBe("function");
        expect(typeof value).toBe("string");
            })
        );
    });

});

