// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import { create } from '@bufbuild/protobuf';
import * as fc from 'fast-check';

import { UrlParamDiagramSource } from '../src/diff/url_param_diagram_source';

describe('testgen_diff__load', () => {
    test('valid_inline_base64', () => {
        fc.assert(
            fc.property(fc.record({ id: fc.stringMatching(/^[A-Za-z0-9 _-]*$/), schemaVersion: fc.integer({ min: 0, max: 1000 }) }).map((diagram) => btoa(JSON.stringify(diagram))), (value) => {
        const expected = JSON.parse(atob(value)) as { id: string };
        const source = new UrlParamDiagramSource(value);
        return source.load().then((result) => {
          expect(result.ok).toBe(true);
          if (result.ok) {
            expect(result.value.id).toBe(expected.id);
          }
        });
            })
        );
    });

    test('valid_url_response', () => {
        fc.assert(
            fc.property(fc.integer({ min: 0, max: 100000 }).map((n) => `https://example.com/diagram/${n}`), (value) => {
        const responseBody = JSON.stringify({ id: 'loaded-diagram', schemaVersion: 1 });
        const originalFetch = globalThis.fetch;
        globalThis.fetch = async (_input: RequestInfo | URL, _init?: RequestInit): Promise<Response> => new Response(responseBody, { status: 200 });
        const source = new UrlParamDiagramSource(value);
        return source.load().then((result) => {
          expect(result.ok).toBe(true);
          if (result.ok) {
            expect(result.value.id).toBe('loaded-diagram');
          }
        }).finally(() => {
          globalThis.fetch = originalFetch;
        });
            })
        );
    });

    test('non_success_url_response', () => {
        fc.assert(
            fc.property(fc.integer({ min: 100, max: 599 }).filter((status) => status < 200 || status >= 300), (value) => {
        const originalFetch = globalThis.fetch;
        globalThis.fetch = async (_input: RequestInfo | URL, _init?: RequestInit): Promise<Response> => new Response('', { status: value });
        const source = new UrlParamDiagramSource('https://example.com/failing-diagram');
        return source.load().then((result) => {
          expect(result.ok).toBe(false);
          if (!result.ok) {
            expect(result.error.kind).toBe('io');
            expect(result.error.message).toContain('https://example.com/failing-diagram');
            expect(result.error.message).toContain(String(value));
          }
        }).finally(() => {
          globalThis.fetch = originalFetch;
        });
            })
        );
    });

});

