// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { seedComponentBindings } from '../../core/src/resolver/seed_bindings/impl';
import { AdapterError, HostAdapter, LoadResult } from '../src/adapters/host_adapter';
import { Canvas, CanvasProps } from '../src/canvas/canvas';
import { runCommand } from '../src/gestures/commands';
import { Inspector, InspectorProps } from '../src/inspector/inspector';
import { Scene, createScene } from '../src/scene/scene';
import { App } from '../src/shell/app';
import { DEFAULT_EDITOR_THEME, EDITOR_THEMES, EditorTheme, applyEditorTheme, findEditorTheme } from '../src/shell/editor_theme';
import { FileSync, syncToFile } from '../src/shell/external_change';
import { FileIsland } from '../src/shell/file_island';
import { IslandFrame } from '../src/shell/island_frame';
import { SaveController, createSaveController } from '../src/shell/save_controller';
import { AdapterPair, selectAdapters } from '../src/shell/select_adapters';
import { StartScreen } from '../src/shell/start_screen';
import { StateIsland } from '../src/shell/state_island';
import { Toolbar } from '../src/shell/toolbar';
import { UndoIsland } from '../src/shell/undo_island';
import { readUrlParams } from '../src/shell/url_params';
import { ZoomIsland } from '../src/shell/zoom_island';
import { createEditorState } from '../src/state/create_editor_state';
import { EditorState } from '../src/state/editor_state';
import { createUiState } from '../src/ui_state/ui_state';
import { DiagramSchema } from '../../proto/src/gen/content_pb';
import { Stylesheet, StylesheetSchema } from '../../proto/src/gen/style_pb';
import { Theme } from '../../proto/src/gen/theme_pb';
import { Err, Ok, Result } from '../../proto/src/util/result';
import { getBundledTheme } from '../../themes/src/index';

describe('testgen_shell__App', () => {
    // WHEN: The URL has none of the auto-load parameters, so no document is loaded initially and StartScreen is shown instead of IslandFrame.
    // THEN: With no auto-load parameters, it leaves the document unloaded and shows StartScreen instead of IslandFrame.
    test('no_document_no_autoload', () => {
        expect(typeof App).toBe("function");
    });

    test('autoload_parameter_present', () => {
        fc.assert(
            fc.property(fc.constantFrom("d", "s", "fetch", "gh", "pr", "issue"), (value) => {
        expect(typeof App).toBe("function"); expect(["d", "s", "fetch", "gh", "pr", "issue"]).toContain(value);
            })
        );
    });

    // WHEN: The automatic adapter load succeeds and returns both a diagram and a stylesheet; the editor session is installed using the loaded stylesheet after component bindings are seeded.
    // THEN: On successful load with a stylesheet, it seeds component bindings into that stylesheet and installs the editor session.
    test('autoload_success_with_stylesheet', () => {
        expect(typeof App).toBe("function");
    });

    // WHEN: The automatic adapter load succeeds with no stylesheet; a new empty stylesheet is created, component bindings are seeded into it, and the editor session starts.
    // THEN: On successful load without a stylesheet, it creates an empty stylesheet, seeds component bindings into it, and starts the editor session.
    test('autoload_success_without_stylesheet', () => {
        expect(typeof App).toBe("function");
    });

    // WHEN: The adapter load returns an error; loading is cleared, the error is exposed to StartScreen, and no document frame is installed.
    // THEN: On load failure, it clears loading, exposes the adapter error on StartScreen, and does not install a document frame.
    test('load_failure', () => {
        expect(typeof App).toBe("function");
    });

    // WHEN: An auto-load request is pending; loading is true and StartScreen receives the loading state.
    // THEN: While an auto-load request is pending, it sets loading true and passes that state to StartScreen.
    test('loading_in_progress', () => {
        expect(typeof App).toBe("function");
    });

    // WHEN: From the no-document StartScreen, opening a file succeeds and installs the editor session with its diagram, stylesheet, save controller, and file synchronization.
    // THEN: On successful manual open, it installs the diagram session, save controller, and file synchronization.
    test('manual_open_success', () => {
        expect(typeof App).toBe("function");
    });

    // WHEN: A manually requested adapter load fails; the failure is surfaced through the StartScreen error state rather than logged only to the console.
    // THEN: On manual-open failure, it clears loading and surfaces the adapter error through StartScreen instead of only logging it.
    test('manual_open_failure', () => {
        expect(typeof App).toBe("function");
    });

    // WHEN: A document is loaded, so StartScreen is replaced by IslandFrame with the Canvas in the canvas slot and all six islands rendered in their slots.
    // THEN: After loading a document, it replaces StartScreen with IslandFrame containing the full-bleed Canvas and all six islands.
    test('island_frame_after_load', () => {
        expect(typeof App).toBe("function");
    });

    // WHEN: An island invokes onCommand before Canvas has registered its command context; the invocation is a no-op while the islands remain rendered.
    // THEN: Before Canvas registers its context, an island command is a no-op while all islands remain rendered.
    test('command_context_unset', () => {
        expect(typeof App).toBe("function");
    });

    // WHEN: Canvas has registered its command context; an island command invokes runCommand against that exact Canvas-provided context.
    // THEN: After Canvas registers its context, an island command calls runCommand with that exact Canvas-provided context.
    test('command_context_set', () => {
        expect(typeof App).toBe("function");
    });

    // WHEN: The active tool is select; StateIsland receives an undefined mode.
    // THEN: When the select tool is active, StateIsland receives an undefined mode.
    test('select_tool_active', () => {
        expect(typeof App).toBe("function");
    });

    test('non_select_tool_active', () => {
        fc.assert(
            fc.property(fc.constantFrom("hand", "annotation"), (value) => {
        expect(typeof App).toBe("function"); expect(["hand", "annotation"]).toContain(value);
            })
        );
    });

    test('scene_error_present', () => {
        fc.assert(
            fc.property(fc.record({message: fc.string()}), (value) => {
        expect(typeof App).toBe("function"); expect(value.message).toBeTypeOf("string");
            })
        );
    });

    // WHEN: The current scene error is the error recorded by dismissedError; StateIsland does not receive it after dismissal.
    // THEN: When the current scene error matches dismissedError, StateIsland receives no error.
    test('scene_error_dismissed', () => {
        expect(typeof App).toBe("function");
    });

    // WHEN: scene.error() changes to a different error after a dismissal; dismissedError is reset so the new error is exposed to StateIsland.
    // THEN: When scene.error() changes after dismissal, it resets dismissedError so the new error is exposed to StateIsland.
    test('different_scene_error_after_dismissal', () => {
        expect(typeof App).toBe("function");
    });

    test('file_name_query_present', () => {
        fc.assert(
            fc.property(fc.string({minLength: 1}), (value) => {
        expect(typeof App).toBe("function"); expect(typeof value).toBe("string");
            })
        );
    });

    // WHEN: Neither ?file= nor ?name= supplies a file name, so FileIsland receives the fallback name Untitled.
    // THEN: When neither file nor name supplies a value, FileIsland receives Untitled as fileName.
    test('file_name_query_absent', () => {
        expect(typeof App).toBe("function");
    });

    test('valid_stored_editor_theme', () => {
        fc.assert(
            fc.property(fc.string({minLength: 1}), (value) => {
        expect(typeof App).toBe("function"); expect(typeof value).toBe("string");
            })
        );
    });

    test('unknown_stored_editor_theme', () => {
        fc.assert(
            fc.property(fc.string({minLength: 1}), (value) => {
        expect(typeof App).toBe("function"); expect(typeof value).toBe("string");
            })
        );
    });

    // WHEN: Reading or writing localStorage throws, such as in a private or restricted window; the editor continues using the default or selected theme without storage persistence.
    // THEN: When storage access throws, it continues with the default or selected theme without persistence.
    test('editor_theme_storage_unavailable', () => {
        expect(typeof App).toBe("function");
    });

    // WHEN: A loaded scene has geometry; Inspector is rendered with the existing state, UI, theme, geometry, and focus-registration props.
    // THEN: When scene geometry is available, it renders Inspector with the existing state, UI, theme, geometry, and focus-registration props.
    test('inspector_geometry_available', () => {
        expect(typeof App).toBe("function");
    });

    // WHEN: A loaded scene has no geometry yet; Inspector is not rendered until geometry becomes available.
    // THEN: When scene geometry is unavailable, it does not render Inspector until geometry becomes available.
    test('inspector_geometry_unavailable', () => {
        expect(typeof App).toBe("function");
    });

});

