// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import { create } from '@bufbuild/protobuf';
import * as fc from 'fast-check';

import { diffRefsFrom } from '../src/diff/diff_refs';

describe('testgen_diff__diffRefsFrom', () => {
    test('ref_and_base_ref', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const params = new URLSearchParams([
          ['ref', value],
          ['fetch', 'fallback-target'],
          ['base_ref', value],
          ['base_fetch', 'fallback-base'],
        ]);
        expect(diffRefsFrom(params)).toEqual({ target: value, base: value });
            })
        );
    });

    test('ref_and_base_fetch', () => {
        fc.assert(
            fc.property(fc.tuple(fc.string(), fc.string()), (value) => {
        const params = new URLSearchParams([
          ['ref', value],
          ['fetch', 'fallback-target'],
          ['base_fetch', value],
        ]);
        expect(diffRefsFrom(params)).toEqual({ target: value, base: value });
            })
        );
    });

    test('ref_and_no_base', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const params = new URLSearchParams([
          ['ref', value],
          ['fetch', 'fallback-target'],
        ]);
        expect(diffRefsFrom(params)).toEqual({ target: value, base: '' });
            })
        );
    });

    test('fetch_and_base_ref', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const params = new URLSearchParams([
          ['fetch', value],
          ['base_ref', value],
          ['base_fetch', 'fallback-base'],
        ]);
        expect(diffRefsFrom(params)).toEqual({ target: value, base: value });
            })
        );
    });

    test('fetch_and_base_fetch', () => {
        fc.assert(
            fc.property(fc.tuple(fc.string(), fc.string()), (value) => {
        const params = new URLSearchParams([
          ['fetch', value],
          ['base_fetch', value],
        ]);
        expect(diffRefsFrom(params)).toEqual({ target: value, base: value });
            })
        );
    });

    test('fetch_and_no_base', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const params = new URLSearchParams([
          ['fetch', value],
        ]);
        expect(diffRefsFrom(params)).toEqual({ target: value, base: '' });
            })
        );
    });

    test('no_target_and_base_ref', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const params = new URLSearchParams([
          ['base_ref', value],
          ['base_fetch', 'fallback-base'],
        ]);
        expect(diffRefsFrom(params)).toEqual({ target: '', base: value });
            })
        );
    });

    test('no_target_and_base_fetch', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const params = new URLSearchParams([
          ['base_fetch', value],
        ]);
        expect(diffRefsFrom(params)).toEqual({ target: '', base: value });
            })
        );
    });

    test('no_target_and_no_base', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const params = new URLSearchParams([['unrelated', value]]);
        expect(diffRefsFrom(params)).toEqual({ target: '', base: '' });
            })
        );
    });

});

