// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { EDITOR_THEMES } from '../src/shell/editor_theme';
import { FileIsland, FileIslandProps } from '../src/shell/file_island';

describe('testgen_shell__FileIsland', () => {
    function findElement(value: any, tag: string, styleToken?: string): any {
      if (value === null || value === undefined) return undefined;
      if (Array.isArray(value)) {
        for (const item of value) { const found = findElement(item, tag, styleToken); if (found) return found; }
        return undefined;
      }
      if (typeof value !== 'object') return undefined;
      if (value.type === tag && (!styleToken || JSON.stringify(value).includes(styleToken))) return value;
      const props = value.props;
      if (props) {
        const found = findElement(props.children, tag, styleToken);
        if (found) return found;
      }
      return findElement(value.children, tag, styleToken);
    }

    function renderFileIsland(props: any): any {
      return FileIsland(props);
    }

    function textContent(value: any): string {
      if (value === null || value === undefined || typeof value === 'boolean') return '';
      if (typeof value === 'string' || typeof value === 'number') return String(value);
      if (Array.isArray(value)) return value.map(textContent).join('');
      if (typeof value === 'object') return textContent(value.children ?? value.props?.children);
      return '';
    }

    test('clean_idle_no_save', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const tree = renderFileIsland({ fileName: value, dirty: false, canSave: false, status: 'idle', editorTheme: EDITOR_THEMES[0].id, onSave: () => {}, onEditorTheme: () => {} });
        const text = textContent(tree);
        expect(text).toContain(value);
        expect(text).not.toContain('Saved');
        expect(text).not.toContain('Unsaved');
        expect(text).not.toContain('Saving...');
        expect(text).not.toContain('Save failed');
        expect(findElement(tree, 'button')).toBeUndefined();
        expect(findElement(tree, 'span', '--ag-teal')).toBeUndefined();
            })
        );
    });

    test('dirty_unsaved_save_enabled', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const tree = renderFileIsland({ fileName: value, dirty: true, canSave: true, status: 'unsaved', editorTheme: EDITOR_THEMES[0].id, onSave: () => {}, onEditorTheme: () => {} });
        expect(textContent(tree)).toContain(value);
        expect(textContent(tree)).toContain('Unsaved');
        expect(findElement(tree, 'button')).toBeDefined();
        expect(findElement(tree, 'span', '--ag-teal')).toBeDefined();
            })
        );
    });

    test('dirty_saving_status_wins', () => {
        fc.assert(
            fc.property(fc.record({ fileName: fc.string(), canSave: fc.boolean() }), (value) => {
        const tree = renderFileIsland({ fileName: value.fileName, dirty: true, canSave: value.canSave, status: 'saving', editorTheme: EDITOR_THEMES[0].id, onSave: () => {}, onEditorTheme: () => {} });
        expect(textContent(tree)).toContain('Saving...');
        expect(findElement(tree, 'span', '--ag-teal')).toBeDefined();
        if (value.canSave) expect(findElement(tree, 'button')).toBeDefined();
        else expect(findElement(tree, 'button')).toBeUndefined();
            })
        );
    });

    test('dirty_saved_status_wins', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const tree = renderFileIsland({ fileName: value, dirty: true, canSave: false, status: 'saved', editorTheme: EDITOR_THEMES[0].id, onSave: () => {}, onEditorTheme: () => {} });
        expect(textContent(tree)).toContain('Saved');
        expect(findElement(tree, 'span', '--ag-teal')).toBeDefined();
            })
        );
    });

    test('clean_saved', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const tree = renderFileIsland({ fileName: value, dirty: false, canSave: false, status: 'saved', editorTheme: EDITOR_THEMES[0].id, onSave: () => {}, onEditorTheme: () => {} });
        expect(textContent(tree)).toContain('Saved');
        expect(findElement(tree, 'span', '--ag-teal')).toBeUndefined();
            })
        );
    });

    test('save_error_replaces_dot', () => {
        fc.assert(
            fc.property(fc.record({ fileName: fc.string(), dirty: fc.boolean() }), (value) => {
        const tree = renderFileIsland({ fileName: value.fileName, dirty: value.dirty, canSave: false, status: 'error', errorMessage: 'write failed', editorTheme: EDITOR_THEMES[0].id, onSave: () => {}, onEditorTheme: () => {} });
        expect(textContent(tree)).toContain('Save failed');
        expect(findElement(tree, 'span', '--ag-danger')).toBeDefined();
        expect(findElement(tree, 'span', '--ag-teal')).toBeUndefined();
            })
        );
    });

    // WHEN: Status idle produces no status label.
    // THEN: It renders no status label for idle.
    test('idle_status_empty', () => {
        const tree = renderFileIsland({ fileName: 'diagram.graph', dirty: false, canSave: false, status: 'idle', editorTheme: EDITOR_THEMES[0].id, onSave: () => {}, onEditorTheme: () => {} });
        const text = textContent(tree);
        expect(text).toContain('diagram.graph');
        expect(text).not.toContain('Saved');
        expect(text).not.toContain('Unsaved');
        expect(text).not.toContain('Saving...');
        expect(text).not.toContain('Save failed');
    });

    test('save_button_hidden', () => {
        fc.assert(
            fc.property(fc.record({ fileName: fc.string(), dirty: fc.boolean(), status: fc.constantFrom('idle', 'saving', 'saved', 'unsaved', 'error') }), (value) => {
        const tree = renderFileIsland({ fileName: value.fileName, dirty: value.dirty, canSave: false, status: value.status, editorTheme: EDITOR_THEMES[0].id, onSave: () => {}, onEditorTheme: () => {} });
        expect(findElement(tree, 'button')).toBeUndefined();
            })
        );
    });

    test('save_button_visible', () => {
        fc.assert(
            fc.property(fc.record({ fileName: fc.string(), dirty: fc.boolean(), status: fc.constantFrom('idle', 'saving', 'saved', 'unsaved', 'error') }), (value) => {
        const tree = renderFileIsland({ fileName: value.fileName, dirty: value.dirty, canSave: true, status: value.status, editorTheme: EDITOR_THEMES[0].id, onSave: () => {}, onEditorTheme: () => {} });
        expect(findElement(tree, 'button')).toBeDefined();
            })
        );
    });

    // WHEN: An empty filename is accepted and displayed as the file-name value without changing dot, status, Save, or picker behavior.
    // THEN: It displays an empty filename value without changing the dot, status, Save, or picker behavior.
    test('empty_file_name', () => {
        const tree = renderFileIsland({ fileName: '', dirty: false, canSave: false, status: 'idle', editorTheme: EDITOR_THEMES[0].id, onSave: () => {}, onEditorTheme: () => {} });
        expect(textContent(tree)).toBe('');
        expect(findElement(tree, 'button')).toBeUndefined();
    });

    test('non_empty_file_name', () => {
        fc.assert(
            fc.property(fc.string({ minLength: 1 }), (value) => {
        const tree = renderFileIsland({ fileName: value, dirty: false, canSave: false, status: 'idle', editorTheme: EDITOR_THEMES[0].id, onSave: () => {}, onEditorTheme: () => {} });
        expect(textContent(tree)).toContain(value);
            })
        );
    });

    test('palette_options_by_label', () => {
        fc.assert(
            fc.property(fc.constantFrom(...EDITOR_THEMES), (value) => {
        const tree = renderFileIsland({ fileName: 'diagram.graph', dirty: false, canSave: false, status: 'idle', editorTheme: value.id, onSave: () => {}, onEditorTheme: () => {} });
        const select = findElement(tree, 'select');
        expect(select).toBeDefined();
        for (const theme of EDITOR_THEMES) expect(textContent(select)).toContain(theme.label);
        expect(select.props.value).toBe(value.id);
            })
        );
    });

    test('palette_change_keeps_clean', () => {
        fc.assert(
            fc.property(fc.tuple(fc.constantFrom(...EDITOR_THEMES), fc.constantFrom(...EDITOR_THEMES)).filter(([first, second]) => first.id !== second.id), (value) => {
        const calls: string[] = [];
        const tree = renderFileIsland({ fileName: 'diagram.graph', dirty: false, canSave: false, status: 'idle', editorTheme: value[0].id, onSave: () => {}, onEditorTheme: (theme) => calls.push(theme) });
        const select = findElement(tree, 'select');
        expect(select).toBeDefined();
        select.props.onChange({ currentTarget: { value: value[1].id } });
        expect(calls).toEqual([value[1].id]);
        expect(findElement(tree, 'span', '--ag-teal')).toBeUndefined();
            })
        );
    });

    // WHEN: Selecting the already active palette leaves the document clean and does not introduce a dirty state.
    // THEN: It leaves the document clean when the already active palette is selected.
    test('palette_same_selection', () => {
        const calls: string[] = [];
        const tree = renderFileIsland({ fileName: 'diagram.graph', dirty: false, canSave: false, status: 'idle', editorTheme: EDITOR_THEMES[0].id, onSave: () => {}, onEditorTheme: (theme) => calls.push(theme) });
        const select = findElement(tree, 'select');
        expect(select).toBeDefined();
        select.props.onChange({ currentTarget: { value: EDITOR_THEMES[0].id } });
        expect(calls).toEqual([EDITOR_THEMES[0].id]);
        expect(findElement(tree, 'span', '--ag-teal')).toBeUndefined();
    });

    // WHEN: With canSave true before a file handle exists, activating Save is the path that permits the first write and its transient file-picker activation; autosave must not initiate that picker by itself.
    // THEN: It uses a real Save-button click to permit the first write and its transient file-picker activation rather than initiating it through autosave.
    test('first_save_requires_click', () => {
        let saves = 0;
        const tree = renderFileIsland({ fileName: 'diagram.graph', dirty: false, canSave: true, status: undefined, editorTheme: EDITOR_THEMES[0].id, onSave: () => { saves += 1; }, onEditorTheme: () => {} });
        const button = findElement(tree, 'button');
        expect(button).toBeDefined();
        expect(saves).toBe(0);
        button.props.onClick();
        expect(saves).toBe(1);
    });

});

