// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { handleKeyDown } from '../src/gestures/keyboard_handler';

describe('testgen_gestures__handleKeyDown', () => {
    const editableTarget = (kind: string): EventTarget => { if (kind === "input" || kind === "textarea") { return { tagName: kind } as unknown as EventTarget; } return { tagName: "div", isContentEditable: false, contentEditable: "inherit", getAttribute: (name: string): string | null => name === "contenteditable" ? "true" : null } as unknown as EventTarget; };

    const makeContext = (gesture: unknown): { context: Parameters<typeof handleKeyDown>[1]; setValues: unknown[]; modalReads: number } => { const setValues: unknown[] = []; let modalReads = 0; const context = { state: {}, ui: { modalGesture: (): unknown => { modalReads += 1; return gesture; }, setModalGesture: (next: unknown): void => { setValues.push(next); } }, geometry: undefined, rect: {}, save: (): void => {}, beginTextEdit: (): void => {} } as unknown as Parameters<typeof handleKeyDown>[1]; return { context, setValues, modalReads }; };

    const makeEvent = (key: string, target: EventTarget | null): KeyboardEvent => ({ key, target, metaKey: false, ctrlKey: false, shiftKey: false } as KeyboardEvent);

    const nonEditingTarget = (): EventTarget => ({ tagName: "div", isContentEditable: false, contentEditable: "inherit", getAttribute: (): string | null => null } as unknown as EventTarget);

    test('ignored_editable_target', () => {
        fc.assert(
            fc.property(fc.constantFrom("input", "textarea", "contenteditable"), (value) => {
        const contextFixture = makeContext(undefined);
        const target = editableTarget(value);
        const event = makeEvent("q", target);
        expect(handleKeyDown(event, contextFixture.context)).toBe(false);
        expect(contextFixture.modalReads).toBe(0);
        expect(contextFixture.setValues).toHaveLength(0);
            })
        );
    });

    test('no_modal_unmatched_chord', () => {
        fc.assert(
            fc.property(fc.constantFrom("UnmappedKeyA", "UnmappedKeyB", "UnmappedKeyC"), (value) => {
        const contextFixture = makeContext(undefined);
        const event = makeEvent(value, nonEditingTarget());
        expect(handleKeyDown(event, contextFixture.context)).toBe(false);
        expect(contextFixture.modalReads).toBe(0);
            })
        );
    });

    test('no_modal_matched_chord', () => {
        fc.assert(
            fc.property(fc.constantFrom("ArrowUp", "ArrowDown", "ArrowLeft", "ArrowRight"), (value) => {
        const contextFixture = makeContext(undefined);
        const event = makeEvent(value, nonEditingTarget());
        expect(handleKeyDown(event, contextFixture.context)).toBe(true);
        expect(contextFixture.modalReads).toBe(0);
            })
        );
    });

    test('modal_continue', () => {
        fc.assert(
            fc.property(fc.constantFrom("ArrowUp", "ArrowDown", "ArrowLeft", "ArrowRight", "1", "7", "Backspace"), (value) => {
        const gesture = { kind: "move", refs: [], digits: "", direction: "up" };
        const contextFixture = makeContext(gesture);
        const event = makeEvent(value, nonEditingTarget());
        expect(handleKeyDown(event, contextFixture.context)).toBe(true);
        expect(contextFixture.setValues).toHaveLength(1);
        expect(contextFixture.setValues[0]).not.toBeUndefined();
            })
        );
    });

    test('modal_commit', () => {
        fc.assert(
            fc.property(fc.constant("Enter"), (value) => {
        const gesture = { kind: "move", refs: [], digits: "", direction: "up" };
        const contextFixture = makeContext(gesture);
        const event = makeEvent(value, nonEditingTarget());
        expect(handleKeyDown(event, contextFixture.context)).toBe(true);
        expect(contextFixture.setValues).toHaveLength(1);
        expect(contextFixture.setValues[0]).toBeUndefined();
            })
        );
    });

    test('modal_cancel', () => {
        fc.assert(
            fc.property(fc.constant("Escape"), (value) => {
        const gesture = { kind: "move", refs: [], digits: "", direction: "up" };
        const contextFixture = makeContext(gesture);
        const event = makeEvent(value, nonEditingTarget());
        expect(handleKeyDown(event, contextFixture.context)).toBe(true);
        expect(contextFixture.setValues).toHaveLength(1);
        expect(contextFixture.setValues[0]).toBeUndefined();
            })
        );
    });

    test('modal_ignore_unmatched_chord', () => {
        fc.assert(
            fc.property(fc.constantFrom("UnmappedKeyA", "UnmappedKeyB", "UnmappedKeyC"), (value) => {
        const gesture = { kind: "move", refs: [], digits: "", direction: "up" };
        const contextFixture = makeContext(gesture);
        const event = makeEvent(value, nonEditingTarget());
        expect(handleKeyDown(event, contextFixture.context)).toBe(false);
        expect(contextFixture.setValues).toHaveLength(0);
            })
        );
    });

    test('modal_arrow_is_consumed_by_the_gesture', () => {
        fc.assert(
            fc.property(fc.constantFrom("ArrowUp", "ArrowDown", "ArrowLeft", "ArrowRight"), (value) => {
        const gesture = { kind: "grab" as const, refs: [], digits: "", direction: "up" as const };
        const contextFixture = makeContext(gesture);
        const event = makeEvent(value, nonEditingTarget());
        // An arrow is consumed by the open gesture, so it re-aims it and never
        // reaches resolveChord -- which is what keeps it from nudging instead.
        expect(handleKeyDown(event, contextFixture.context)).toBe(true);
        expect(contextFixture.setValues).toHaveLength(1);
            })
        );
    });

});

