// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { COMMANDS, Command, CommandContext, FIT_PADDING, ZOOM_STEP, runAddAnnotation, runDelete, runDuplicate, runEditText, runHide, runNudge, runPinAll, runResetSize, runRing, runUnpinAll } from '../src/gestures/commands';
import { MAX_ZOOM, MIN_ZOOM } from '../src/gestures/wheel_handler';
import { ElementBounds, SceneGeometry } from '../src/scene/scene';
import { EditorState } from '../src/state/editor_state';
import { CommandId } from '../src/ui_state/keymap';
import { clearSelection } from '../src/ui_state/selection_ops';
import { UiState } from '../src/ui_state/ui_state';
import { fitBoundsToRect, zoomAboutPoint } from '../src/ui_state/viewport_math';

describe('testgen_gestures__COMMANDS', () => {
    function commandFor(id) {
      const command = COMMANDS.find((entry) => entry.id === id);
      expect(command).toBeDefined();
      return command;
    }

    function makeContext(viewport, rect, geometry) {
      const context = {
        state: { undo() {}, redo() {}, stylesheet() { return {}; }, applyStyleEdit() {} },
        ui: { selection() { return []; }, setSelection() {}, viewport() { return context.viewport; }, setViewport(next) { context.viewport = next; context.setViewportCalls += 1; }, setTool(tool) { context.tool = tool; } },
        rect,
        save() {},
        beginTextEdit() {},
        geometry,
        viewport,
        setViewportCalls: 0,
        tool: undefined,
      };
      return context;
    }

    function runZoom(id, value, rect) {
      const viewport = { zoom: value.zoom, panX: 37, panY: -19 };
      const context = makeContext(viewport, rect);
      commandFor(id).run(context);
      return context.viewport;
    }

    test('existing_command_registry_preserved', () => {
        fc.assert(
            fc.property(fc.constantFrom({ id: 'undo', label: 'Undo' }, { id: 'redo', label: 'Redo' }, { id: 'delete', label: 'Delete' }, { id: 'hide', label: 'Hide' }, { id: 'tool-select', label: 'Select tool' }, { id: 'tool-annotation', label: 'Annotation tool' }, { id: 'add-annotation', label: 'Add annotation' }, { id: 'edit-text', label: 'Edit text' }, { id: 'duplicate', label: 'Duplicate' }, { id: 'escape', label: 'Escape' }, { id: 'select-all', label: 'Select all' }, { id: 'focus-inspector', label: 'Focus inspector' }, { id: 'nudge-up', label: 'Nudge up' }, { id: 'nudge-down', label: 'Nudge down' }, { id: 'nudge-left', label: 'Nudge left' }, { id: 'nudge-right', label: 'Nudge right' }, { id: 'ring-next', label: 'Next element' }, { id: 'ring-prev', label: 'Previous element' }, { id: 'pin-all', label: 'Pin all' }, { id: 'unpin-all', label: 'Unpin all' }, { id: 'auto-layout', label: 'Auto layout' }, { id: 'reset-size', label: 'Reset size' }, { id: 'save', label: 'Save' }), (value) => {
        const command = COMMANDS.find((entry) => entry.id === value.id);
        expect(command).toBeDefined();
        expect(command?.label).toBe(value.label);
            })
        );
    });

    // WHEN: Running tool-hand sets the active tool to hand, matching the neighboring tool commands.
    // THEN: Running tool-hand sets the active tool to hand.
    test('tool_hand_sets_hand_tool', () => {
        const context = makeContext({ zoom: 1, panX: 0, panY: 0 }, { left: 10, top: 20, width: 300, height: 200 });
        commandFor('tool-hand').run(context);
        expect(context.tool).toBe('hand');
    });

    test('zoom_in_positive_viewport', () => {
        fc.assert(
            fc.property(fc.record({ width: fc.integer({ min: 1, max: 2000 }), height: fc.integer({ min: 1, max: 2000 }), zoom: fc.double({ min: 0.2, max: 6, noNaN: true }) }), (value) => {
        const result = runZoom('zoom-in', value, { left: 10, top: 20, width: value.width, height: value.height });
        const x = value.width / 2;
        const y = value.height / 2;
        expect(result.zoom).toBeCloseTo(value.zoom * 1.2, 12);
        expect(result.panX).toBeCloseTo(x - (x - 37) * (result.zoom / value.zoom), 12);
        expect(result.panY).toBeCloseTo(y - (y + 19) * (result.zoom / value.zoom), 12);
            })
        );
    });

    test('zoom_in_lower_clamp', () => {
        fc.assert(
            fc.property(fc.record({ rect: fc.record({ left: fc.integer({ min: -1000, max: 1000 }), top: fc.integer({ min: -1000, max: 1000 }), width: fc.integer({ min: 1, max: 2000 }), height: fc.integer({ min: 1, max: 2000 }) }), zoom: fc.constantFrom(0.01, 0.03, 0.08) }), (value) => {
        const result = runZoom('zoom-in', { zoom: value.zoom, panX: 37, panY: -19 }, value.rect);
        const x = value.rect.width / 2;
        const y = value.rect.height / 2;
        expect(result.zoom).toBe(0.1);
        expect(result.panX).toBeCloseTo(x - (x - 37) * (0.1 / value.zoom), 12);
        expect(result.panY).toBeCloseTo(y - (y + 19) * (0.1 / value.zoom), 12);
            })
        );
    });

    test('zoom_in_upper_clamp', () => {
        fc.assert(
            fc.property(fc.record({ rect: fc.record({ left: fc.integer({ min: -1000, max: 1000 }), top: fc.integer({ min: -1000, max: 1000 }), width: fc.integer({ min: 1, max: 2000 }), height: fc.integer({ min: 1, max: 2000 }) }), zoom: fc.constantFrom(7, 7.5, 8, 10) }), (value) => {
        const result = runZoom('zoom-in', { zoom: value.zoom, panX: 37, panY: -19 }, value.rect);
        const x = value.rect.width / 2;
        const y = value.rect.height / 2;
        expect(result.zoom).toBe(8);
        expect(result.panX).toBeCloseTo(x - (x - 37) * (8 / value.zoom), 12);
        expect(result.panY).toBeCloseTo(y - (y + 19) * (8 / value.zoom), 12);
            })
        );
    });

    test('zoom_out_positive_viewport', () => {
        fc.assert(
            fc.property(fc.record({ width: fc.integer({ min: 1, max: 2000 }), height: fc.integer({ min: 1, max: 2000 }), zoom: fc.double({ min: 1, max: 7.5, noNaN: true }) }), (value) => {
        const result = runZoom('zoom-out', value, { left: 10, top: 20, width: value.width, height: value.height });
        const x = value.width / 2;
        const y = value.height / 2;
        const target = value.zoom / 1.2;
        expect(result.zoom).toBeCloseTo(target, 12);
        expect(result.panX).toBeCloseTo(x - (x - 37) * (target / value.zoom), 12);
        expect(result.panY).toBeCloseTo(y - (y + 19) * (target / value.zoom), 12);
            })
        );
    });

    test('zoom_out_lower_clamp', () => {
        fc.assert(
            fc.property(fc.record({ rect: fc.record({ left: fc.integer({ min: -1000, max: 1000 }), top: fc.integer({ min: -1000, max: 1000 }), width: fc.integer({ min: 1, max: 2000 }), height: fc.integer({ min: 1, max: 2000 }) }), zoom: fc.constantFrom(0.1, 0.12) }), (value) => {
        const result = runZoom('zoom-out', { zoom: value.zoom, panX: 37, panY: -19 }, value.rect);
        const x = value.rect.width / 2;
        const y = value.rect.height / 2;
        expect(result.zoom).toBe(0.1);
        expect(result.panX).toBeCloseTo(x - (x - 37) * (0.1 / value.zoom), 12);
        expect(result.panY).toBeCloseTo(y - (y + 19) * (0.1 / value.zoom), 12);
            })
        );
    });

    test('zoom_reset_centred_to_one', () => {
        fc.assert(
            fc.property(fc.record({ rect: fc.record({ left: fc.integer({ min: -1000, max: 1000 }), top: fc.integer({ min: -1000, max: 1000 }), width: fc.integer({ min: 1, max: 2000 }), height: fc.integer({ min: 1, max: 2000 }) }), zoom: fc.constantFrom(0.25, 0.5, 2, 4) }), (value) => {
        const result = runZoom('zoom-reset', { zoom: value.zoom, panX: 37, panY: -19 }, value.rect);
        const x = value.rect.width / 2;
        const y = value.rect.height / 2;
        expect(result.zoom).toBeCloseTo(1, 12);
        expect(result.panX).toBeCloseTo(x - (x - 37) / value.zoom, 12);
        expect(result.panY).toBeCloseTo(y - (y + 19) / value.zoom, 12);
            })
        );
    });

    test('zoom_fit_valid_geometry', () => {
        fc.assert(
            fc.property(fc.record({ rect: fc.record({ left: fc.integer({ min: -1000, max: 1000 }), top: fc.integer({ min: -1000, max: 1000 }), width: fc.integer({ min: 100, max: 2000 }), height: fc.integer({ min: 100, max: 2000 }) }) }), (value) => {
        const context = makeContext({ zoom: 2, panX: 13, panY: -7 }, value.rect, { index: [{ ref: { kind: 'node', id: 'n' }, bounds: { minX: 0, minY: 0, maxX: 1, maxY: 1 } }], contentBounds: { minX: -20, minY: 10, maxX: 180, maxY: 110 } });
        commandFor('zoom-fit').run(context);
        expect(context.viewport.zoom).toBeCloseTo(Math.min((value.rect.width - 80) / 200, (value.rect.height - 80) / 100), 12);
            })
        );
    });

    test('zoom_fit_content_bounds_source', () => {
        fc.assert(
            fc.property(fc.record({ rect: fc.record({ left: fc.integer({ min: -1000, max: 1000 }), top: fc.integer({ min: -1000, max: 1000 }), width: fc.integer({ min: 100, max: 2000 }), height: fc.integer({ min: 100, max: 2000 }) }) }), (value) => {
        const contentBounds = { minX: 100, minY: 200, maxX: 300, maxY: 400 };
        const context = makeContext({ zoom: 1, panX: 0, panY: 0 }, value.rect, { index: [{ ref: { kind: 'node', id: 'n' }, bounds: { minX: 0, minY: 0, maxX: 1, maxY: 1 } }], contentBounds });
        commandFor('zoom-fit').run(context);
        expect(context.viewport.zoom).toBeCloseTo(Math.min((value.rect.width - 80) / 200, (value.rect.height - 80) / 200), 12);
        expect(context.viewport.panX).toBeCloseTo(value.rect.width / 2 - 200 * context.viewport.zoom, 12);
        expect(context.viewport.panY).toBeCloseTo(value.rect.height / 2 - 300 * context.viewport.zoom, 12);
            })
        );
    });

    test('zero_width_or_height_viewport_no_op', () => {
        fc.assert(
            fc.property(fc.oneof(fc.record({ left: fc.integer({ min: -1000, max: 1000 }), top: fc.integer({ min: -1000, max: 1000 }), width: fc.constant(0), height: fc.integer({ min: 1, max: 2000 }) }), fc.record({ left: fc.integer({ min: -1000, max: 1000 }), top: fc.integer({ min: -1000, max: 1000 }), width: fc.integer({ min: 1, max: 2000 }), height: fc.constant(0) })), (value) => {
        for (const id of ['zoom-in', 'zoom-out', 'zoom-reset', 'zoom-fit']) {
          const context = makeContext({ zoom: 2, panX: 13, panY: -7 }, value, { index: [{ ref: { kind: 'node', id: 'n' } }], contentBounds: { minX: 0, minY: 0, maxX: 100, maxY: 100 } });
          commandFor(id).run(context);
          expect(context.viewport).toEqual({ zoom: 2, panX: 13, panY: -7 });
          expect(context.setViewportCalls).toBe(0);
        }
            })
        );
    });

    // WHEN: Running zoom-fit does nothing when geometry is undefined, provided the rectangle has positive width and height.
    // THEN: zoom-fit does nothing when geometry is undefined and the rectangle has positive dimensions.
    test('zoom_fit_undefined_geometry_no_op', () => {
        const context = makeContext({ zoom: 2, panX: 13, panY: -7 }, { left: 10, top: 20, width: 300, height: 200 });
        commandFor('zoom-fit').run(context);
        expect(context.viewport).toEqual({ zoom: 2, panX: 13, panY: -7 });
        expect(context.setViewportCalls).toBe(0);
    });

    // WHEN: Running zoom-fit does nothing when geometry is defined but geometry.index.length is 0, provided the rectangle has positive width and height.
    // THEN: zoom-fit does nothing when defined geometry has an empty index and the rectangle has positive dimensions.
    test('zoom_fit_empty_index_no_op', () => {
        const context = makeContext({ zoom: 2, panX: 13, panY: -7 }, { left: 10, top: 20, width: 300, height: 200 }, { index: [], contentBounds: { minX: 0, minY: 0, maxX: 0, maxY: 0 } });
        commandFor('zoom-fit').run(context);
        expect(context.viewport).toEqual({ zoom: 2, panX: 13, panY: -7 });
        expect(context.setViewportCalls).toBe(0);
    });

});

