// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { PALETTE_EXCLUDED } from '../src/shell/palette_excluded';

describe('testgen_shell__PALETTE_EXCLUDED', () => {
    // WHEN: The command id is 'enter-grab'; it is excluded from the palette.
    // THEN: The function should include 'enter-grab' in the excluded command set.
    test('enter_grab_excluded', () => {
        expect(PALETTE_EXCLUDED.has('enter-grab')).toBe(true);
    });

    // WHEN: The command id is 'enter-resize'; it is excluded from the palette.
    // THEN: The function should include 'enter-resize' in the excluded command set.
    test('enter_resize_excluded', () => {
        expect(PALETTE_EXCLUDED.has('enter-resize')).toBe(true);
    });

    test('existing_members_remain_excluded', () => {
        fc.assert(
            fc.property(fc.constantFrom('escape', 'nudge-up', 'nudge-down', 'nudge-left', 'nudge-right', 'ring-next', 'ring-prev', 'open-palette', 'open-help'), (value) => {
        expect(PALETTE_EXCLUDED.has(value)).toBe(true);
            })
        );
    });

});

