// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import { create } from '@bufbuild/protobuf';
import * as fc from 'fast-check';

import { buildRemoteUrl } from '../src/adapters/url_param_adapter';

describe('testgen_adapters__buildRemoteUrl', () => {
    test('fetch_precedence', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const params: URLSearchParams = new URLSearchParams();
        params.set('fetch', value);
        params.set('gh', 'ignored-owner/repo');
        params.set('path', 'ignored/path');
        params.set('ref', 'ignored-ref');
        params.set('gist', 'ignored-gist');
        expect(buildRemoteUrl(params)).toBe(value);
            })
        );
    });

    test('github_explicit_fields', () => {
        fc.assert(
            fc.property(fc.record({ gh: fc.string(), path: fc.string(), ref: fc.string() }), (value) => {
        const params: URLSearchParams = new URLSearchParams();
        params.set('gh', value.gh);
        params.set('path', value.path);
        params.set('ref', value.ref);
        expect(buildRemoteUrl(params)).toBe(`https://raw.githubusercontent.com/${value.gh}/${value.ref}/${value.path}`);
            })
        );
    });

    test('github_missing_ref', () => {
        fc.assert(
            fc.property(fc.record({ gh: fc.string(), path: fc.string() }), (value) => {
        const params: URLSearchParams = new URLSearchParams();
        params.set('gh', value.gh);
        params.set('path', value.path);
        expect(buildRemoteUrl(params)).toBe(`https://raw.githubusercontent.com/${value.gh}/main/${value.path}`);
            })
        );
    });

    test('github_missing_path', () => {
        fc.assert(
            fc.property(fc.record({ gh: fc.string(), ref: fc.string() }), (value) => {
        const params: URLSearchParams = new URLSearchParams();
        params.set('gh', value.gh);
        params.set('ref', value.ref);
        expect(buildRemoteUrl(params)).toBe(`https://raw.githubusercontent.com/${value.gh}/${value.ref}/`);
            })
        );
    });

    test('github_precedence_over_gist', () => {
        fc.assert(
            fc.property(fc.record({ gh: fc.string(), path: fc.string(), ref: fc.string(), gist: fc.string() }), (value) => {
        const params: URLSearchParams = new URLSearchParams();
        params.set('gh', value.gh);
        params.set('path', value.path);
        params.set('ref', value.ref);
        params.set('gist', value.gist);
        expect(buildRemoteUrl(params)).toBe(`https://raw.githubusercontent.com/${value.gh}/${value.ref}/${value.path}`);
            })
        );
    });

    test('gist_fallback', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const params: URLSearchParams = new URLSearchParams();
        params.set('gist', value);
        expect(buildRemoteUrl(params)).toBe(value);
            })
        );
    });

    test.skip('no_matching_form', () => {
        // test generation failed: generated body does not reference the bound value `value`
    });

    test('default_empty_prefix', () => {
        fc.assert(
            fc.property(fc.boolean(), (value) => {
        const params: URLSearchParams = new URLSearchParams();
        params.set('gh', 'owner/repo');
        params.set('path', 'src/file.ts');
        params.set('ref', 'feature');
        const result: string | null = value ? buildRemoteUrl(params, '') : buildRemoteUrl(params);
        expect(result).toBe('https://raw.githubusercontent.com/owner/repo/feature/src/file.ts');
            })
        );
    });

    test('custom_prefix', () => {
        fc.assert(
            fc.property(fc.string().filter((prefix: string): boolean => prefix.length > 0), (value) => {
        const params: URLSearchParams = new URLSearchParams();
        params.set('fetch', 'unprefixed-fetch');
        params.set('gh', 'unprefixed-owner/repo');
        params.set('gist', 'unprefixed-gist');
        params.set(`${value}fetch`, 'prefixed-fetch');
        params.set(`${value}gh`, 'prefixed-owner/repo');
        params.set(`${value}path`, 'prefixed/path');
        params.set(`${value}ref`, 'prefixed-ref');
        params.set(`${value}gist`, 'prefixed-gist');
        expect(buildRemoteUrl(params, value)).toBe('prefixed-fetch');
            })
        );
    });

});

