// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { commandPaletteItems } from '../src/shell/palette_items';

describe('testgen_shell__commandPaletteItems', () => {
    test('eligible_command', () => {
        fc.assert(
            fc.property(fc.record({ label: fc.string(), appliesTo: fc.constantFrom('global', ['node']) , hasBinding: fc.boolean() }), (value) => {
        const command = {
          id: 'copy',
          label: value.label,
          appliesTo: value.appliesTo,
          run: () => undefined,
        };
        const keymap = value.hasBinding
          ? [{ command: 'copy', chord: { key: 'x', meta: false, shift: false } }]
          : [];
        const items = commandPaletteItems([command], keymap);
        expect(items).toEqual([
          {
            key: 'command:copy',
            label: value.label,
            detail: value.hasBinding ? 'X' : '',
            action: { kind: 'command', command: 'copy' },
          },
        ]);
            })
        );
    });

    test('inapplicable_command', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const command = {
          id: 'copy',
          label: value,
          run: () => undefined,
        };
        expect(commandPaletteItems([command], [])).toEqual([]);
            })
        );
    });

    // WHEN: A command has id 'open-palette'; it is skipped even when appliesTo is present.
    // THEN: Skips the command even when appliesTo is present.
    test('palette_self_reference', () => {
        const command = {
          id: 'open-palette',
          label: 'Open palette',
          appliesTo: 'global',
          run: () => undefined,
        };
        expect(commandPaletteItems([command], [])).toEqual([]);
    });

    // WHEN: A command has id 'open-help'; it is included when it has appliesTo present, rather than being excluded merely because it is a global command.
    // THEN: Includes open-help when appliesTo is present, despite it being a global command.
    test('help_command_listed', () => {
        const command = {
          id: 'open-help',
          label: 'Keyboard Shortcuts',
          appliesTo: 'global',
          run: () => undefined,
        };
        expect(commandPaletteItems([command], [])).toEqual([
          {
            key: 'command:open-help',
            label: 'Keyboard Shortcuts',
            detail: '',
            action: { kind: 'command', command: 'open-help' },
          },
        ]);
    });

    test('matching_keymap_entry', () => {
        fc.assert(
            fc.property(fc.array(fc.record({ key: fc.constant('x'), meta: fc.constant(false), shift: fc.constant(false) }), { minLength: 1 }), (value) => {
        const command = {
          id: 'copy',
          label: 'Copy',
          appliesTo: 'global',
          run: () => undefined,
        };
        const keymap = value.map((chord) => ({ command: 'copy', chord }));
        const items = commandPaletteItems([command], keymap);
        expect(items[0]?.detail).toBe('X');
            })
        );
    });

    // WHEN: An included command has no keymap entry whose command equals its id; its detail is the empty string.
    // THEN: Sets the included command's detail to the empty string.
    test('missing_keymap_entry', () => {
        const command = {
          id: 'copy',
          label: 'Copy',
          appliesTo: 'global',
          run: () => undefined,
        };
        const items = commandPaletteItems([command], []);
        expect(items).toEqual([
          {
            key: 'command:copy',
            label: 'Copy',
            detail: '',
            action: { kind: 'command', command: 'copy' },
          },
        ]);
    });

    test('command_order_preserved', () => {
        fc.assert(
            fc.property(fc.array(fc.boolean()), (value) => {
        const commands = value.map((included, index) => ({
          id: 'copy',
          label: String(index),
          ...(included ? { appliesTo: 'global' } : {}),
          run: () => undefined,
        }));
        const items = commandPaletteItems(commands, []);
        expect(items.map((item) => item.label)).toEqual(
          value
            .map((included, index) => (included ? String(index) : undefined))
            .filter((label) => label !== undefined),
        );
            })
        );
    });

    // WHEN: The commands input is empty; the function returns an empty array.
    // THEN: Returns an empty array.
    test('empty_command_list', () => {
        expect(commandPaletteItems([], [])).toEqual([]);
    });

});

