// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import { create } from '@bufbuild/protobuf';
import * as fc from 'fast-check';

import { createDiffState } from '../src/diff/diff_state';
import { Diagram } from '../../proto/src/gen/content_pb';
import { Delta, DiagramSchema } from '../../proto/src/gen/content_pb';

describe('testgen_diff__createDiffState', () => {
    const makeDiagram = (id: string): Diagram => create(DiagramSchema, {id});

    test('no_base_attached', () => {
        fc.assert(
            fc.property(fc.oneof(fc.constant(undefined), fc.string().map((id: string): Diagram => makeDiagram(id))), (value) => {
        const state = createDiffState(() => value, "target");
        expect(state.delta()).toBeUndefined();
            })
        );
    });

    // WHEN: A base Diagram is attached, but target() is still undefined while the document is loading; delta() is undefined.
    // THEN: It keeps delta() undefined while an attached base exists but target() is still undefined.
    test('base_attached_target_loading', () => {
        const state = createDiffState(() => undefined, "target");
        state.setBase(makeDiagram("base"), "base-ref");
        expect(state.delta()).toBeUndefined();
    });

    test('base_and_target_available', () => {
        fc.assert(
            fc.property(fc.record({baseId: fc.string(), targetId: fc.string(), baseRef: fc.string(), targetRef: fc.string()}), (value) => {
        const base = makeDiagram(value.baseId);
        const target = makeDiagram(value.targetId);
        const state = createDiffState(() => target, value.targetRef);
        state.setBase(base, value.baseRef);
        const result = state.delta();
        expect(result?.schemaVersion).toBe(1);
        expect(result?.baseRef).toBe(value.baseRef);
        expect(result?.targetRef).toBe(value.targetRef);
        expect(result?.nodeDeltas).toEqual([]);
        expect(result?.edgeDeltas).toEqual([]);
        expect(result?.groupDeltas).toEqual([]);
            })
        );
    });

    test('target_updates_with_base', () => {
        fc.assert(
            fc.property(fc.array(fc.string(), {minLength: 2, maxLength: 8}), (value) => {
        let current = makeDiagram(value[0]);
        let reads = 0;
        const target = (): Diagram | undefined => {
          reads += 1;
          return current;
        };
        const state = createDiffState(target, "target-ref");
        state.setBase(makeDiagram("base"), "base-ref");
        state.delta();
        const readsAfterFirstDelta = reads;
        current = makeDiagram(value[1]);
        const result = state.delta();
        expect(reads).toBeGreaterThan(readsAfterFirstDelta);
        expect(result?.baseRef).toBe("base-ref");
        expect(result?.targetRef).toBe("target-ref");
            })
        );
    });

    // WHEN: The base becomes attached while target() is undefined, then target() first returns a Diagram; delta() transitions from undefined to the computed Delta without another setBase call.
    // THEN: It changes delta() from undefined to the computed diff when target() first returns a Diagram.
    test('target_becomes_available_after_base', () => {
        let current: Diagram | undefined;
        const target = (): Diagram | undefined => current;
        const state = createDiffState(target, "target-ref");
        state.setBase(makeDiagram("base"), "base-ref");
        expect(state.delta()).toBeUndefined();
        current = makeDiagram("target");
        const result = state.delta();
        expect(result?.schemaVersion).toBe(1);
        expect(result?.baseRef).toBe("base-ref");
        expect(result?.targetRef).toBe("target-ref");
    });

    // WHEN: Calling setBase(undefined) detaches an otherwise attached base; delta() returns to undefined, including when target() currently returns a Diagram.
    // THEN: It returns delta() to undefined when setBase(undefined) detaches the base, even if a target is available.
    test('base_detached', () => {
        let current = makeDiagram("target");
        const state = createDiffState(() => current, "target-ref");
        state.setBase(makeDiagram("base"), "base-ref");
        expect(state.delta()?.baseRef).toBe("base-ref");
        state.setBase(undefined, "ignored");
        expect(state.delta()).toBeUndefined();
    });

    test('opaque_or_blank_labels', () => {
        fc.assert(
            fc.property(fc.record({baseRef: fc.string(), targetRef: fc.string()}), (value) => {
        const state = createDiffState(() => makeDiagram("target"), value.targetRef);
        state.setBase(makeDiagram("base"), value.baseRef);
        const result = state.delta();
        expect(result?.baseRef).toBe(value.baseRef);
        expect(result?.targetRef).toBe(value.targetRef);
        expect(result?.nodeDeltas).toEqual([]);
        expect(result?.edgeDeltas).toEqual([]);
        expect(result?.groupDeltas).toEqual([]);
            })
        );
    });

});

