// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import { create } from '@bufbuild/protobuf';

import { CONTENT_PARAMS } from '../src/shell/url_params';

describe('testgen_shell__CONTENT_PARAMS', () => {
    // WHEN: CONTENT_PARAMS contains exactly the content parameter names 'd', 's', and the base diagram parameter 'base_d', while base locator parameters such as 'base_fetch', 'base_gh', 'base_path', 'base_ref', and 'base_gist' remain excluded
    // THEN: CONTENT_PARAMS contains exactly 'd', 's', and 'base_d', while excluding 'base_fetch', 'base_gh', 'base_path', 'base_ref', and 'base_gist'.
    test('declared_content_params', () => {
        expect(CONTENT_PARAMS).toEqual(['d', 's', 'base_d']);
        expect(CONTENT_PARAMS).not.toContain('base_fetch');
        expect(CONTENT_PARAMS).not.toContain('base_gh');
        expect(CONTENT_PARAMS).not.toContain('base_path');
        expect(CONTENT_PARAMS).not.toContain('base_ref');
        expect(CONTENT_PARAMS).not.toContain('base_gist');
    });

});

