// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { StartScreenProps } from '../src/shell/start_screen';

describe('testgen_shell__StartScreenProps', () => {
    // WHEN: The screen is not loading, no error is provided, and onOpen is a callable callback; the normal start-screen action is available.
    // THEN: Shows the normal start-screen action and makes it available through onOpen.
    test('idle_without_error', () => {
        let opened = 0;
        const onOpen = () => {
          opened += 1;
        };
        const props = new StartScreenProps();
        props.loading = false;
        props.onOpen = onOpen;
        expect(props.loading).toBe(false);
        expect(props.error).toBeUndefined();
        expect(props.onOpen).toBe(onOpen);
        props.onOpen();
        expect(opened).toBe(1);
    });

    // WHEN: The screen is not loading and error is the empty string, with onOpen callable; this is the boundary case for a supplied but empty error value.
    // THEN: Treats the empty error as no error and shows the normal start-screen action through onOpen.
    test('idle_with_empty_error', () => {
        let opened = 0;
        const onOpen = () => {
          opened += 1;
        };
        const props = new StartScreenProps();
        props.loading = false;
        props.error = '';
        props.onOpen = onOpen;
        expect(props.loading).toBe(false);
        expect(props.error).toBe('');
        expect(props.onOpen).toBe(onOpen);
        props.onOpen();
        expect(opened).toBe(1);
    });

    test('idle_with_error', () => {
        fc.assert(
            fc.property(fc.string({ minLength: 1 }), (value) => {
        let opened = 0;
        const onOpen = () => {
          opened += 1;
        };
        const props = new StartScreenProps();
        props.loading = false;
        props.error = value;
        props.onOpen = onOpen;
        expect(props.loading).toBe(false);
        expect(props.error).toBe(value);
        expect(props.error.length).toBeGreaterThan(0);
        expect(props.onOpen).toBe(onOpen);
            })
        );
    });

    // WHEN: loading is true, no error is provided, and onOpen is callable; progress is shown instead of the start action while the URL-param load is in flight.
    // THEN: Shows loading progress instead of the start action while the URL-param load is in flight.
    test('loading_without_error', () => {
        let opened = 0;
        const onOpen = () => {
          opened += 1;
        };
        const props = new StartScreenProps();
        props.loading = true;
        props.onOpen = onOpen;
        expect(props.loading).toBe(true);
        expect(props.error).toBeUndefined();
        expect(props.onOpen).toBe(onOpen);
        props.onOpen();
        expect(opened).toBe(1);
    });

    // WHEN: loading is true and error is the empty string, with onOpen callable; loading takes precedence while the supplied error is empty.
    // THEN: Shows loading progress instead of the start action, with the empty error having no effect.
    test('loading_with_empty_error', () => {
        let opened = 0;
        const onOpen = () => {
          opened += 1;
        };
        const props = new StartScreenProps();
        props.loading = true;
        props.error = '';
        props.onOpen = onOpen;
        expect(props.loading).toBe(true);
        expect(props.error).toBe('');
        expect(props.onOpen).toBe(onOpen);
        props.onOpen();
        expect(opened).toBe(1);
    });

    test('loading_with_error', () => {
        fc.assert(
            fc.property(fc.string({ minLength: 1 }), (value) => {
        let opened = 0;
        const onOpen = () => {
          opened += 1;
        };
        const props = new StartScreenProps();
        props.loading = true;
        props.error = value;
        props.onOpen = onOpen;
        expect(props.loading).toBe(true);
        expect(props.error).toBe(value);
        expect(props.error.length).toBeGreaterThan(0);
        expect(props.onOpen).toBe(onOpen);
            })
        );
    });

});

