// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { COMMANDS } from '../src/gestures/commands';

describe('testgen_gestures__COMMANDS', () => {
    test('open_palette_from_any_overlay_state', () => {
        fc.assert(
            fc.property(fc.oneof(fc.constant(undefined), fc.string()), (value) => {
        const command = COMMANDS.find((entry) => entry.id === 'open-palette')!;
        let currentOverlay: unknown = value;
        const setOverlay = (next: unknown): void => {
          currentOverlay = next;
        };
        const context = {
          ui: {
            overlay: (): unknown => currentOverlay,
            setOverlay,
          },
        } as unknown as Parameters<typeof command.run>[0];

        command.run(context);
        expect(currentOverlay).toBe('palette');
            })
        );
    });

    test('open_help_from_any_overlay_state', () => {
        fc.assert(
            fc.property(fc.oneof(fc.constant(undefined), fc.string()), (value) => {
        const command = COMMANDS.find((entry) => entry.id === 'open-help')!;
        let currentOverlay: unknown = value;
        const setOverlay = (next: unknown): void => {
          currentOverlay = next;
        };
        const context = {
          ui: {
            overlay: (): unknown => currentOverlay,
            setOverlay,
          },
        } as unknown as Parameters<typeof command.run>[0];

        command.run(context);
        expect(currentOverlay).toBe('help');
            })
        );
    });

    test('escape_with_overlay_open', () => {
        fc.assert(
            fc.property(fc.record({ overlay: fc.string(), selection: fc.array(fc.record({ kind: fc.constantFrom('node', 'edge', 'group', 'annotation'), id: fc.string() })) }), (value) => {
        const command = COMMANDS.find((entry) => entry.id === 'escape')!;
        let currentOverlay: unknown = value.overlay;
        let selectionAfter: unknown = value.selection;
        const setOverlay = (next: unknown): void => {
          currentOverlay = next;
        };
        const setSelection = (next: unknown): void => {
          selectionAfter = next;
        };
        const context = {
          ui: {
            overlay: (): unknown => currentOverlay,
            setOverlay,
            selection: (): unknown => value.selection,
            setSelection,
          },
        } as unknown as Parameters<typeof command.run>[0];

        command.run(context);
        expect(currentOverlay).toBeUndefined();
        expect(selectionAfter).toEqual(value.selection);
            })
        );
    });

    test('escape_without_overlay', () => {
        fc.assert(
            fc.property(fc.array(fc.record({ kind: fc.constantFrom('node', 'edge', 'group', 'annotation'), id: fc.string() })), (value) => {
        const command = COMMANDS.find((entry) => entry.id === 'escape')!;
        let selectionAfter: unknown = value;
        const setSelection = (next: unknown): void => {
          selectionAfter = next;
        };
        const context = {
          ui: {
            overlay: (): undefined => undefined,
            setOverlay: (_next: unknown): void => {},
            selection: (): unknown => value,
            setSelection,
          },
        } as unknown as Parameters<typeof command.run>[0];

        command.run(context);
        expect(selectionAfter).toEqual([]);
            })
        );
    });

});

