// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { beginModalGesture } from '../src/ui_state/modal_gesture';

describe('testgen_ui_state__beginModalGesture', () => {
    test('grab_gesture', () => {
        fc.assert(
            fc.property(fc.array(fc.record({ id: fc.string(), kind: fc.constantFrom('node', 'edge', 'group', 'annotation') })), (value) => {
        const gesture = beginModalGesture('grab', value);
        expect(gesture).toEqual({
          kind: 'grab',
          refs: value,
          direction: undefined,
          digits: '',
        });
            })
        );
    });

    test('resize_gesture', () => {
        fc.assert(
            fc.property(fc.array(fc.record({ id: fc.string(), kind: fc.constantFrom('node', 'edge', 'group', 'annotation') })), (value) => {
        const gesture = beginModalGesture('resize', value);
        expect(gesture).toEqual({
          kind: 'resize',
          refs: value,
          direction: undefined,
          digits: '',
        });
            })
        );
    });

});

