// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { formatChord } from '../src/shell/chord_label';

describe('testgen_shell__formatChord', () => {
    function expectedChord(platform: string, chord: { key: string; meta?: boolean; shift?: boolean }): string {
      let key: string;
      switch (chord.key) {
        case 'ArrowUp': key = 'Up'; break;
        case 'ArrowDown': key = 'Down'; break;
        case 'ArrowLeft': key = 'Left'; break;
        case 'ArrowRight': key = 'Right'; break;
        case 'Escape': key = 'Esc'; break;
        default: key = chord.key.length === 1 ? chord.key.toUpperCase() : chord.key;
      }
      if (platform.includes('Mac')) {
        return (chord.meta ? '⌘' : '') + (chord.shift ? '⇧' : '') + key;
      }
      return (chord.meta ? 'Ctrl+' : '') + (chord.shift ? 'Shift+' : '') + key;
    }

    function setNavigator(platform: string, userAgent: string): void {
      Object.defineProperty(navigator, 'platform', { configurable: true, value: platform });
      Object.defineProperty(navigator, 'userAgent', { configurable: true, value: userAgent });
    }

    test('apple_no_modifiers', () => {
        fc.assert(
            fc.property(fc.constantFrom('a', 'Z', '?', 'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'Escape', 'Backspace', 'Delete', 'Enter', 'F1'), (value) => {
        setNavigator('MacIntel', '');
        expect(formatChord({ key: value })).toBe(expectedChord('MacIntel', { key: value }));
            })
        );
    });

    test('apple_meta_only', () => {
        fc.assert(
            fc.property(fc.constantFrom('a', 'Z', '?', 'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'Escape', 'Backspace', 'Delete', 'Enter', 'F1'), (value) => {
        setNavigator('MacIntel', '');
        expect(formatChord({ key: value, meta: true })).toBe(expectedChord('MacIntel', { key: value, meta: true }));
            })
        );
    });

    test('apple_shift_only', () => {
        fc.assert(
            fc.property(fc.constantFrom('a', 'Z', '?', 'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'Escape', 'Backspace', 'Delete', 'Enter', 'F1'), (value) => {
        setNavigator('MacIntel', '');
        expect(formatChord({ key: value, shift: true })).toBe(expectedChord('MacIntel', { key: value, shift: true }));
            })
        );
    });

    test('apple_meta_and_shift', () => {
        fc.assert(
            fc.property(fc.constantFrom('a', 'Z', '?', 'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'Escape', 'Backspace', 'Delete', 'Enter', 'F1'), (value) => {
        setNavigator('MacIntel', '');
        expect(formatChord({ key: value, meta: true, shift: true })).toBe(expectedChord('MacIntel', { key: value, meta: true, shift: true }));
            })
        );
    });

    test('non_apple_no_modifiers', () => {
        fc.assert(
            fc.property(fc.constantFrom('a', 'Z', '?', 'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'Escape', 'Backspace', 'Delete', 'Enter', 'F1'), (value) => {
        setNavigator('Linux', '');
        expect(formatChord({ key: value })).toBe(expectedChord('Linux', { key: value }));
            })
        );
    });

    test('non_apple_meta_only', () => {
        fc.assert(
            fc.property(fc.constantFrom('a', 'Z', '?', 'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'Escape', 'Backspace', 'Delete', 'Enter', 'F1'), (value) => {
        setNavigator('Linux', '');
        expect(formatChord({ key: value, meta: true })).toBe(expectedChord('Linux', { key: value, meta: true }));
            })
        );
    });

    test('non_apple_shift_only', () => {
        fc.assert(
            fc.property(fc.constantFrom('a', 'Z', '?', 'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'Escape', 'Escape', 'Backspace', 'Delete', 'Enter', 'F1'), (value) => {
        setNavigator('Linux', '');
        expect(formatChord({ key: value, shift: true })).toBe(expectedChord('Linux', { key: value, shift: true }));
            })
        );
    });

    test('non_apple_meta_and_shift', () => {
        fc.assert(
            fc.property(fc.constantFrom('a', 'Z', '?', 'ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'Escape', 'Backspace', 'Delete', 'Enter', 'F1'), (value) => {
        setNavigator('Linux', '');
        expect(formatChord({ key: value, meta: true, shift: true })).toBe(expectedChord('Linux', { key: value, meta: true, shift: true }));
            })
        );
    });

    test('single_character_key', () => {
        fc.assert(
            fc.property(fc.string({ minLength: 1, maxLength: 1 }), (value) => {
        setNavigator('Linux', '');
        expect(formatChord({ key: value, meta: true, shift: true })).toBe('Ctrl+Shift+' + value.toUpperCase());
            })
        );
    });

    // WHEN: The key is the single character '?'; upper-casing leaves it as '?', while any applicable modifier composition is applied before it.
    // THEN: It leaves the single-character key ? unchanged after applying any applicable modifier composition.
    test('question_mark_key', () => {
        setNavigator('Linux', '');
        expect(formatChord({ key: '?', meta: true, shift: true })).toBe('Ctrl+Shift+?');
    });

    // WHEN: The key is exactly 'ArrowUp'; it is renamed to 'Up', while any applicable modifier composition is applied before it.
    // THEN: It renames ArrowUp to Up after applying any applicable modifier composition.
    test('arrow_up_key', () => {
        setNavigator('MacIntel', '');
        expect(formatChord({ key: 'ArrowUp', meta: true, shift: true })).toBe('⌘⇧Up');
    });

    // WHEN: The key is exactly 'ArrowDown'; it is renamed to 'Down', while any applicable modifier composition is applied before it.
    // THEN: It renames ArrowDown to Down after applying any applicable modifier composition.
    test('arrow_down_key', () => {
        setNavigator('MacIntel', '');
        expect(formatChord({ key: 'ArrowDown', meta: true, shift: true })).toBe('⌘⇧Down');
    });

    // WHEN: The key is exactly 'ArrowLeft'; it is renamed to 'Left', while any applicable modifier composition is applied before it.
    // THEN: It renames ArrowLeft to Left after applying any applicable modifier composition.
    test('arrow_left_key', () => {
        setNavigator('MacIntel', '');
        expect(formatChord({ key: 'ArrowLeft', meta: true, shift: true })).toBe('⌘⇧Left');
    });

    // WHEN: The key is exactly 'ArrowRight'; it is renamed to 'Right', while any applicable modifier composition is applied before it.
    // THEN: It renames ArrowRight to Right after applying any applicable modifier composition.
    test('arrow_right_key', () => {
        setNavigator('MacIntel', '');
        expect(formatChord({ key: 'ArrowRight', meta: true, shift: true })).toBe('⌘⇧Right');
    });

    // WHEN: The key is exactly 'Escape'; it is renamed to 'Esc', while any applicable modifier composition is applied before it.
    // THEN: It renames Escape to Esc after applying any applicable modifier composition.
    test('escape_key', () => {
        setNavigator('MacIntel', '');
        expect(formatChord({ key: 'Escape', meta: true, shift: true })).toBe('⌘⇧Esc');
    });

    test('other_multicharacter_key', () => {
        fc.assert(
            fc.property(fc.string({ minLength: 2 }).filter((key) => !['ArrowUp', 'ArrowDown', 'ArrowLeft', 'ArrowRight', 'Escape'].includes(key)), (value) => {
        setNavigator('Linux', '');
        expect(formatChord({ key: value, shift: true })).toBe('Shift+' + value);
            })
        );
    });

    // WHEN: The key is exactly 'Backspace'; it remains 'Backspace' and is not renamed to 'Delete', while any applicable modifier composition is applied before it.
    // THEN: It preserves Backspace as Backspace rather than renaming it to Delete, after applying any applicable modifier composition.
    test('backspace_key', () => {
        setNavigator('Linux', '');
        expect(formatChord({ key: 'Backspace', meta: true })).toBe('Ctrl+Backspace');
    });

    // WHEN: The key is exactly 'Delete'; it remains 'Delete', while any applicable modifier composition is applied before it.
    // THEN: It preserves Delete as Delete after applying any applicable modifier composition.
    test('delete_key', () => {
        setNavigator('Linux', '');
        expect(formatChord({ key: 'Delete', meta: true })).toBe('Ctrl+Delete');
    });

    // WHEN: The key is exactly 'Enter'; it remains 'Enter', while any applicable modifier composition is applied before it.
    // THEN: It preserves Enter as Enter after applying any applicable modifier composition.
    test('enter_key', () => {
        setNavigator('Linux', '');
        expect(formatChord({ key: 'Enter', meta: true })).toBe('Ctrl+Enter');
    });

    test('platform_read_per_call', () => {
        fc.assert(
            fc.property(fc.constantFrom(['MacIntel', 'Linux'], ['Linux', 'MacIntel']), (value) => {
        // The domain contains both orderings, so the expectation is derived
        // from the platform set rather than assuming Apple comes first.
        const expected = (platform: string): string =>
          platform.includes('Mac') ? '⌘⇧Z' : 'Ctrl+Shift+Z';
        setNavigator(value[0], '');
        expect(formatChord({ key: 'z', meta: true, shift: true })).toBe(expected(value[0]));
        setNavigator(value[1], '');
        expect(formatChord({ key: 'z', meta: true, shift: true })).toBe(expected(value[1]));
            })
        );
    });

    test('user_agent_ignored', () => {
        fc.assert(
            fc.property(fc.tuple(fc.string(), fc.string()), (value) => {
        setNavigator('MacIntel', value[0]);
        expect(formatChord({ key: 'x', meta: true })).toBe('⌘X');
        setNavigator('Linux', value[1]);
        expect(formatChord({ key: 'x', meta: true })).toBe('Ctrl+X');
            })
        );
    });

});

