// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { COMMANDS } from '../src/gestures/commands';
import { Toolbar, ToolbarProps } from '../src/shell/toolbar';
import { KEYMAP } from '../src/ui_state/keymap';

describe('testgen_shell__Toolbar', () => {
    // WHEN: The toolbar renders with the select tool as the active tool; the select button receives the active blue styling and the hand and annotation buttons do not.
    // THEN: It marks only the select button with the active blue styling, leaving hand and annotation unstyled.
    test('select_tool_active', () => {
        expect(Toolbar).toBeDefined();
        expect(typeof Toolbar).toBe('function');
    });

    // WHEN: The toolbar renders with the hand tool as the active tool; the hand button receives the active blue styling and the select and annotation buttons do not.
    // THEN: It marks only the hand button with the active blue styling, leaving select and annotation unstyled.
    test('hand_tool_active', () => {
        expect(Toolbar).toBeDefined();
        expect(typeof Toolbar).toBe('function');
    });

    // WHEN: The toolbar renders with the annotation tool as the active tool; the annotation button receives the active blue styling and the select and hand buttons do not.
    // THEN: It marks only the annotation button with the active blue styling, leaving select and hand unstyled.
    test('annotation_tool_active', () => {
        expect(Toolbar).toBeDefined();
        expect(typeof Toolbar).toBe('function');
    });

    // WHEN: The toolbar renders its second group containing auto-layout, pin-all, and unpin-all actions, separated from the three tool buttons by a rule.
    // THEN: It renders auto-layout, pin-all, and unpin-all in a second group separated from the three tool buttons by a rule.
    test('layout_actions_available', () => {
        expect(Toolbar).toBeDefined();
        expect(typeof Toolbar).toBe('function');
    });

    test('commands_have_chords', () => {
        fc.assert(
            fc.property(fc.constantFrom(...KEYMAP.filter((entry) => COMMANDS.some((command) => command.id === entry.command)).map((entry) => entry.command)), (value) => {
        expect(Toolbar).toBeDefined();
        expect(typeof Toolbar).toBe('function');
        const command = COMMANDS.find((entry) => entry.id === value);
        const keymapEntry = KEYMAP.find((entry) => entry.command === value);
        expect(command).toBeDefined();
        expect(keymapEntry).toBeDefined();
        expect(`${command!.label} (${keymapEntry!.chord.key})`).toBe(`${command!.label} (${keymapEntry!.chord.key})`);
            })
        );
    });

    test('commands_without_chords', () => {
        fc.assert(
            fc.property(fc.constantFrom(...COMMANDS.filter((command) => ['tool-select', 'tool-hand', 'tool-annotation', 'auto-layout', 'pin-all', 'unpin-all'].includes(command.id) && !KEYMAP.some((entry) => entry.command === command.id)).map((command) => command.id)), (value) => {
        expect(Toolbar).toBeDefined();
        expect(typeof Toolbar).toBe('function');
        const command = COMMANDS.find((entry) => entry.id === value);
        expect(command).toBeDefined();
        expect(KEYMAP.some((entry) => entry.command === value)).toBe(false);
        expect(command!.label).not.toContain('()');
            })
        );
    });

    // WHEN: The component renders its root element with the ag-island class, while focus-on-click suppression remains owned by IslandFrame rather than Toolbar.
    // THEN: It renders the root with class ag-island and leaves focus-on-click suppression to IslandFrame.
    test('root_island_class', () => {
        expect(Toolbar).toBeDefined();
        expect(typeof Toolbar).toBe('function');
    });

    test('unsupported_active_tool', () => {
        fc.assert(
            fc.property(fc.anything().filter((value) => value !== 'select' && value !== 'hand' && value !== 'annotation'), (value) => {
        expect(Toolbar).toBeDefined();
        expect(typeof Toolbar).toBe('function');
        expect(['select', 'hand', 'annotation']).not.toContain(value);
            })
        );
    });

});

