// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { BrowserFsAdapter } from '../src/adapters/browser_fs_adapter';
import { GitForgeIssueBackend } from '../src/adapters/git_forge_issue_backend';
import { GitForgePrBackend } from '../src/adapters/git_forge_pr_backend';
import { GitHubForge } from '../src/adapters/github_forge';
import { UrlParamAdapter } from '../src/adapters/url_param_adapter';
import { selectAdapters } from '../src/shell/select_adapters';

describe('testgen_shell__selectAdapters', () => {
    test('pr_parameter_present', () => {
        fc.assert(
            fc.property(fc.record({
      pr: fc.string(),
      issue: fc.option(fc.string(), { nil: undefined }),
      fetch: fc.option(fc.string(), { nil: undefined }),
      gh: fc.option(fc.string(), { nil: undefined }),
      d: fc.option(fc.string(), { nil: undefined }),
      s: fc.option(fc.string(), { nil: undefined }),
    }), (value) => {
        const params = new URLSearchParams();
        params.set('pr', value.pr);
        if (value.issue !== undefined) params.set('issue', value.issue);
        if (value.fetch !== undefined) params.set('fetch', value.fetch);
        if (value.gh !== undefined) params.set('gh', value.gh);
        if (value.d !== undefined) params.set('d', value.d);
        if (value.s !== undefined) params.set('s', value.s);

        const result = selectAdapters(params);
        expect(result.adapter).toBeInstanceOf(UrlParamAdapter);
        expect(result.backend).toBeInstanceOf(GitForgePrBackend);
        const backend = result.backend as GitForgePrBackend;
        expect(backend.pr).toBe(value.pr);
        expect(backend.forge).toBeInstanceOf(GitHubForge);
            })
        );
    });

    test('issue_parameter_present_without_pr', () => {
        fc.assert(
            fc.property(fc.record({
      issue: fc.string(),
      fetch: fc.option(fc.string(), { nil: undefined }),
      gh: fc.option(fc.string(), { nil: undefined }),
      d: fc.option(fc.string(), { nil: undefined }),
      s: fc.option(fc.string(), { nil: undefined }),
    }), (value) => {
        const params = new URLSearchParams();
        params.set('issue', value.issue);
        if (value.fetch !== undefined) params.set('fetch', value.fetch);
        if (value.gh !== undefined) params.set('gh', value.gh);
        if (value.d !== undefined) params.set('d', value.d);
        if (value.s !== undefined) params.set('s', value.s);

        const result = selectAdapters(params);
        expect(result.adapter).toBeInstanceOf(UrlParamAdapter);
        expect(result.backend).toBeInstanceOf(GitForgeIssueBackend);
        const backend = result.backend as GitForgeIssueBackend;
        expect(backend.issue).toBe(value.issue);
        expect(backend.forge).toBeInstanceOf(GitHubForge);
            })
        );
    });

    test('remote_parameter_present_without_pr_or_issue', () => {
        fc.assert(
            fc.property(fc.record({
      fetch: fc.boolean(),
      gh: fc.boolean(),
      d: fc.boolean(),
      s: fc.boolean(),
      fetchValue: fc.string(),
      ghValue: fc.string(),
      dValue: fc.string(),
      sValue: fc.string(),
    }).filter((value) => value.fetch || value.gh || value.d || value.s), (value) => {
        const params = new URLSearchParams();
        if (value.fetch) params.set('fetch', value.fetchValue);
        if (value.gh) params.set('gh', value.ghValue);
        if (value.d) params.set('d', value.dValue);
        if (value.s) params.set('s', value.sValue);

        const result = selectAdapters(params);
        expect(result.adapter).toBeInstanceOf(UrlParamAdapter);
        expect(result.backend).toBeUndefined();
            })
        );
    });

    // WHEN: None of `pr`, `issue`, `fetch`, `gh`, `d`, or `s` is present. The result uses BrowserFsAdapter and has no backend.
    // THEN: Returns an AdapterPair with a BrowserFsAdapter and no backend.
    test('no_selection_parameters', () => {
        const result = selectAdapters(new URLSearchParams());
        expect(result.adapter).toBeInstanceOf(BrowserFsAdapter);
        expect(result.backend).toBeUndefined();
    });

});

