// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { COMMANDS } from '../src/gestures/commands';
import { UndoIsland, UndoIslandProps } from '../src/shell/undo_island';
import { KEYMAP } from '../src/ui_state/keymap';

describe('testgen_shell__UndoIsland', () => {
    const assertUndoIslandExport = (): void => {
      expect(UndoIsland).toBeDefined();
      expect(typeof UndoIsland).toBe('function');
    };

    test('both_history_actions_available', () => {
        fc.assert(
            fc.property(fc.record({ undoDepth: fc.integer({ min: 1, max: 100 }), redoDepth: fc.integer({ min: 1, max: 100 }) }), (value) => {
        assertUndoIslandExport();
        expect(value.undoDepth).toBeGreaterThan(0);
        expect(value.redoDepth).toBeGreaterThan(0);
            })
        );
    });

    test('undo_unavailable', () => {
        fc.assert(
            fc.property(fc.record({ redoDepth: fc.nat({ max: 100 }) }), (value) => {
        assertUndoIslandExport();
        expect(value.redoDepth).toBeGreaterThanOrEqual(0);
            })
        );
    });

    test('redo_unavailable', () => {
        fc.assert(
            fc.property(fc.record({ undoDepth: fc.nat({ max: 100 }) }), (value) => {
        assertUndoIslandExport();
        expect(value.undoDepth).toBeGreaterThanOrEqual(0);
            })
        );
    });

    test('both_history_actions_unavailable', () => {
        fc.assert(
            fc.property(fc.record({ historyLength: fc.nat({ max: 100 }), initial: fc.boolean() }), (value) => {
        assertUndoIslandExport();
        expect(value.historyLength).toBeGreaterThanOrEqual(0);
            })
        );
    });

    test('command_label_from_registry', () => {
        fc.assert(
            fc.property(fc.constantFrom(...COMMANDS.filter((command) => command.id === 'undo' || command.id === 'redo').map((command) => command.label)), (value) => {
        assertUndoIslandExport();
        expect(COMMANDS.some((command) => (command.id === 'undo' || command.id === 'redo') && command.label === value)).toBe(true);
            })
        );
    });

    test('command_with_key_chord', () => {
        fc.assert(
            fc.property(fc.constantFrom(...KEYMAP.filter((entry) => entry.command === 'undo' || entry.command === 'redo').map((entry) => ({ command: entry.command, key: entry.chord.key }))), (value) => {
        assertUndoIslandExport();
        expect(KEYMAP.some((entry) => entry.command === value.command && entry.chord.key === value.key)).toBe(true);
            })
        );
    });

    test('command_without_key_chord', () => {
        fc.assert(
            fc.property(fc.constantFrom(...COMMANDS.filter((command) => !KEYMAP.some((entry) => entry.command === command.id)).map((command) => ({ id: command.id, label: command.label }))), (value) => {
        assertUndoIslandExport();
        expect(COMMANDS.some((command) => command.id === value.id && command.label === value.label && !KEYMAP.some((entry) => entry.command === command.id))).toBe(true);
            })
        );
    });

    test('mousedown_on_focused_button', () => {
        fc.assert(
            fc.property(fc.constantFrom('undo', 'redo'), (value) => {
        assertUndoIslandExport();
        expect(value === 'undo' || value === 'redo').toBe(true);
            })
        );
    });

    test('history_changes_during_edit_run', () => {
        fc.assert(
            fc.property(fc.array(fc.record({ canUndo: fc.boolean(), canRedo: fc.boolean() }), { minLength: 1, maxLength: 20 }), (value) => {
        assertUndoIslandExport();
        expect(value.length).toBeGreaterThan(0);
        expect(value.every((state) => typeof state.canUndo === 'boolean' && typeof state.canRedo === 'boolean')).toBe(true);
            })
        );
    });

});

