// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { ToolbarProps } from '../src/shell/toolbar';

describe('testgen_shell__ToolbarProps', () => {
    test('select_tool_active', () => {
        fc.assert(
            fc.property(fc.constantFrom('select'), (value) => {
        const props = new ToolbarProps();
        props.tool = value as any;
        expect(props.tool).toBe(value);
            })
        );
    });

    test('hand_tool_active', () => {
        fc.assert(
            fc.property(fc.constantFrom('hand'), (value) => {
        const props = new ToolbarProps();
        props.tool = value as any;
        expect(props.tool).toBe(value);
            })
        );
    });

    test('annotation_tool_active', () => {
        fc.assert(
            fc.property(fc.constantFrom('annotation'), (value) => {
        const props = new ToolbarProps();
        props.tool = value as any;
        expect(props.tool).toBe(value);
            })
        );
    });

    test('command_callback_dispatches', () => {
        fc.assert(
            fc.property(fc.constantFrom('tool-select', 'tool-hand', 'tool-annotation'), (value) => {
        const received: unknown[] = [];
        const props = new ToolbarProps();
        props.onCommand = (command) => {
          received.push(command);
        };
        props.onCommand(value as any);
        expect(received).toEqual([value]);
            })
        );
    });

    // WHEN: Activating the select toolbar control calls onCommand with the tool-select command.
    // THEN: Calls onCommand with the tool-select command when the select control is activated.
    test('select_command_dispatch', () => {
        const received: unknown[] = [];
        const props = new ToolbarProps();
        props.onCommand = (command) => {
          received.push(command);
        };
        props.onCommand('tool-select' as any);
        expect(received).toEqual(['tool-select']);
    });

    // WHEN: Activating the hand toolbar control calls onCommand with the tool-hand command.
    // THEN: Calls onCommand with the tool-hand command when the hand control is activated.
    test('hand_command_dispatch', () => {
        const received: unknown[] = [];
        const props = new ToolbarProps();
        props.onCommand = (command) => {
          received.push(command);
        };
        props.onCommand('tool-hand' as any);
        expect(received).toEqual(['tool-hand']);
    });

    // WHEN: Activating the annotation toolbar control calls onCommand with the tool-annotation command.
    // THEN: Calls onCommand with the tool-annotation command when the annotation control is activated.
    test('annotation_command_dispatch', () => {
        const received: unknown[] = [];
        const props = new ToolbarProps();
        props.onCommand = (command) => {
          received.push(command);
        };
        props.onCommand('tool-annotation' as any);
        expect(received).toEqual(['tool-annotation']);
    });

    test('keyboard_equivalent_command', () => {
        fc.assert(
            fc.property(fc.constantFrom('v', 'h', 't'), (value) => {
        const received: unknown[] = [];
        const props = new ToolbarProps();
        props.onCommand = (command) => {
          received.push(command);
        };
        const command = value === 'v' ? 'tool-select' : value === 'h' ? 'tool-hand' : 'tool-annotation';
        props.onCommand(command as any);
        expect(received).toEqual([command]);
            })
        );
    });

    // WHEN: onCommand is callable but intentionally performs no observable work; dispatch completes without a toolbar-owned state mutation.
    // THEN: Invokes onCommand and makes no toolbar-owned state mutation when the callback does nothing.
    test('callback_noop', () => {
        const props = new ToolbarProps();
        props.tool = 'select' as any;
        props.onCommand = () => {};
        const before = { tool: props.tool };
        props.onCommand('tool-hand' as any);
        expect(props.tool).toBe(before.tool);
    });

    // WHEN: onCommand is callable but throws while handling a dispatched command; the callback error propagates rather than being converted into toolbar state.
    // THEN: Propagates an error thrown by onCommand without converting it into toolbar state.
    test('callback_throws', () => {
        const props = new ToolbarProps();
        const error = new Error('toolbar callback failure');
        props.onCommand = () => {
          throw error;
        };
        expect(() => props.onCommand('tool-select' as any)).toThrow('toolbar callback failure');
    });

    // WHEN: The tool property is absent or remains uninitialized at runtime, so no valid active tool can be determined.
    // THEN: Treats the uninitialized tool as having no valid active-tool highlight.
    test('missing_tool', () => {
        const props = new ToolbarProps();
        expect(props.tool).toBeUndefined();
        expect(Object.prototype.hasOwnProperty.call(props, 'tool')).toBe(false);
    });

    test('invalid_tool', () => {
        fc.assert(
            fc.property(fc.anything().filter((value) => value !== 'select' && value !== 'hand' && value !== 'annotation'), (value) => {
        const props = new ToolbarProps();
        props.tool = value as any;
        expect(props.tool).toBe(value);
            })
        );
    });

    // WHEN: The tool property is explicitly null at runtime, so no valid active tool can be determined.
    // THEN: Provides no valid active-tool highlight when tool is null.
    test('null_tool', () => {
        const props = new ToolbarProps();
        props.tool = null as any;
        expect(props.tool).toBeNull();
    });

    // WHEN: The onCommand property is absent or remains uninitialized at runtime, so dispatch cannot call a handler.
    // THEN: Cannot dispatch a command because no onCommand handler is initialized.
    test('missing_command_callback', () => {
        const props = new ToolbarProps();
        expect(props.onCommand).toBeUndefined();
        expect(Object.prototype.hasOwnProperty.call(props, 'onCommand')).toBe(false);
    });

    // WHEN: The onCommand property is explicitly null at runtime, so dispatch cannot call a handler.
    // THEN: Cannot dispatch a command because onCommand is null and cannot be called.
    test('null_command_callback', () => {
        const props = new ToolbarProps();
        props.onCommand = null as any;
        expect(props.onCommand).toBeNull();
    });

    test('unsupported_command_id', () => {
        fc.assert(
            fc.property(fc.anything().filter((value) => value !== 'tool-select' && value !== 'tool-hand' && value !== 'tool-annotation'), (value) => {
        const received: unknown[] = [];
        const props = new ToolbarProps();
        props.onCommand = (command) => {
          received.push(command);
        };
        props.onCommand(value as any);
        expect(received).toEqual([value]);
            })
        );
    });

});

