// @generated by archebuild — do not edit. Regenerated each build.

import { boundsCentre, boundsProjectToEdge, type Bounds } from '../../geometry/bounds';
import type { Vec2 } from '../../geometry/vec2';

export function routeStraight(sourceBounds: Bounds, targetBounds: Bounds, sourceAttach?: Vec2, targetAttach?: Vec2): Vec2[] {
  const sourceCentre = boundsCentre(sourceBounds);
  const targetCentre = boundsCentre(targetBounds);
  const start = resolveAttachPoint(sourceBounds, targetCentre, sourceAttach);
  const end = resolveAttachPoint(targetBounds, sourceCentre, targetAttach);
  return [start, end];
}
export function resolveAttachPoint(bounds: Bounds, towardCentre: Vec2, attachHint?: Vec2): Vec2 {
  const centre = boundsCentre(bounds);
  if (attachHint === undefined) {
    return boundsProjectToEdge(bounds, towardCentre);
  }
  const halfWidth = (bounds.maxX - bounds.minX) / 2;
  const halfHeight = (bounds.maxY - bounds.minY) / 2;
  const toward: Vec2 = {
    x: centre.x + attachHint.x * halfWidth,
    y: centre.y + attachHint.y * halfHeight,
  };
  return boundsProjectToEdge(bounds, toward);
}
export function routeOrthogonal(sourceBounds: Bounds, targetBounds: Bounds, sourceAttach?: Vec2, targetAttach?: Vec2): Vec2[] {
  throw new Error('not implemented');
}
