// @generated by archebuild — do not edit. Regenerated each build.

export function routeStraight(sourceBounds: Bounds, targetBounds: Bounds, sourceAttach?: Vec2, targetAttach?: Vec2): Vec2[] {
  throw new Error('not implemented');
}
export function resolveAttachPoint(bounds: Bounds, towardCentre: Vec2, attachHint?: Vec2): Vec2 {
  throw new Error('not implemented');
}
export function routeOrthogonal(sourceBounds: Bounds, targetBounds: Bounds, sourceAttach?: Vec2, targetAttach?: Vec2): Vec2[] {
  throw new Error('not implemented');
}
