// @generated by archebuild — do not edit. Regenerated each build.

import { ResolvedDiagram } from '../resolved_diagram';
import { Tokens } from '@archeglyph/proto/gen/theme_pb';

export class ResolveTokensRequest {
  resolved!: ResolvedDiagram;
  tokens?: Tokens;
}
