// @generated by archebuild — do not edit. Regenerated each build.

import { LaidOutDiagram } from '../laid_out_diagram';
import { RenderError } from '../render_error';
import { Result } from '@archeglyph/proto/util/result';

export interface SvgRenderer {
  render(diagram: LaidOutDiagram): Result<string, RenderError>;
}
import { LaidOutDiagram } from '../laid_out_diagram';
import { RenderError } from '../render_error';
import { Result } from '@archeglyph/proto/util/result';
import { SvgRenderer } from './';

export class SvgRendererImpl implements SvgRenderer {
  render(diagram: LaidOutDiagram): Result<string, RenderError> { throw new Error('not implemented'); }
}
