// @generated by archebuild — do not edit. Regenerated each build.

import { create } from '@bufbuild/protobuf';
import { type Vec2 as ProtoVec2, Vec2Schema } from '@archeglyph/proto/gen/style_pb';

export function vec2fromProto(v: Vec2): Vec2 {
  throw new Error('not implemented');
}
export function vec2toProto(v: Vec2): ProtoVec2 {
  return create(Vec2Schema, { x: v.x, y: v.y });
}
export function length(v: Vec2): number {
  throw new Error('not implemented');
}
export function add(a: Vec2, b: Vec2): Vec2 {
  throw new Error('not implemented');
}
export function distance(a: Vec2, b: Vec2): number {
  throw new Error('not implemented');
}
export interface Vec2 {
  x: number;
  y: number;
}
export function dot(a: Vec2, b: Vec2): number {
  throw new Error('not implemented');
}
export function sub(a: Vec2, b: Vec2): Vec2 {
  throw new Error('not implemented');
}
export function angle(v: Vec2): number {
  throw new Error('not implemented');
}
export function normalize(v: Vec2): Vec2 {
  throw new Error('not implemented');
}
export function scale(v: Vec2, s: number): Vec2 {
  throw new Error('not implemented');
}
