// SPDX-License-Identifier: AGPL-3.0-or-later

// @generated by archebuild — do not edit. Regenerated each build.

export class DiffRoles {
  added!: string;
  modified!: string;
  deleted!: string;
}
import { Tokens } from '../../../proto/src/gen/theme_pb';
import { init } from '@archeglyph/proto/util/init';
import { resolveTokensIn } from '../resolver/token_resolver';

export function resolveDiffRoles(tokens?: Tokens): DiffRoles | undefined {
  if (tokens === undefined) return undefined;

  const roles = {
    added: '$roles.diff_added',
    modified: '$roles.diff_modified',
    deleted: '$roles.diff_deleted',
  };
  if (resolveTokensIn(roles, tokens).length > 0) return undefined;

  return init(new DiffRoles(), {
    added: roles.added,
    modified: roles.modified,
    deleted: roles.deleted,
  });
}
