// @generated by archebuild — do not edit. Regenerated each build.

import { boundsCentre, boundsProjectToEdge, type Bounds } from '@archeglyph/core/geometry/bounds';
import { type Vec2 } from '@archeglyph/core/geometry/vec2';

/**
 * How far OUTSIDE the annotation's outline the grip centre sits, in
 * diagram units. 14.
 *
 * Outside, not on the outline, and this is the whole reason the constant
 * exists. scene/hit_test draws eight resize handles and every one of them
 * is ON the outline -- four corners and four edge midpoints. A grip
 * anywhere on that boundary coincides with one of them for some target
 * direction, and two overlapping affordances that start different
 * gestures is worse than either.
 */
export const ANCHOR_GRIP_OFFSET: number = 14;

export function anchorGripPoint(bounds: Bounds, towardCentre?: Vec2): Vec2 {
  const centre = boundsCentre(bounds);
  const toward = towardCentre ?? { x: centre.x, y: centre.y + 1 };
  const edge = boundsProjectToEdge(bounds, toward);
  const dx = toward.x - centre.x;
  const dy = toward.y - centre.y;
  const length = Math.hypot(dx, dy);

  if (length === 0) {
    return { x: edge.x, y: edge.y + ANCHOR_GRIP_OFFSET };
  }

  return {
    x: edge.x + (dx / length) * ANCHOR_GRIP_OFFSET,
    y: edge.y + (dy / length) * ANCHOR_GRIP_OFFSET,
  };
}
export function anchorGripAt(geometry: SceneGeometry, selection: Array<ElementRef>, point: Vec2, radius: number): ElementRef | undefined {
  throw new Error('not implemented');
}
