// @generated by archebuild — do not edit. Regenerated each build.

/**
 * How far OUTSIDE the annotation's outline the grip centre sits, in
 * diagram units. 14.
 *
 * Outside, not on the outline, and this is the whole reason the constant
 * exists. scene/hit_test draws eight resize handles and every one of them
 * is ON the outline -- four corners and four edge midpoints. A grip
 * anywhere on that boundary coincides with one of them for some target
 * direction, and two overlapping affordances that start different
 * gestures is worse than either.
 */
export const ANCHOR_GRIP_OFFSET: number = 14;

export function anchorGripPoint(bounds: Bounds, towardCentre?: Vec2): Vec2 {
  throw new Error('not implemented');
}
export function anchorGripAt(geometry: SceneGeometry, selection: Array<ElementRef>, point: Vec2, radius: number): ElementRef | undefined {
  throw new Error('not implemented');
}
