// @generated by archebuild — do not edit. Regenerated each build.

export function calloutPreviews(geometry: SceneGeometry, moved: Array<ElementBounds>): Array<PreviewEdge> {
  throw new Error('not implemented');
}
