// @generated by archebuild — do not edit. Regenerated each build.

import { Handle } from './hit_test';
import { Vec2 } from '../vec2';

export interface HandlePoint {
  handle: Handle;
  point: Vec2;
}
export function hitTestPoint(geometry: SceneGeometry, point: Vec2, edgeTolerance: number): ElementRef | undefined {
  throw new Error('not implemented');
}
export function handlePositions(bounds: Bounds): Array<HandlePoint> {
  throw new Error('not implemented');
}
export type Handle = 'nw' | 'n' | 'ne' | 'e' | 'se' | 's' | 'sw' | 'w';
export function hitTestHandle(bounds: Bounds, point: Vec2, radius: number): Handle | undefined {
  throw new Error('not implemented');
}
