// @generated by archebuild — do not edit. Regenerated each build.

import { Bounds } from '../bounds';
import { Vec2 } from '../vec2';

export interface PreviewEdge {
  id: string;
  points: Array<Vec2>;
}
import { ElementBounds } from './scene';
import { PreviewEdge } from './preview';

export interface ScenePreview {
  bounds: Array<ElementBounds>;
  edges: Array<PreviewEdge>;
}
export function previewMove(geometry: SceneGeometry, intent: MoveIntent): ScenePreview {
  throw new Error('not implemented');
}
export function routeEdgeBetween(edge: LaidOutEdge, sourceBounds: Bounds, targetBounds: Bounds): Array<Vec2> {
  throw new Error('not implemented');
}
export function resizeBounds(bounds: Bounds, handle: Handle, delta: Vec2): Bounds {
  const minimumSize = 1;
  const movesMinX = handle === 'nw' || handle === 'w' || handle === 'sw';
  const movesMaxX = handle === 'ne' || handle === 'e' || handle === 'se';
  const movesMinY = handle === 'nw' || handle === 'n' || handle === 'ne';
  const movesMaxY = handle === 'sw' || handle === 's' || handle === 'se';

  return {
    minX: movesMinX
      ? Math.min(bounds.maxX - minimumSize, bounds.minX + delta.x)
      : bounds.minX,
    minY: movesMinY
      ? Math.min(bounds.maxY - minimumSize, bounds.minY + delta.y)
      : bounds.minY,
    maxX: movesMaxX
      ? Math.max(bounds.minX + minimumSize, bounds.maxX + delta.x)
      : bounds.maxX,
    maxY: movesMaxY
      ? Math.max(bounds.minY + minimumSize, bounds.maxY + delta.y)
      : bounds.maxY,
  };
}
import { ElementRef } from '../element_ref';
import { Vec2 } from '../vec2';

export interface MoveIntent {
  refs: Array<ElementRef>;
  delta: Vec2;
}
import { ElementRef } from '../element_ref';
import { Handle } from './hit_test';
import { Vec2 } from '../vec2';

export interface ResizeIntent {
  ref: ElementRef;
  handle: Handle;
  delta: Vec2;
}
export function previewResize(geometry: SceneGeometry, intent: ResizeIntent): ScenePreview {
  throw new Error('not implemented');
}
