// @generated by archebuild — do not edit. Regenerated each build.

import { Vec2 } from '../vec2';

export interface PreviewEdge {
  id: string;
  points: Array<Vec2>;
}
import { ElementBounds } from './scene';
import { PreviewEdge } from './preview';

export interface ScenePreview {
  bounds: Array<ElementBounds>;
  edges: Array<PreviewEdge>;
}
export function previewMove(geometry: SceneGeometry, intent: MoveIntent): ScenePreview {
  throw new Error('not implemented');
}
export function routeEdgeBetween(edge: LaidOutEdge, sourceBounds: Bounds, targetBounds: Bounds): Array<Vec2> {
  throw new Error('not implemented');
}
export function resizeBounds(bounds: Bounds, handle: Handle, delta: Vec2): Bounds {
  throw new Error('not implemented');
}
import { ElementRef } from '../element_ref';
import { Vec2 } from '../vec2';

export interface MoveIntent {
  refs: Array<ElementRef>;
  delta: Vec2;
}
import { ElementRef } from '../element_ref';
import { Handle } from './hit_test';
import { Vec2 } from '../vec2';

export interface ResizeIntent {
  ref: ElementRef;
  handle: Handle;
  delta: Vec2;
}
export function previewResize(geometry: SceneGeometry, intent: ResizeIntent): ScenePreview {
  throw new Error('not implemented');
}
