// @generated by archebuild — do not edit. Regenerated each build.

import { boundsFromRect, boundsUnion, Bounds } from '@archeglyph/core/geometry/bounds';
import { LaidOutDiagram } from '@archeglyph/core/layout/laid_out_diagram';
import { Vec2 } from '@archeglyph/core/geometry/vec2';
import { elementKey } from './element_key';
import { ElementBounds } from './scene';
import { ElementRef } from '../ui_state/ui_state';

export interface SceneGeometry {
  diagram: LaidOutDiagram;
  index: Array<ElementBounds>;
  byKey: Record<string, ElementBounds>;
  edgePolylines: Record<string, Vec2[]>;
  contentBounds: Bounds;
  svg: string;
}
export function buildSceneGeometry(diagram: LaidOutDiagram, svg: string): SceneGeometry {
  const index: Array<ElementBounds> = [];
  const byKey: Record<string, ElementBounds> = {};

  const add = (ref: ElementRef, position: Vec2, size: Vec2, parentGroup: string | undefined): void => {
    const entry: ElementBounds = {
      ref,
      bounds: boundsFromRect(position, size),
      ...(parentGroup === undefined ? {} : { parentGroup }),
    };
    index.push(entry);
    byKey[elementKey(ref)] = entry;
  };

  for (const node of diagram.nodes) {
    add({ kind: 'node', id: node.id }, node.position, node.size, node.parentGroup);
  }
  for (const group of diagram.groups) {
    add({ kind: 'group', id: group.id }, group.position, group.size, group.parentGroup);
  }
  for (const annotation of diagram.annotations) {
    add({ kind: 'annotation', id: annotation.id }, annotation.position, annotation.size, undefined);
  }

  const edgePolylines: Record<string, Vec2[]> = {};
  for (const edge of diagram.edges) {
    const points: Vec2[] = [];
    for (const section of edge.sections) {
      points.push(section.startPoint, ...section.bendPoints, section.endPoint);
    }
    edgePolylines[edge.id] = points;
  }

  const contentBounds = index.reduce(
    (bounds, entry) => bounds === undefined ? entry.bounds : boundsUnion(bounds, entry.bounds),
    undefined as Bounds | undefined,
  ) ?? { minX: 0, minY: 0, maxX: 0, maxY: 0 };

  return { diagram, index, byKey, edgePolylines, contentBounds, svg };
}
export interface SceneError {
  stage: string;
  message: string;
}
import { ElementRef } from '../ui_state/ui_state';

export interface ElementBounds {
  ref: ElementRef;
  bounds: Bounds;
  parentGroup?: string;
}
export function createScene(state: EditorState, theme: Accessor<Theme>, layoutEngine: LayoutEngine): Scene {
  throw new Error('not implemented');
}
export interface Scene {
  geometry: Accessor<SceneGeometry | undefined>;
  error: Accessor<SceneError | undefined>;
  loading: Accessor<boolean>;
}
