// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import { create } from '@bufbuild/protobuf';
import {
  DiagramSchema, GraphSchema, NodeSchema, EdgeSchema, GroupSchema,
  DeltaSchema, NodeDeltaSchema, EdgeDeltaSchema, GroupDeltaSchema,
} from '@archeglyph/proto/gen/content_pb';
import {
  StylesheetSchema, StrokeSchema, FillSchema, GlowSchema, GradientSchema,
  Glyph1DSchema, Glyph2DSchema, DecorationSchema, TypographySchema,
  ArrowheadsSchema, CanvasStyleSchema,
} from '@archeglyph/proto/gen/style_pb';
import { TokensSchema, ThemeSchema } from '@archeglyph/proto/gen/theme_pb';
import * as fc from 'fast-check';

import { rotateHue } from '../src/delta/hue';

describe('testgen_delta__rotateHue', () => {
    function expectedRotateHue(color: string, degrees: number): string {
      const red: number = parseInt(color.slice(1, 3), 16) / 255;
      const green: number = parseInt(color.slice(3, 5), 16) / 255;
      const blue: number = parseInt(color.slice(5, 7), 16) / 255;
      const maximum: number = Math.max(red, green, blue);
      const minimum: number = Math.min(red, green, blue);
      const lightness: number = (maximum + minimum) / 2;
      const difference: number = maximum - minimum;
      let hue: number = 0;
      let saturation: number = 0;
      if (difference !== 0) {
        saturation = difference / (1 - Math.abs(2 * lightness - 1));
        if (maximum === red) {
          hue = 60 * (((green - blue) / difference) % 6);
        } else if (maximum === green) {
          hue = 60 * ((blue - red) / difference + 2);
        } else {
          hue = 60 * ((red - green) / difference + 4);
        }
      }
      hue = ((hue + degrees) % 360 + 360) % 360;
      const hueToRgb = (p: number, q: number, t: number): number => {
        let normalized: number = t;
        if (normalized < 0) normalized += 1;
        if (normalized > 1) normalized -= 1;
        if (normalized < 1 / 6) return p + (q - p) * 6 * normalized;
        if (normalized < 1 / 2) return q;
        if (normalized < 2 / 3) return p + (q - p) * (2 / 3 - normalized) * 6;
        return p;
      };
      const chroma: number = (1 - Math.abs(2 * lightness - 1)) * saturation;
      const q: number = lightness < 0.5 ? lightness * (1 + saturation) : lightness + saturation - lightness * saturation;
      const p: number = 2 * lightness - q;
      const normalizedHue: number = hue / 360;
      const outputRed: number = difference === 0 ? lightness : hueToRgb(p, q, normalizedHue + 1 / 3);
      const outputGreen: number = difference === 0 ? lightness : hueToRgb(p, q, normalizedHue);
      const outputBlue: number = difference === 0 ? lightness : hueToRgb(p, q, normalizedHue - 1 / 3);
      const toHex = (channel: number): string => Math.round(channel * 255).toString(16).padStart(2, '0');
      void chroma;
      return `#${toHex(outputRed)}${toHex(outputGreen)}${toHex(outputBlue)}`;
    }

    test('accepted_six_digit_hex', () => {
        fc.assert(
            fc.property(fc.stringMatching(/^#[0-9a-fA-F]{6}$/), (value) => {
        expect(rotateHue(value, 137.25)).toBe(expectedRotateHue(value, 137.25));
            })
        );
    });

    test('rejected_three_digit_hex', () => {
        fc.assert(
            fc.property(fc.constantFrom('#abc', '#ABC', '#123', '#aF0'), (value) => {
        expect(rotateHue(value, 180)).toBe(value);
            })
        );
    });

    test('rejected_named_colour', () => {
        fc.assert(
            fc.property(fc.constantFrom('none', 'red', 'transparent', 'RebeccaPurple', 'currentColor'), (value) => {
        expect(rotateHue(value, -45)).toBe(value);
            })
        );
    });

    test('rejected_unresolved_token', () => {
        fc.assert(
            fc.property(fc.constantFrom('$roles.node_fill', '$roles.background', '$theme.primary_text', '$color.accent'), (value) => {
        expect(rotateHue(value, 270)).toBe(value);
            })
        );
    });

    // WHEN: The empty string is rejected and returned unchanged, without an error.
    // THEN: Returns the empty string unchanged without raising an error.
    test('rejected_empty_string', () => {
        expect(rotateHue('', 180)).toBe('');
    });

    test('accepted_uppercase_normalization', () => {
        fc.assert(
            fc.property(fc.constantFrom('#8A8A8A', '#AAAAAA', '#B0B0B0'), (value) => {
        expect(rotateHue(value, 180)).toBe(value.toLowerCase());
            })
        );
    });

    test('saturated_colour_hue_rotation', () => {
        fc.assert(
            fc.property(fc.constantFrom('#8ad1ff', '#73daca', '#122238', '#ff0000', '#00aF7B', '#6633cc'), (value) => {
        expect(rotateHue(value, 180)).toBe(expectedRotateHue(value, 180));
            })
        );
    });

    test('zero_saturation_identity', () => {
        fc.assert(
            fc.property(fc.constantFrom('#000000', '#FFFFFF', '#8A8A8A', '#bBbBbB', '#404040'), (value) => {
        expect(rotateHue(value, 271.5)).toBe(value.toLowerCase());
            })
        );
    });

    // WHEN: A finite degree value of zero leaves the colour unchanged apart from the required lowercase output normalization for accepted inputs.
    // THEN: Returns an accepted colour unchanged apart from required lowercase normalization when degrees is zero.
    test('zero_degree_rotation', () => {
        expect(rotateHue('#8A12f0', 0)).toBe('#8a12f0');
    });

    test('full_turn_rotation', () => {
        fc.assert(
            fc.property(fc.integer({ min: -1000000, max: 1000000 }).map((turns) => turns * 360), (value) => {
        expect(rotateHue('#73daca', value)).toBe('#73daca');
            })
        );
    });

    test('negative_degree_rotation', () => {
        fc.assert(
            fc.property(fc.double({ noNaN: true, noDefaultInfinity: true, max: -Number.MIN_VALUE }), (value) => {
        expect(rotateHue('#8ad1ff', value)).toBe(expectedRotateHue('#8ad1ff', value));
            })
        );
    });

    test('over_360_degree_rotation', () => {
        fc.assert(
            fc.property(fc.double({ noNaN: true, noDefaultInfinity: true, min: 360 + Number.EPSILON }), (value) => {
        expect(rotateHue('#8ad1ff', value)).toBe(expectedRotateHue('#8ad1ff', value));
            })
        );
    });

    test('fractional_degree_rotation', () => {
        fc.assert(
            fc.property(fc.double({ noNaN: true, noDefaultInfinity: true }).filter((degrees) => Number.isFinite(degrees) && !Number.isInteger(degrees)), (value) => {
        expect(rotateHue('#73daca', value)).toBe(expectedRotateHue('#73daca', value));
            })
        );
    });

});

