// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import { create } from '@bufbuild/protobuf';
import * as fc from 'fast-check';

import { diffColorFor } from '../src/delta/diff_color';
import { desaturate, rotateHue } from '../src/delta/hue';
import { ChangeType } from '../../proto/src/gen/content_pb';

describe('testgen_delta__diffColorFor', () => {
    test('unchanged_color', () => {
        fc.assert(
            fc.property(fc.record({ color: fc.string(), diffRoles: fc.oneof(fc.constant(undefined), fc.record({ added: fc.string(), modified: fc.string(), deleted: fc.string() })) }), (value) => {
        const diffRoles = value.diffRoles === undefined ? undefined : {
          get added(): string { throw new Error('diffRoles was read'); },
          get modified(): string { throw new Error('diffRoles was read'); },
          get deleted(): string { throw new Error('diffRoles was read'); },
        };
        expect(diffColorFor(value.color, ChangeType.UNCHANGED, diffRoles)).toBe(desaturate(value.color));
            })
        );
    });

    test('unspecified_color', () => {
        fc.assert(
            fc.property(fc.record({ color: fc.string(), diffRoles: fc.oneof(fc.constant(undefined), fc.record({ added: fc.string(), modified: fc.string(), deleted: fc.string() })) }), (value) => {
        const diffRoles = value.diffRoles === undefined ? undefined : {
          get added(): string { throw new Error('diffRoles was read'); },
          get modified(): string { throw new Error('diffRoles was read'); },
          get deleted(): string { throw new Error('diffRoles was read'); },
        };
        expect(diffColorFor(value.color, ChangeType.CHANGE_TYPE_UNSPECIFIED, diffRoles)).toBe(desaturate(value.color));
            })
        );
    });

    test('added_table_mode', () => {
        fc.assert(
            fc.property(fc.record({ color: fc.string(), added: fc.string(), modified: fc.string(), deleted: fc.string() }), (value) => {
        const diffRoles = { added: value.added, modified: value.modified, deleted: value.deleted };
        expect(diffColorFor(value.color, ChangeType.ADDED, diffRoles)).toBe(value.added);
            })
        );
    });

    test('modified_table_mode', () => {
        fc.assert(
            fc.property(fc.record({ color: fc.string(), added: fc.string(), modified: fc.string(), deleted: fc.string() }), (value) => {
        const diffRoles = { added: value.added, modified: value.modified, deleted: value.deleted };
        expect(diffColorFor(value.color, ChangeType.MODIFIED, diffRoles)).toBe(value.modified);
            })
        );
    });

    test('deleted_table_mode', () => {
        fc.assert(
            fc.property(fc.record({ color: fc.string(), added: fc.string(), modified: fc.string(), deleted: fc.string() }), (value) => {
        const diffRoles = { added: value.added, modified: value.modified, deleted: value.deleted };
        expect(diffColorFor(value.color, ChangeType.DELETED, diffRoles)).toBe(value.deleted);
            })
        );
    });

    test('added_rotate_mode', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        expect(diffColorFor(value, ChangeType.ADDED)).toBe(rotateHue(value, 300));
            })
        );
    });

    test('modified_rotate_mode', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        expect(diffColorFor(value, ChangeType.MODIFIED)).toBe(rotateHue(value, 60));
            })
        );
    });

    test('deleted_rotate_mode', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        expect(diffColorFor(value, ChangeType.DELETED)).toBe(rotateHue(value, 180));
            })
        );
    });

    test('desaturated_rotate_input', () => {
        fc.assert(
            fc.property(fc.integer({ min: 0, max: 255 }).map((channel: number): string => { const hex = channel.toString(16).padStart(2, '0'); return '#' + hex.repeat(3); }), (value) => {
        const added = diffColorFor(value, ChangeType.ADDED);
        const modified = diffColorFor(value, ChangeType.MODIFIED);
        const deleted = diffColorFor(value, ChangeType.DELETED);
        expect(added).toBe(value);
        expect(modified).toBe(value);
        expect(deleted).toBe(value);
        expect(added).toBe(modified);
        expect(modified).toBe(deleted);
            })
        );
    });

    test('non_hex_color', () => {
        fc.assert(
            fc.property(fc.string().filter((value: string): boolean => !/^#[0-9a-fA-F]{6}$/.test(value)), (value) => {
        const diffRoles = { added: 'table-added', modified: 'table-modified', deleted: 'table-deleted' };
        expect(diffColorFor(value, ChangeType.CHANGE_TYPE_UNSPECIFIED)).toBe(value);
        expect(diffColorFor(value, ChangeType.ADDED)).toBe(value);
        expect(diffColorFor(value, ChangeType.MODIFIED)).toBe(value);
        expect(diffColorFor(value, ChangeType.DELETED)).toBe(value);
        expect(diffColorFor(value, ChangeType.ADDED, diffRoles)).toBe('table-added');
        expect(diffColorFor(value, ChangeType.MODIFIED, diffRoles)).toBe('table-modified');
        expect(diffColorFor(value, ChangeType.DELETED, diffRoles)).toBe('table-deleted');
            })
        );
    });

});

