// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { isThemeDefault } from '../src/resolver/seed_bindings/derive';

describe('testgen_seed_bindings__isThemeDefault', () => {
    test('undefined_current', () => {
        fc.assert(
            fc.property(fc.string().filter((themeDefault) => themeDefault.length > 0), (value) => {
        expect(isThemeDefault(undefined, value)).toBe(true);
            })
        );
    });

    test('empty_current', () => {
        fc.assert(
            fc.property(fc.string().filter((themeDefault) => themeDefault.length > 0), (value) => {
        expect(isThemeDefault('', value)).toBe(true);
            })
        );
    });

    test('matching_split_parts', () => {
        fc.assert(
            fc.property(fc.record({ theme: fc.constantFrom('default', 'acme'), component: fc.string().filter((component) => component.length > 0 && !component.includes('.')) }).map(({ theme, component }) => ({ current: theme === 'default' ? component : `${theme}.${component}`, themeDefault: `${theme}.${component}` })), (value) => {
        expect(isThemeDefault(value.current, value.themeDefault)).toBe(true);
            })
        );
    });

    test('different_theme_name', () => {
        fc.assert(
            fc.property(fc.record({ currentTheme: fc.string().filter((theme) => !theme.includes('.')), defaultTheme: fc.string().filter((theme) => !theme.includes('.')), component: fc.string().filter((component) => component.length > 0 && !component.includes('.')) }).filter(({ currentTheme, defaultTheme }) => currentTheme !== defaultTheme).map(({ currentTheme, defaultTheme, component }) => ({ current: `${currentTheme}.${component}`, themeDefault: `${defaultTheme}.${component}` })), (value) => {
        expect(isThemeDefault(value.current, value.themeDefault)).toBe(false);
            })
        );
    });

    test('different_component_name', () => {
        fc.assert(
            fc.property(fc.record({ theme: fc.string().filter((theme) => !theme.includes('.')), currentComponent: fc.string().filter((component) => !component.includes('.')), defaultComponent: fc.string().filter((component) => !component.includes('.')) }).filter(({ currentComponent, defaultComponent }) => currentComponent !== defaultComponent).map(({ theme, currentComponent, defaultComponent }) => ({ current: `${theme}.${currentComponent}`, themeDefault: `${theme}.${defaultComponent}` })), (value) => {
        expect(isThemeDefault(value.current, value.themeDefault)).toBe(false);
            })
        );
    });

});

