// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import { create } from '@bufbuild/protobuf';
import * as fc from 'fast-check';

import { rotateHue } from '../src/delta/hue';

describe('testgen_delta__rotateHue', () => {
    function expectedRotateHue(color: string, degrees: number): string {
      const r = parseInt(color.slice(1, 3), 16) / 255;
      const g = parseInt(color.slice(3, 5), 16) / 255;
      const b = parseInt(color.slice(5, 7), 16) / 255;
      const max = Math.max(r, g, b);
      const min = Math.min(r, g, b);
      const lightness = (max + min) / 2;
      const difference = max - min;
      if (difference === 0) {
        const channel = Math.round(r * 255).toString(16).padStart(2, '0');
        return `#${channel}${channel}${channel}`;
      }
      const saturation = lightness > 0.5
        ? difference / (2 - max - min)
        : difference / (max + min);
      let hue: number;
      if (max === r) {
        hue = (g - b) / difference + (g < b ? 6 : 0);
      } else if (max === g) {
        hue = (b - r) / difference + 2;
      } else {
        hue = (r - g) / difference + 4;
      }
      hue = (hue * 60 + degrees) % 360;
      if (hue < 0) hue += 360;
      const q = lightness < 0.5
        ? lightness * (1 + saturation)
        : lightness + saturation - lightness * saturation;
      const p = 2 * lightness - q;
      const hueToRgb = (t: number): number => {
        let adjusted = t;
        if (adjusted < 0) adjusted += 1;
        if (adjusted > 1) adjusted -= 1;
        if (adjusted < 1 / 6) return p + (q - p) * 6 * adjusted;
        if (adjusted < 1 / 2) return q;
        if (adjusted < 2 / 3) return p + (q - p) * (2 / 3 - adjusted) * 6;
        return p;
      };
      const red = Math.round(hueToRgb(hue / 360 + 1 / 3) * 255).toString(16).padStart(2, '0');
      const green = Math.round(hueToRgb(hue / 360) * 255).toString(16).padStart(2, '0');
      const blue = Math.round(hueToRgb(hue / 360 - 1 / 3) * 255).toString(16).padStart(2, '0');
      return `#${red}${green}${blue}`;
    }

    test('accepted_saturated_color_rotation', () => {
        fc.assert(
            fc.property(fc.tuple(fc.integer({ min: 0, max: 255 }), fc.integer({ min: 0, max: 255 }), fc.integer({ min: 0, max: 255 }), fc.double({ noNaN: true, noDefaultInfinity: true })).map(([r, g, b, degrees]) => ({ color: `#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`, degrees })).filter(({ color }) => { const r = parseInt(color.slice(1, 3), 16); const g = parseInt(color.slice(3, 5), 16); const b = parseInt(color.slice(5, 7), 16); return Math.max(r, g, b) !== Math.min(r, g, b); }), (value) => {
        expect(rotateHue(value, degrees)).toBe(expectedRotateHue(value, degrees));
            })
        );
    });

    test('accepted_zero_degree_rotation', () => {
        fc.assert(
            fc.property(fc.tuple(fc.integer({ min: 0, max: 255 }), fc.integer({ min: 0, max: 255 }), fc.integer({ min: 0, max: 255 })).map(([r, g, b]) => `#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`), (value) => {
        expect(rotateHue(value, 0)).toBe(value.toLowerCase());
            })
        );
    });

    test('accepted_full_turn_rotation', () => {
        fc.assert(
            fc.property(fc.tuple(fc.tuple(fc.integer({ min: 0, max: 255 }), fc.integer({ min: 0, max: 255 }), fc.integer({ min: 0, max: 255 })).map(([r, g, b]) => `#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`), fc.integer({ min: -10000, max: 10000 }).map((turns) => turns * 360)), (value) => {
        expect(rotateHue(value[0], value[1])).toBe(value[0].toLowerCase());
            })
        );
    });

    test('negative_degree_modulo', () => {
        fc.assert(
            fc.property(fc.double({ min: -1000000, max: -Number.MIN_VALUE, noNaN: true, noDefaultInfinity: true }), (value) => {
        expect(rotateHue('#8ad1ff', value)).toBe(expectedRotateHue('#8ad1ff', value));
            })
        );
    });

    test('over_360_degree_modulo', () => {
        fc.assert(
            fc.property(fc.double({ min: 360 + Number.MIN_VALUE, max: 1000000, noNaN: true, noDefaultInfinity: true }), (value) => {
        expect(rotateHue('#8ad1ff', value)).toBe(expectedRotateHue('#8ad1ff', value));
            })
        );
    });

    test('uppercase_accepted_color', () => {
        fc.assert(
            fc.property(fc.tuple(fc.integer({ min: 0, max: 255 }), fc.integer({ min: 0, max: 255 }), fc.integer({ min: 0, max: 255 })).map(([r, g, b]) => `#${r.toString(16).padStart(2, '0')}${g.toString(16).padStart(2, '0')}${b.toString(16).padStart(2, '0')}`.toUpperCase()).filter((color) => /[A-F]/.test(color)), (value) => {
        expect(rotateHue(value, 0)).toBe(value.toLowerCase());
            })
        );
    });

    test('achromatic_color_identity', () => {
        fc.assert(
            fc.property(fc.tuple(fc.integer({ min: 0, max: 255 }).map((channel) => `#${channel.toString(16).padStart(2, '0')}${channel.toString(16).padStart(2, '0')}${channel.toString(16).padStart(2, '0')}`), fc.double({ noNaN: true, noDefaultInfinity: true })), (value) => {
        expect(rotateHue(value[0], value[1])).toBe(value[0].toLowerCase());
            })
        );
    });

    test('three_digit_hex_rejected', () => {
        fc.assert(
            fc.property(fc.constantFrom('#abc', '#ABC', '#123', '#aF0'), (value) => {
        expect(rotateHue(value, 180)).toBe(value);
            })
        );
    });

    test('named_color_rejected', () => {
        fc.assert(
            fc.property(fc.constantFrom('none', 'red', 'transparent', 'RebeccaPurple'), (value) => {
        expect(rotateHue(value, 180)).toBe(value);
            })
        );
    });

    test('unresolved_color_rejected', () => {
        fc.assert(
            fc.property(fc.constantFrom('$roles.node_fill', '$color.primary', '$theme.background'), (value) => {
        expect(rotateHue(value, 180)).toBe(value);
            })
        );
    });

    // WHEN: An empty string is rejected and returned byte for byte without parsing, transformation, or lowercasing.
    // THEN: Returns the empty string byte for byte without parsing, transformation, or lowercasing.
    test('empty_color_rejected', () => {
        expect(rotateHue('', 180)).toBe('');
    });

    test('other_invalid_color_rejected', () => {
        fc.assert(
            fc.property(fc.string().filter((color) => !/^#[0-9a-fA-F]{6}$/.test(color)), (value) => {
        expect(rotateHue(value, 37)).toBe(value);
            })
        );
    });

});

