// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import { create } from '@bufbuild/protobuf';
// Repaired by hand: the generated body used these schema descriptors
// without importing them. archetest.yaml now carries them in the core header.
import { Decoration, DecorationSchema, FillSchema, GlowSchema, Glyph2DSchema, GradientSchema, StrokeSchema } from '@archeglyph/proto/gen/style_pb';
import * as fc from 'fast-check';

import { DiffRoles } from '../src/delta/diff_roles';
import { recolorShape } from '../src/delta/recolor_shape';
import { ChangeType } from '../../proto/src/gen/content_pb';
import { StrokePattern } from '../../proto/src/gen/style_pb';

describe('testgen_delta__recolorShape', () => {
    const testDiffRoles = (): DiffRoles => Object.assign(new DiffRoles(), { added: '#00aa00', modified: '#0000aa', deleted: '#cc0000' });

    test('color_stroke_paint', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const glyph = create(Glyph2DSchema, { stroke: create(StrokeSchema, { paint: { case: 'color', value } }) });
        const result = recolorShape(glyph, ChangeType.ADDED, testDiffRoles());
        expect(result.stroke?.paint).toEqual({ case: 'color', value: '#00aa00' });
            })
        );
    });

    // WHEN: The glyph has a stroke whose paint is the GRADIENT case; the stroke, including its gradient data, is left unchanged and no color is derived.
    // THEN: Returns a copy leaving the gradient stroke and all its gradient data unchanged without deriving a color.
    test('gradient_stroke_paint', () => {
        const stroke = create(StrokeSchema, { paint: { case: 'gradient', value: create(GradientSchema, {}) } });
        const glyph = create(Glyph2DSchema, { stroke });
        const result = recolorShape(glyph, ChangeType.ADDED, testDiffRoles());
        expect(result.stroke).toEqual(stroke);
    });

    test('color_fill_paint', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const glyph = create(Glyph2DSchema, { fill: create(FillSchema, { paint: { case: 'color', value }) }) });
        const result = recolorShape(glyph, ChangeType.ADDED, testDiffRoles());
        expect(result.fill?.paint).toEqual({ case: 'color', value: '#00aa00' });
            })
        );
    });

    // WHEN: The glyph has a fill whose paint is the GRADIENT case; the fill, including its gradient data, is left unchanged and no color is derived.
    // THEN: Returns a copy leaving the gradient fill and all its gradient data unchanged without deriving a color.
    test('gradient_fill_paint', () => {
        const fill = create(FillSchema, { paint: { case: 'gradient', value: create(GradientSchema, {}) } });
        const glyph = create(Glyph2DSchema, { fill });
        const result = recolorShape(glyph, ChangeType.MODIFIED, testDiffRoles());
        expect(result.fill).toEqual(fill);
    });

    test('glow_color_set', () => {
        fc.assert(
            fc.property(fc.string(), (value) => {
        const glow = create(GlowSchema, { color: value });
        const glyph = create(Glyph2DSchema, { glow });
        const result = recolorShape(glyph, ChangeType.DELETED, testDiffRoles());
        expect(result.glow?.color).toBe('#cc0000');
            })
        );
    });

    test('decoration_colors_set', () => {
        fc.assert(
            fc.property(fc.array(fc.string()), (value) => {
        const glyph = create(Glyph2DSchema, { decorations: value.map((color: string) => create(DecorationSchema, { color })) });
        const result = recolorShape(glyph, ChangeType.ADDED, testDiffRoles());
        expect(result.decorations.map((decoration: Decoration) => decoration.color)).toEqual(value.map(() => '#00aa00'));
            })
        );
    });

    test('optional_colors_unset', () => {
        fc.assert(
            fc.property(fc.record({ stroke: fc.boolean(), fill: fc.boolean(), glow: fc.boolean(), decoration: fc.boolean() }), (value) => {
        const glyph = create(Glyph2DSchema, { stroke: value.stroke ? create(StrokeSchema, {}) : undefined, fill: value.fill ? create(FillSchema, {}) : undefined, glow: value.glow ? create(GlowSchema, {}) : undefined, decorations: value.decoration ? [create(DecorationSchema, {})] : [] });
        const result = recolorShape(glyph, ChangeType.MODIFIED, testDiffRoles());
        expect(result.stroke?.paint.case).toBe(undefined);
        expect(result.fill?.paint.case).toBe(undefined);
        expect(result.glow?.color).toBe(undefined);
        expect(result.decorations[0]?.color).toBe(undefined);
            })
        );
    });

    test('deleted_with_stroke', () => {
        fc.assert(
            fc.property(fc.constantFrom(StrokePattern.UNSPECIFIED, StrokePattern.SOLID, StrokePattern.DASHED, StrokePattern.DOTTED), (value) => {
        const glyph = create(Glyph2DSchema, { stroke: create(StrokeSchema, { dashing: value, width: 2.5, cap: 1, join: 2, paint: { case: 'color', value: '#123456' } }) });
        const result = recolorShape(glyph, ChangeType.DELETED, testDiffRoles());
        expect(result.stroke?.dashing).toBe(StrokePattern.DOTTED);
        expect(result.stroke?.width).toBe(2.5);
        expect(result.stroke?.cap).toBe(1);
        expect(result.stroke?.join).toBe(2);
            })
        );
    });

    // WHEN: change is DELETED and the glyph has no stroke; no stroke is created and therefore no dashing is added.
    // THEN: For DELETED, returns a copy without creating a stroke or adding dashing.
    test('deleted_without_stroke', () => {
        const glyph = create(Glyph2DSchema, {});
        const result = recolorShape(glyph, ChangeType.DELETED);
        expect(result.stroke).toBe(undefined);
    });

    test('deleted_fill_explicit_opacity', () => {
        fc.assert(
            fc.property(fc.double({ noNaN: true, noDefaultInfinity: true }), (value) => {
        const glyph = create(Glyph2DSchema, { fill: create(FillSchema, { opacity: value }) });
        const result = recolorShape(glyph, ChangeType.DELETED);
        expect(result.fill?.opacity).toBe(value * 0.4);
            })
        );
    });

    // WHEN: change is DELETED and the glyph has a fill whose opacity is unset; it is treated as 1.0 and the returned copy sets fill.opacity to 0.4.
    // THEN: For DELETED, treats the present fill's unset opacity as 1.0 and sets it to 0.4 in the copy.
    test('deleted_fill_unset_opacity', () => {
        const glyph = create(Glyph2DSchema, { fill: create(FillSchema, {}) });
        const result = recolorShape(glyph, ChangeType.DELETED);
        expect(result.fill?.opacity).toBe(0.4);
    });

    // WHEN: change is DELETED and the glyph has no fill; no fill is created and no opacity is set.
    // THEN: For DELETED, returns a copy without creating a fill or setting opacity.
    test('deleted_without_fill', () => {
        const glyph = create(Glyph2DSchema, {});
        const result = recolorShape(glyph, ChangeType.DELETED);
        expect(result.fill).toBe(undefined);
    });

    test('nondeleted_preserves_ghosting_fields', () => {
        fc.assert(
            fc.property(fc.record({ change: fc.constantFrom(ChangeType.CHANGE_TYPE_UNSPECIFIED, ChangeType.UNCHANGED, ChangeType.ADDED, ChangeType.MODIFIED), stroke: fc.boolean(), fill: fc.boolean() }), (value) => {
        const glyph = create(Glyph2DSchema, { stroke: value.stroke ? create(StrokeSchema, { dashing: StrokePattern.DASHED }) : undefined, fill: value.fill ? create(FillSchema, { opacity: 0.25 }) : undefined });
        const result = recolorShape(glyph, value.change);
        expect(result.stroke?.dashing).toBe(value.stroke ? StrokePattern.DASHED : undefined);
        expect(result.fill?.opacity).toBe(value.fill ? 0.25 : undefined);
            })
        );
    });

    test('copy_preserves_geometry_and_style', () => {
        fc.assert(
            fc.property(fc.record({ change: fc.constantFrom(ChangeType.CHANGE_TYPE_UNSPECIFIED, ChangeType.UNCHANGED, ChangeType.ADDED, ChangeType.DELETED, ChangeType.MODIFIED), path: fc.string() }), (value) => {
        const glyph = create(Glyph2DSchema, { shapeKind: { case: 'customPathRef', value }, cornerRadius: 7, stroke: create(StrokeSchema, { width: 3, cap: 1, join: 2, dashing: StrokePattern.DASHED }), glow: create(GlowSchema, { radius: 4, intensity: 0.7 }), decorations: [create(DecorationSchema, { id: 'd1', kind: 1, badgeText: 'badge', iconRef: 'icon', position: { x: 2, y: 3 } })] });
        const before = create(Glyph2DSchema, { shapeKind: { case: 'customPathRef', value }, cornerRadius: 7, stroke: create(StrokeSchema, { width: 3, cap: 1, join: 2, dashing: StrokePattern.DASHED }), glow: create(GlowSchema, { radius: 4, intensity: 0.7 }), decorations: [create(DecorationSchema, { id: 'd1', kind: 1, badgeText: 'badge', iconRef: 'icon', position: { x: 2, y: 3 } })] });
        const result = recolorShape(glyph, value.change, testDiffRoles());
        expect(result.shapeKind).toEqual(glyph.shapeKind);
        expect(result.cornerRadius).toBe(7);
        expect(result.stroke?.width).toBe(3);
        expect(result.stroke?.cap).toBe(1);
        expect(result.stroke?.join).toBe(2);
        expect(result.glow?.radius).toBe(4);
        expect(result.glow?.intensity).toBe(0.7);
        expect(result.decorations[0]).toEqual(glyph.decorations[0]);
        expect(glyph).toEqual(before);
            })
        );
    });

});

