// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import * as fc from 'fast-check';

import { deriveComponent } from '../src/resolver/seed_bindings/derive';

describe('testgen_seed_bindings__deriveComponent', () => {
    test('missing_theme_default', () => {
        fc.assert(
            fc.property(fc.constantFrom<string | undefined>(undefined, ""), (value) => {
        expect(deriveComponent("store", ["store"], value)).toBeUndefined();
            })
        );
    });

    test('exact_component_kind', () => {
        fc.assert(
            fc.property(fc.string({ minLength: 1 }), (value) => {
        expect(deriveComponent(value, [value], "fallback")).toBe(value);
            })
        );
    });

    // WHEN: themeDefault is non-empty and kind is undefined. With no exact kind to select, the function returns themeDefault.
    // THEN: It returns themeDefault when kind is undefined.
    test('undefined_kind_falls_back', () => {
        expect(deriveComponent(undefined, ["store"], "fallback")).toBe("fallback");
    });

    // WHEN: themeDefault is non-empty and kind is the empty string. The function returns themeDefault.
    // THEN: It returns themeDefault when kind is the empty string.
    test('empty_kind_falls_back', () => {
        expect(deriveComponent("", ["store"], "fallback")).toBe("fallback");
    });

    test('qualified_kind_does_not_match', () => {
        fc.assert(
            fc.property(fc.string({ minLength: 1 }).map((name) => `default.${name}`), (value) => {
        const unqualified = value.slice("default.".length);
        expect(deriveComponent(value, [unqualified], "fallback")).toBe("fallback");
            })
        );
    });

    test('other_unmatched_kind_falls_back', () => {
        fc.assert(
            fc.property(fc.string({ minLength: 1 }), (value) => {
        expect(deriveComponent(value, [`${value}-other`], "fallback")).toBe("fallback");
            })
        );
    });

});

