// Generated by `archegraph testgen` — do not edit by hand.
// Re-run `archegraph testgen --spec <name>` to regenerate.

import { describe, expect, test } from 'bun:test';
import { create } from '@bufbuild/protobuf';
import {
  DiagramSchema, GraphSchema, NodeSchema, EdgeSchema, GroupSchema,
  DeltaSchema, NodeDeltaSchema, EdgeDeltaSchema, GroupDeltaSchema,
} from '@archeglyph/proto/gen/content_pb';
import {
  StylesheetSchema, StrokeSchema, FillSchema, GlowSchema, GradientSchema,
  Glyph1DSchema, Glyph2DSchema, DecorationSchema, TypographySchema,
  ArrowheadsSchema, CanvasStyleSchema,
} from '@archeglyph/proto/gen/style_pb';
import { TokensSchema, ThemeSchema } from '@archeglyph/proto/gen/theme_pb';
import * as fc from 'fast-check';

import { diffColorFor } from '../src/delta/diff_color';
import { DiffRoles } from '../src/delta/diff_roles';
import { recolorTypography } from '../src/delta/recolor_text';
import { ChangeType } from '../../proto/src/gen/content_pb';
import { Typography } from '../../proto/src/gen/style_pb';

describe('testgen_delta__recolorTypography', () => {
    function assertTypographyNonColorFields(actual: Typography, expected: Typography): void {
      expect(actual.font).toBe(expected.font);
      expect(actual.size).toBe(expected.size);
      expect(actual.weight).toBe(expected.weight);
      expect(actual.align).toBe(expected.align);
      expect(actual.visible).toBe(expected.visible);
    }

    test('both_colors_set', () => {
        fc.assert(
            fc.property(fc.record({ color: fc.string(), background: fc.string(), font: fc.option(fc.string(), { nil: undefined }), size: fc.integer(), visible: fc.option(fc.boolean(), { nil: undefined }) }).map(({ color, background, font, size, visible }) => create(TypographySchema, { color, background, font, size, visible })), (value) => {
        const originalColor = value.color;
        const originalBackground = value.background;
        const result = recolorTypography(value, ChangeType.MODIFIED);
        expect(result.color).toBe(diffColorFor(originalColor!, ChangeType.MODIFIED));
        expect(result.background).toBe(diffColorFor(originalBackground!, ChangeType.MODIFIED));
        assertTypographyNonColorFields(result, value);
        expect(value.color).toBe(originalColor);
        expect(value.background).toBe(originalBackground);
            })
        );
    });

    test('color_only', () => {
        fc.assert(
            fc.property(fc.record({ color: fc.string(), font: fc.option(fc.string(), { nil: undefined }), size: fc.integer(), visible: fc.option(fc.boolean(), { nil: undefined }) }).map(({ color, font, size, visible }) => create(TypographySchema, { color, font, size, visible })), (value) => {
        const originalColor = value.color;
        const result = recolorTypography(value, ChangeType.ADDED);
        expect(result.color).toBe(diffColorFor(originalColor!, ChangeType.ADDED));
        expect(result.background).toBeUndefined();
        assertTypographyNonColorFields(result, value);
        expect(value.color).toBe(originalColor);
        expect(value.background).toBeUndefined();
            })
        );
    });

    test('background_only', () => {
        fc.assert(
            fc.property(fc.record({ background: fc.string(), font: fc.option(fc.string(), { nil: undefined }), size: fc.integer(), visible: fc.option(fc.boolean(), { nil: undefined }) }).map(({ background, font, size, visible }) => create(TypographySchema, { background, font, size, visible })), (value) => {
        const originalBackground = value.background;
        const result = recolorTypography(value, ChangeType.MODIFIED);
        expect(result.color).toBeUndefined();
        expect(result.background).toBe(diffColorFor(originalBackground!, ChangeType.MODIFIED));
        assertTypographyNonColorFields(result, value);
        expect(value.color).toBeUndefined();
        expect(value.background).toBe(originalBackground);
            })
        );
    });

    test('no_colors_set', () => {
        fc.assert(
            fc.property(fc.record({ font: fc.option(fc.string(), { nil: undefined }), size: fc.integer(), visible: fc.option(fc.boolean(), { nil: undefined }) }).map(({ font, size, visible }) => create(TypographySchema, { font, size, visible })), (value) => {
        const result = recolorTypography(value, ChangeType.UNCHANGED);
        expect(result.color).toBeUndefined();
        expect(result.background).toBeUndefined();
        assertTypographyNonColorFields(result, value);
            })
        );
    });

    // WHEN: The change type is DELETED. Any present text colors are recolored in the same way as for other change types; the Typography receives no ghosting, including no special treatment of a deleted label.
    // THEN: For DELETED, recolors each present text color normally without applying any ghosting or special deleted-label treatment.
    test('deleted_change', () => {
        const typography = create(TypographySchema, { color: '#123456', background: '#abcdef', font: 'body', size: 14, visible: true });
        const result = recolorTypography(typography, ChangeType.DELETED);
        expect(result.color).toBe(diffColorFor('#123456', ChangeType.DELETED));
        expect(result.background).toBe(diffColorFor('#abcdef', ChangeType.DELETED));
        assertTypographyNonColorFields(result, typography);
        expect(typography.color).toBe('#123456');
        expect(typography.background).toBe('#abcdef');
    });

    test('non_deleted_change', () => {
        fc.assert(
            fc.property(fc.record({ change: fc.constantFrom(ChangeType.CHANGE_TYPE_UNSPECIFIED, ChangeType.UNCHANGED, ChangeType.ADDED, ChangeType.MODIFIED), typography: fc.record({ color: fc.option(fc.string(), { nil: undefined }), background: fc.option(fc.string(), { nil: undefined }), font: fc.option(fc.string(), { nil: undefined }), size: fc.integer(), visible: fc.option(fc.boolean(), { nil: undefined }) }).map(({ color, background, font, size, visible }) => create(TypographySchema, { color, background, font, size, visible })) }), (value) => {
        const result = recolorTypography(value.typography, value.change);
        if (value.typography.color !== undefined) {
          expect(result.color).toBe(diffColorFor(value.typography.color, value.change));
        } else {
          expect(result.color).toBeUndefined();
        }
        if (value.typography.background !== undefined) {
          expect(result.background).toBe(diffColorFor(value.typography.background, value.change));
        } else {
          expect(result.background).toBeUndefined();
        }
        assertTypographyNonColorFields(result, value.typography);
            })
        );
    });

    // WHEN: The optional diffRoles argument is omitted. The function invokes diffColorFor without caller-supplied diff roles while preserving the Typography fields and optional-color presence rules.
    // THEN: When diffRoles is omitted, calls diffColorFor without caller-supplied roles and preserves field values and optional-color presence.
    test('diff_roles_omitted', () => {
        const typography = create(TypographySchema, { color: '#123456', background: '#abcdef', font: 'body', size: 14, visible: true });
        const result = recolorTypography(typography, ChangeType.ADDED);
        expect(result.color).toBe(diffColorFor('#123456', ChangeType.ADDED));
        expect(result.background).toBe(diffColorFor('#abcdef', ChangeType.ADDED));
        assertTypographyNonColorFields(result, typography);
    });

    test('diff_roles_supplied', () => {
        fc.assert(
            fc.property(fc.record({ roles: fc.record({ added: fc.string(), modified: fc.string(), deleted: fc.string() }).map(({ added, modified, deleted }) => { const roles = new DiffRoles(); roles.added = added; roles.modified = modified; roles.deleted = deleted; return roles; }), typography: fc.record({ color: fc.option(fc.string(), { nil: undefined }), background: fc.option(fc.string(), { nil: undefined }), font: fc.option(fc.string(), { nil: undefined }), size: fc.integer(), visible: fc.option(fc.boolean(), { nil: undefined }) }).map(({ color, background, font, size, visible }) => create(TypographySchema, { color, background, font, size, visible })) }), (value) => {
        const result = recolorTypography(value.typography, ChangeType.ADDED, value.roles);
        expect(result.color).toBe(value.roles.added);
        expect(result.background).toBe(value.roles.added);
        assertTypographyNonColorFields(result, value.typography);
            })
        );
    });

});

