// @generated by archebuild — do not edit. Regenerated each build.

export function boundsIntersects(a: Bounds, b: Bounds): boolean {
  throw new Error('not implemented');
}
export function boundsFromRect(position: Vec2, size: Vec2): Bounds {
  const endX = position.x + size.x;
  const endY = position.y + size.y;
  return {
    minX: Math.min(position.x, endX),
    minY: Math.min(position.y, endY),
    maxX: Math.max(position.x, endX),
    maxY: Math.max(position.y, endY),
  };
}
export interface Bounds {
  minX: number;
  minY: number;
  maxX: number;
  maxY: number;
}
export function boundsContains(b: Bounds, p: Vec2): boolean {
  throw new Error('not implemented');
}
export function boundsUnion(a: Bounds, b: Bounds): Bounds {
  throw new Error('not implemented');
}
export function boundsCentre(b: Bounds): Vec2 {
  throw new Error('not implemented');
}
export function boundsProjectToEdge(b: Bounds, toward: Vec2): Vec2 {
  throw new Error('not implemented');
}
