// @generated by archebuild — do not edit. Regenerated each build.

import { create } from '@bufbuild/protobuf';
import { CascadeRequest } from '../cascade_request';
import { Err, Ok, Result } from '@archeglyph/proto/util/result';
import { FilteredAnnotation } from '../filtered_annotation';
import { FilteredDiagram } from '../filtered_diagram';
import { FilteredEdge } from '../filtered_edge';
import { FilteredGroup } from '../filtered_group';
import { FilteredNode } from '../filtered_node';
import {
  AnnotationEntry,
  EdgeStyleEntry,
  Fill,
  FillSchema,
  Glow,
  GlowSchema,
  Glyph1D,
  Glyph1DSchema,
  Glyph2D,
  Glyph2DSchema,
  GroupStyleEntry,
  NodeStyleEntry,
  Stroke,
  StrokeSchema,
  Stylesheet,
  Typography,
  TypographySchema,
} from '@archeglyph/proto/gen/style_pb';
import { AnnotationComponent, EdgeComponent, NodeComponent, Theme } from '@archeglyph/proto/gen/theme_pb';
import { ResolveError } from '../resolve_error';
import { ResolvedAnnotation } from '../resolved_annotation';
import { ResolvedDiagram } from '../resolved_diagram';
import { ResolvedEdge } from '../resolved_edge';
import { ResolvedGroup } from '../resolved_group';
import { ResolvedNode } from '../resolved_node';
import { StyleCascade } from './schema_gen';

function compareIds(a: string, b: string): number {
  if (a < b) { return -1; } else if (a > b) { return 1; } else { return 0; }
}

function mergeStroke(base: Stroke, layer: Stroke): void {
  if (layer.paint.case !== undefined) { base.paint = layer.paint; }
  if (layer.width !== undefined) { base.width = layer.width; }
  if (layer.dashing.case !== undefined) { base.dashing = layer.dashing; }
  if (layer.cap !== undefined) { base.cap = layer.cap; }
  if (layer.join !== undefined) { base.join = layer.join; }
}

function mergeFill(base: Fill, layer: Fill): void {
  if (layer.paint.case !== undefined) { base.paint = layer.paint; }
  if (layer.opacity !== undefined) { base.opacity = layer.opacity; }
}

function mergeGlow(base: Glow, layer: Glow): void {
  if (layer.color !== undefined) { base.color = layer.color; }
  if (layer.radius !== undefined) { base.radius = layer.radius; }
  if (layer.intensity !== undefined) { base.intensity = layer.intensity; }
}

function mergeGlyph2D(base: Glyph2D, layer: Glyph2D): void {
  if (layer.shapeKind.case !== undefined) { base.shapeKind = layer.shapeKind; }
  if (layer.cornerRadius !== undefined) { base.cornerRadius = layer.cornerRadius; }
  if (layer.stroke !== undefined) {
    if (base.stroke === undefined) { base.stroke = create(StrokeSchema); }
    mergeStroke(base.stroke, layer.stroke);
  }
  if (layer.fill !== undefined) {
    if (base.fill === undefined) { base.fill = create(FillSchema); }
    mergeFill(base.fill, layer.fill);
  }
  if (layer.glow !== undefined) {
    if (base.glow === undefined) { base.glow = create(GlowSchema); }
    mergeGlow(base.glow, layer.glow);
  }
  if (layer.decorations.length > 0) { base.decorations = layer.decorations.slice(); }
}

function mergeGlyph1D(base: Glyph1D, layer: Glyph1D): void {
  if (layer.stroke !== undefined) {
    if (base.stroke === undefined) { base.stroke = create(StrokeSchema); }
    mergeStroke(base.stroke, layer.stroke);
  }
  if (layer.arrowheads !== undefined) { base.arrowheads = layer.arrowheads; }
  if (layer.glow !== undefined) {
    if (base.glow === undefined) { base.glow = create(GlowSchema); }
    mergeGlow(base.glow, layer.glow);
  }
}

function mergeTypography(base: Typography, layer: Typography): void {
  if (layer.font !== undefined) { base.font = layer.font; }
  if (layer.color !== undefined) { base.color = layer.color; }
  if (layer.size !== undefined) { base.size = layer.size; }
  if (layer.weight !== undefined) { base.weight = layer.weight; }
  if (layer.align !== undefined) { base.align = layer.align; }
  if (layer.visible !== undefined) { base.visible = layer.visible; }
  if (layer.background !== undefined) { base.background = layer.background; }
}

function findNodeComponent(theme: Theme | undefined, name: string): NodeComponent | undefined {
  if (theme === undefined) {
    return undefined;
  } else {
    return theme.nodeComponents.find((c: NodeComponent): boolean => c.name === name);
  }
}

function findEdgeComponent(theme: Theme | undefined, name: string): EdgeComponent | undefined {
  if (theme === undefined) {
    return undefined;
  } else {
    return theme.edgeComponents.find((c: EdgeComponent): boolean => c.name === name);
  }
}

function findGroupComponent(theme: Theme | undefined, name: string): NodeComponent | undefined {
  if (theme === undefined) {
    return undefined;
  } else {
    return theme.groupComponents.find((c: NodeComponent): boolean => c.name === name);
  }
}

function findAnnotationComponent(theme: Theme | undefined, name: string): AnnotationComponent | undefined {
  if (theme === undefined) {
    return undefined;
  } else {
    return theme.annotationComponents.find((c: AnnotationComponent): boolean => c.name === name);
  }
}

export class StyleCascadeImpl implements StyleCascade {
  cascade(request: CascadeRequest): Result<ResolvedDiagram, ResolveError> {
    const filtered: FilteredDiagram = request.filtered;
    const stylesheet: Stylesheet | undefined = request.stylesheet;
    const theme: Theme | undefined = request.theme;

    const result: ResolvedDiagram = new ResolvedDiagram();
    result.id = filtered.id;

    const sortedNodes: FilteredNode[] = filtered.nodes.slice();
    sortedNodes.sort((a: FilteredNode, b: FilteredNode): number => compareIds(a.id, b.id));
    for (const node of sortedNodes) {
      const entry: NodeStyleEntry | undefined = stylesheet?.nodes[node.id];
      const componentName: string = entry?.component ?? '';
      const themeComponent: NodeComponent | undefined =
        componentName === '' ? undefined : findNodeComponent(theme, componentName);
      if (componentName !== '' && themeComponent === undefined) {
        const err: ResolveError = new ResolveError();
        err.message = `node ${node.id}: theme component '${componentName}' not found`;
        return Err(err);
      }
      const shape: Glyph2D = create(Glyph2DSchema);
      if (themeComponent?.shape !== undefined) { mergeGlyph2D(shape, themeComponent.shape); }
      if (entry?.shape !== undefined) { mergeGlyph2D(shape, entry.shape); }
      const typography: Typography = create(TypographySchema);
      if (themeComponent?.typography !== undefined) { mergeTypography(typography, themeComponent.typography); }
      if (entry?.typography !== undefined) { mergeTypography(typography, entry.typography); }
      const resolved: ResolvedNode = new ResolvedNode();
      resolved.id = node.id;
      resolved.parentGroup = node.parentGroup;
      resolved.shape = shape;
      resolved.typography = typography;
      resolved.layout = entry?.layout;
      resolved.label = node.label;
      result.nodes.push(resolved);
    }

    const sortedEdges: FilteredEdge[] = filtered.edges.slice();
    sortedEdges.sort((a: FilteredEdge, b: FilteredEdge): number => compareIds(a.id, b.id));
    for (const edge of sortedEdges) {
      const entry: EdgeStyleEntry | undefined = stylesheet?.edges[edge.id];
      const componentName: string = entry?.component ?? '';
      const themeComponent: EdgeComponent | undefined =
        componentName === '' ? undefined : findEdgeComponent(theme, componentName);
      if (componentName !== '' && themeComponent === undefined) {
        const err: ResolveError = new ResolveError();
        err.message = `edge ${edge.id}: theme component '${componentName}' not found`;
        return Err(err);
      }
      const connection: Glyph1D = create(Glyph1DSchema);
      if (themeComponent?.connection !== undefined) { mergeGlyph1D(connection, themeComponent.connection); }
      if (entry?.connection !== undefined) { mergeGlyph1D(connection, entry.connection); }
      const typography: Typography = create(TypographySchema);
      if (themeComponent?.typography !== undefined) { mergeTypography(typography, themeComponent.typography); }
      if (entry?.typography !== undefined) { mergeTypography(typography, entry.typography); }
      const resolved: ResolvedEdge = new ResolvedEdge();
      resolved.id = edge.id;
      resolved.source = edge.source;
      resolved.target = edge.target;
      resolved.connection = connection;
      resolved.typography = typography;
      resolved.layout = entry?.layout;
      resolved.label = edge.label;
      result.edges.push(resolved);
    }

    const sortedGroups: FilteredGroup[] = filtered.groups.slice();
    sortedGroups.sort((a: FilteredGroup, b: FilteredGroup): number => compareIds(a.id, b.id));
    for (const group of sortedGroups) {
      const entry: GroupStyleEntry | undefined = stylesheet?.groups[group.id];
      const componentName: string = entry?.component ?? '';
      const themeComponent: NodeComponent | undefined =
        componentName === '' ? undefined : findGroupComponent(theme, componentName);
      if (componentName !== '' && themeComponent === undefined) {
        const err: ResolveError = new ResolveError();
        err.message = `group ${group.id}: theme component '${componentName}' not found`;
        return Err(err);
      }
      const shape: Glyph2D = create(Glyph2DSchema);
      if (themeComponent?.shape !== undefined) { mergeGlyph2D(shape, themeComponent.shape); }
      if (entry?.shape !== undefined) { mergeGlyph2D(shape, entry.shape); }
      const typography: Typography = create(TypographySchema);
      if (themeComponent?.typography !== undefined) { mergeTypography(typography, themeComponent.typography); }
      if (entry?.typography !== undefined) { mergeTypography(typography, entry.typography); }
      const resolved: ResolvedGroup = new ResolvedGroup();
      resolved.id = group.id;
      resolved.parentGroup = group.parentGroup;
      resolved.shape = shape;
      resolved.typography = typography;
      resolved.layout = entry?.layout;
      resolved.label = group.label;
      resolved.isSuperNode = group.isSuperNode;
      resolved.hiddenDescendantCount = group.hiddenDescendantCount;
      result.groups.push(resolved);
    }

    const sortedAnnotations: FilteredAnnotation[] = filtered.annotations.slice();
    sortedAnnotations.sort((a: FilteredAnnotation, b: FilteredAnnotation): number => compareIds(a.id, b.id));
    for (const annotation of sortedAnnotations) {
      const entry: AnnotationEntry = annotation.entry;
      const componentName: string = entry.component ?? '';
      const themeComponent: AnnotationComponent | undefined =
        componentName === '' ? undefined : findAnnotationComponent(theme, componentName);
      if (componentName !== '' && themeComponent === undefined) {
        const err: ResolveError = new ResolveError();
        err.message = `annotation ${annotation.id}: theme component '${componentName}' not found`;
        return Err(err);
      }
      const shape: Glyph2D = create(Glyph2DSchema);
      if (themeComponent?.shape !== undefined) { mergeGlyph2D(shape, themeComponent.shape); }
      if (entry.shape !== undefined) { mergeGlyph2D(shape, entry.shape); }
      const typography: Typography = create(TypographySchema);
      if (themeComponent?.typography !== undefined) { mergeTypography(typography, themeComponent.typography); }
      if (entry.typography !== undefined) { mergeTypography(typography, entry.typography); }
      const callout: Glyph1D = create(Glyph1DSchema);
      if (entry.anchor !== undefined) {
        if (themeComponent?.callout !== undefined) { mergeGlyph1D(callout, themeComponent.callout); }
        if (entry.callout !== undefined) { mergeGlyph1D(callout, entry.callout); }
      }
      const resolved: ResolvedAnnotation = new ResolvedAnnotation();
      resolved.id = annotation.id;
      resolved.shape = shape;
      resolved.typography = typography;
      resolved.callout = callout;
      resolved.layout = entry.layout;
      result.annotations.push(resolved);
    }

    return Ok(result);
  }
}
