// @generated by archebuild — do not edit. Regenerated each build.
import { extname, basename, dirname, join } from 'node:path';

export function deriveOutPath(diagramPath: string): string {
  const ext = extname(diagramPath);
  const base = ext
    ? basename(diagramPath, ext) + '.svg'
    : basename(diagramPath) + '.svg';
  const dir = dirname(diagramPath);
  return dir === '.' ? base : join(dir, base);
}
export function defaultTheme(): Theme {
  throw new Error('not implemented');
}
export function renderOp(): unknown {
  throw new Error('not implemented');
}
