// @generated by archebuild — do not edit. Regenerated each build.

export function deriveOutPath(diagramPath: string): string {
  throw new Error('not implemented');
}
export function defaultTheme(): Theme {
  throw new Error('not implemented');
}
export function renderOp(): unknown {
  throw new Error('not implemented');
}
