// @generated by archebuild — do not edit. Regenerated each build.

import { splitQualified } from '../style_cascade/impl';

export function deriveComponent(kind: string | undefined, componentNames: Array<string>, themeDefault: string | undefined): string | undefined {
  if (themeDefault === undefined || themeDefault === '') {
    return undefined;
  }
  if (kind !== undefined && kind !== '' && componentNames.includes(kind)) {
    return kind;
  }
  return themeDefault;
}
export function isThemeDefault(current: string | undefined, themeDefault: string): boolean {
  if (current === undefined || current === '') {
    return true;
  }

  const currentQualified = splitQualified(current);
  const defaultQualified = splitQualified(themeDefault);
  return currentQualified.theme === defaultQualified.theme
    && currentQualified.component === defaultQualified.component;
}
