// SPDX-License-Identifier: MPL-2.0

// @generated by archebuild — do not edit. Regenerated each build.

import { StyleEdit, Stylesheet } from '@archeglyph/proto/gen/style_pb';
import { anchorForElement, setAnnotationAnchorEdit } from '../state/edits/annotation';
import { boundsCentre } from '@archeglyph/core/geometry/bounds';
import { resolveAttachPoint } from '@archeglyph/core/layout/edge_router';
import type { Vec2 } from '@archeglyph/core/geometry/vec2';
import type { ElementRef } from '../ui_state/ui_state';
import { elementKey } from '../scene/element_key';
import type { SceneGeometry } from '../scene/scene';

export function anchorCommit(session: AnchorSession, stylesheet: Stylesheet, hit?: ElementRef): StyleEdit {
  const anchor = hit === undefined || hit.kind === 'annotation'
    ? undefined
    : anchorForElement(hit);
  return setAnnotationAnchorEdit(stylesheet, session.ref.id, anchor);
}

export class AnchorSession {
  ref!: ElementRef;
}
export function anchorUpdate(session: AnchorSession, geometry: SceneGeometry, pointer: Vec2, hit?: ElementRef): Array<Vec2> {
  const annotation = geometry.byKey[elementKey(session.ref)];
  if (annotation === undefined) {
    return [];
  }

  const annotationCentre = boundsCentre(annotation.bounds);
  if (hit === undefined || hit.kind === 'annotation') {
    return [resolveAttachPoint(annotation.bounds, pointer), pointer];
  }

  const target = geometry.byKey[elementKey(hit)];
  if (target === undefined) {
    return [resolveAttachPoint(annotation.bounds, pointer), pointer];
  }

  const targetCentre = boundsCentre(target.bounds);
  return [
    resolveAttachPoint(annotation.bounds, targetCentre),
    resolveAttachPoint(target.bounds, annotationCentre),
  ];
}
