// @generated by archebuild — do not edit. Regenerated each build.

import type { Stylesheet, StyleEdit } from '@archeglyph/proto/gen/style_pb';
import type { Vec2 } from '@archeglyph/core/geometry/vec2';
import { moveElementsEdit } from '../state/edits/move';
import type { ElementMove } from '../state/edits/move';
import { elementKey } from '../scene/element_key';
import type { SceneGeometry } from '../scene/scene';
import type { ScenePreview } from '../scene/preview';
import type { ElementRef, Viewport } from '../ui_state/ui_state';
import type { Bounds } from '@archeglyph/core/geometry/bounds';

export function moveCommit(session: MoveSession, geometry: SceneGeometry, stylesheet: Stylesheet, current: Vec2, zoom: number): StyleEdit | undefined {
  const delta = {
    x: (current.x - session.origin.x) / zoom,
    y: (current.y - session.origin.y) / zoom,
  };
  if (delta.x === 0 && delta.y === 0) {
    return undefined;
  }

  const moves: Array<ElementMove> = [];
  const requested = new Set(session.refs.map(elementKey));

  const parentIsMoving = (groupId: string): boolean => {
    let group: string | undefined = groupId;
    const visited = new Set<string>();
    while (group !== undefined && !visited.has(group)) {
      visited.add(group);
      if (requested.has(elementKey({ kind: 'group', id: group }))) {
        return true;
      }
      group = geometry.byKey[elementKey({ kind: 'group', id: group })]?.parentGroup;
    }
    return false;
  };

  for (const ref of session.refs) {
    // Routes are derived from their endpoints and are never persisted as
    // part of a move edit.
    if (ref.kind === 'edge') {
      continue;
    }
    const bounds = geometry.byKey[elementKey(ref)];
    if (bounds === undefined) {
      continue;
    }

    // Layout bounds are canvas-absolute, while style positions are relative
    // to the immediate parent group.  Convert back to that coordinate space
    // before constructing the edit.
    const parent = bounds.parentGroup === undefined
      ? undefined
      : geometry.byKey[elementKey({ kind: 'group', id: bounds.parentGroup })];
    const parentDelta = bounds.parentGroup !== undefined && parentIsMoving(bounds.parentGroup)
      ? delta
      : { x: 0, y: 0 };
    moves.push({
      kind: ref.kind,
      id: ref.id,
      position: {
        x: bounds.bounds.minX + delta.x - (parent?.bounds.minX ?? 0) - parentDelta.x,
        y: bounds.bounds.minY + delta.y - (parent?.bounds.minY ?? 0) - parentDelta.y,
      },
    });
  }

  return moves.length === 0 ? undefined : moveElementsEdit(stylesheet, moves);
}
export function moveUpdate(session: MoveSession, geometry: SceneGeometry, current: Vec2, zoom: number): ScenePreview {
  throw new Error('not implemented');
}
export function marqueeUpdate(session: MarqueeSession, current: Vec2): Bounds {
  throw new Error('not implemented');
}
export function marqueeCommit(geometry: SceneGeometry, marquee: Bounds): Array<ElementRef> {
  throw new Error('not implemented');
}
export interface PanSession {
  origin: Vec2;
  viewport: Viewport;
}
export interface MoveSession {
  refs: Array<ElementRef>;
  origin: Vec2;
}
export interface MarqueeSession {
  origin: Vec2;
}
export function panUpdate(session: PanSession, current: Vec2): Viewport {
  throw new Error('not implemented');
}
