// SPDX-License-Identifier: AGPL-3.0-or-later

// @generated by archebuild — do not edit. Regenerated each build.

import { runCommand, type CommandContext } from './commands';
import { commitModalGesture } from './modal_apply';
import { resolveChord } from '../ui_state/keymap';
import { modalKeyDown, type ModalStep } from '../ui_state/modal_step';
import type { ModalGesture } from '../ui_state/modal_gesture';

type ContentEditableValue = string | boolean;

type TextEntryTarget = EventTarget & {
  readonly tagName?: string;
  readonly isContentEditable?: boolean;
  readonly contentEditable?: ContentEditableValue;
  readonly getAttribute?: (name: string) => string | null;
};

export function shouldIgnoreKey(target: EventTarget | null): boolean {
  if (target === null) {
    return false;
  }

  const element = target as TextEntryTarget;
  const tagName = element.tagName?.toLowerCase();
  if (tagName === 'input' || tagName === 'textarea') {
    return true;
  }

  if (element.isContentEditable === true) {
    return true;
  }

  if (element.contentEditable === true) {
    return true;
  }

  const contentEditable =
    typeof element.contentEditable === 'string' ? element.contentEditable.toLowerCase() : undefined;
  if (contentEditable === 'true' || contentEditable === 'plaintext-only') {
    return true;
  }

  const contentEditableAttribute = element.getAttribute?.('contenteditable')?.toLowerCase();
  return (
    contentEditableAttribute === '' ||
    contentEditableAttribute === 'true' ||
    contentEditableAttribute === 'plaintext-only'
  );
}
export function handleKeyDown(event: KeyboardEvent, context: CommandContext): boolean {
  if (shouldIgnoreKey(event.target)) {
    return false;
  }

  const gesture: ModalGesture | undefined = context.ui.modalGesture();
  if (gesture !== undefined) {
    const step: ModalStep = modalKeyDown(gesture, event.key);
    if (step.outcome === 'continue') {
      context.ui.setModalGesture(step.gesture);
      return true;
    }
    if (step.outcome === 'commit') {
      commitModalGesture(gesture, context);
      context.ui.setModalGesture(undefined);
      return true;
    }
    if (step.outcome === 'cancel') {
      context.ui.setModalGesture(undefined);
      return true;
    }
  }

  const command = resolveChord({
    key: event.key,
    metaKey: event.metaKey,
    ctrlKey: event.ctrlKey,
    shiftKey: event.shiftKey,
  });
  if (command === undefined) {
    return false;
  }

  runCommand(command, context);
  return true;
}
