// @generated by archebuild — do not edit. Regenerated each build.

export function modalDelta(gesture: ModalGesture): Vec2 {
  throw new Error('not implemented');
}
export function modalHandle(gesture: ModalGesture): Handle | undefined {
  throw new Error('not implemented');
}
