// @generated by archebuild — do not edit. Regenerated each build.

import { ElementRef } from '../element_ref';
import { Handle } from '../handle';
import { Tool } from '../tool';
import { Vec2 } from '../vec2';

export interface PressContext {
  point: Vec2;
  hit?: ElementRef;
  tool: Tool;
  button: number;
  additive: boolean;
  onHandle?: Handle;
}
export function routePress(context: PressContext, current: Array<ElementRef>): GestureDecision {
  throw new Error('not implemented');
}
import { ElementRef } from '../element_ref';
import { Handle } from '../handle';

export interface GestureDecision {
  kind: 'pan' | 'move' | 'marquee' | 'resize' | 'none';
  selection?: Array<ElementRef>;
  handle?: Handle;
}
export function exceedsThreshold(origin: Vec2, current: Vec2): boolean {
  const dx = current.x - origin.x;
  const dy = current.y - origin.y;
  const threshold = 3;

  // Pointer coordinates are screen coordinates.  Do not apply the diagram's
  // zoom here: a physical pointer wobble is independent of diagram scale.
  return dx * dx + dy * dy >= threshold * threshold;
}
