// @generated by archebuild — do not edit. Regenerated each build.

export const MAX_ZOOM: number = 8;

export function applyWheel(viewport: Viewport, rect: ContainerRect, input: WheelInput): Viewport {
  throw new Error('not implemented');
}
export function isTrackpadScroll(input: WheelInput): boolean {
  throw new Error('not implemented');
}
import { Vec2 } from '../vec2';

export interface WheelInput {
  deltaX: number;
  deltaY: number;
  deltaMode: number;
  ctrlKey: boolean;
  point: Vec2;
}
