// SPDX-License-Identifier: MPL-2.0

// @generated by archebuild — do not edit. Regenerated each build.

import type { OpErrorCause } from '../op';

export class WatchOpError extends Error {
  stage!: string;
  cause!: OpErrorCause;
}
