// SPDX-License-Identifier: MPL-2.0

// @generated by archebuild — do not edit. Regenerated each build.

export function modalKeyDown(gesture: ModalGesture, key: string): ModalStep {
  switch (key) {
    case 'ArrowUp':
      return { outcome: 'continue', gesture: { ...gesture, direction: 'up' } };
    case 'ArrowDown':
      return { outcome: 'continue', gesture: { ...gesture, direction: 'down' } };
    case 'ArrowLeft':
      return { outcome: 'continue', gesture: { ...gesture, direction: 'left' } };
    case 'ArrowRight':
      return { outcome: 'continue', gesture: { ...gesture, direction: 'right' } };
    case 'Backspace':
      if (gesture.digits.length === 0) {
        return { outcome: 'continue', gesture };
      }
      return {
        outcome: 'continue',
        gesture: { ...gesture, digits: gesture.digits.slice(0, -1) },
      };
    case 'Enter':
      return { outcome: 'commit' };
    case 'Escape':
      return { outcome: 'cancel' };
    default:
      if (!/^[0-9]$/.test(key)) {
        return { outcome: 'ignore' };
      }
      if (gesture.digits.length >= 6) {
        return { outcome: 'continue', gesture };
      }
      return {
        outcome: 'continue',
        gesture: { ...gesture, digits: gesture.digits + key },
      };
  }
}
import { ModalGesture } from './modal_gesture';

export interface ModalStep {
  outcome: 'continue' | 'commit' | 'cancel' | 'ignore';
  gesture?: ModalGesture;
}
