// @generated by archebuild — do not edit. Regenerated each build.

import { ElementRef } from '../element_ref';

export interface ModalGesture {
  kind: 'grab' | 'resize';
  refs: Array<ElementRef>;
  direction?: 'up' | 'down' | 'left' | 'right';
  digits: string;
}
export function beginModalGesture(kind: 'grab' | 'resize', refs: Array<ElementRef>): ModalGesture {
  throw new Error('not implemented');
}
