// SPDX-License-Identifier: AGPL-3.0-or-later

// @generated by archebuild — do not edit. Regenerated each build.

import type { ElementRef } from './ui_state';

export interface ModalGesture {
  kind: 'grab' | 'resize';
  refs: Array<ElementRef>;
  direction?: 'up' | 'down' | 'left' | 'right';
  digits: string;
}
export function beginModalGesture(kind: 'grab' | 'resize', refs: Array<ElementRef>): ModalGesture {
  return {
    kind,
    refs,
    digits: '',
  };
}
