// @generated by archebuild — do not edit. Regenerated each build.

export function followEdge(edges: { id: string; source: string; target: string }[], fromId: string, direction: 'forward' | 'backward'): string[] {
  return edges
    .filter((edge) => direction === 'forward' ? edge.source === fromId : edge.target === fromId)
    .map((edge) => direction === 'forward' ? edge.target : edge.source);
}
export function prevInDocumentOrder(elements: NavigableElement[], current?: ElementRef): ElementRef | undefined {
  if (elements.length === 0) {
    return undefined;
  }

  const currentIndex = current === undefined
    ? -1
    : elements.findIndex((element) => (
      element.ref.id === current.id && element.ref.kind === current.kind
    ));
  const previousIndex = currentIndex <= 0 ? elements.length - 1 : currentIndex - 1;

  return elements[previousIndex].ref;
}
export function nextInDocumentOrder(elements: NavigableElement[], current?: ElementRef): ElementRef | undefined {
  if (elements.length === 0) {
    return undefined;
  }

  const currentIndex = current === undefined
    ? -1
    : elements.findIndex((element) => element.ref.id === current.id && element.ref.kind === current.kind);
  const nextIndex = (currentIndex + 1) % elements.length;
  return elements[nextIndex].ref;
}
export function nearestInDirection(elements: NavigableElement[], from: NavigableElement, direction: Vec2, halfAngleRad: number): ElementRef | undefined {
  throw new Error('not implemented');
}
import { ElementRef } from './ui_state';
import { Vec2 } from '../vec2';

export interface NavigableElement {
  ref: ElementRef;
  centre: Vec2;
}
