// @generated by archebuild — do not edit. Regenerated each build.

export function followEdge(edges: { id: string; source: string; target: string }[], fromId: string, direction: 'forward' | 'backward'): string[] {
  throw new Error('not implemented');
}
export function prevInDocumentOrder(elements: NavigableElement[], current?: ElementRef): ElementRef | undefined {
  throw new Error('not implemented');
}
export function nextInDocumentOrder(elements: NavigableElement[], current?: ElementRef): ElementRef | undefined {
  throw new Error('not implemented');
}
export function nearestInDirection(elements: NavigableElement[], from: NavigableElement, direction: Vec2, halfAngleRad: number): ElementRef | undefined {
  let nearest: NavigableElement | undefined;
  let nearestDistance = Infinity;

  for (const element of elements) {
    if (element.ref.id === from.ref.id && element.ref.kind === from.ref.kind) {
      continue;
    }
    if (!isWithinCone(from.centre, direction, element.centre, halfAngleRad)) {
      continue;
    }

    const candidateDistance = distance(from.centre, element.centre);
    if (candidateDistance < nearestDistance) {
      nearest = element;
      nearestDistance = candidateDistance;
    }
  }

  return nearest?.ref;
}
import { ElementRef } from './ui_state';
import { isWithinCone } from '@archeglyph/core/geometry/direction';
import { distance, Vec2 } from '@archeglyph/core/geometry/vec2';

export interface NavigableElement {
  ref: ElementRef;
  centre: Vec2;
}

