// @generated by archebuild — do not edit. Regenerated each build.

export function followEdge(edges: { id: string; source: string; target: string }[], fromId: string, direction: 'forward' | 'backward'): string[] {
  return edges
    .filter((edge) => direction === 'forward' ? edge.source === fromId : edge.target === fromId)
    .map((edge) => direction === 'forward' ? edge.target : edge.source);
}
export function prevInDocumentOrder(elements: NavigableElement[], current?: ElementRef): ElementRef | undefined {
  throw new Error('not implemented');
}
export function nextInDocumentOrder(elements: NavigableElement[], current?: ElementRef): ElementRef | undefined {
  throw new Error('not implemented');
}
export function nearestInDirection(elements: NavigableElement[], from: NavigableElement, direction: Vec2, halfAngleRad: number): ElementRef | undefined {
  throw new Error('not implemented');
}
import { ElementRef } from './ui_state';
import { Vec2 } from '../vec2';

export interface NavigableElement {
  ref: ElementRef;
  centre: Vec2;
}
