// @generated by archebuild — do not edit. Regenerated each build.

export function toggleSelection(current: ElementRef[], ref: ElementRef): ElementRef[] {
  const index = current.findIndex(
    (candidate) => candidate.id === ref.id && candidate.kind === ref.kind,
  );
  if (index >= 0) {
    return [...current.slice(0, index), ...current.slice(index + 1)];
  }
  return [...current, ref];
}
export function addAllSelection(current: ElementRef[], refs: ElementRef[]): ElementRef[] {
  const result: ElementRef[] = [];
  const seen = new Set<string>();

  for (const ref of current) {
    const key = `${ref.id}\u0000${ref.kind}`;
    if (!seen.has(key)) {
      seen.add(key);
      result.push(ref);
    }
  }

  for (const ref of refs) {
    const key = `${ref.id}\u0000${ref.kind}`;
    if (!seen.has(key)) {
      seen.add(key);
      result.push(ref);
    }
  }

  return result;
}
export function clearSelection(): ElementRef[] {
  return [];
}
export function selectInRect(candidates: { ref: ElementRef; bounds: Bounds }[], marquee: Bounds): ElementRef[] {
  throw new Error('not implemented');
}
export function replaceSelection(ref: ElementRef): ElementRef[] {
  return [ref];
}
