// @generated by archebuild — do not edit. Regenerated each build.

export function createUiState(): UiState {
  throw new Error('not implemented');
}
export interface Viewport {
  panX: number;
  panY: number;
  zoom: number;
}
export interface ElementRef {
  id: string;
  kind: 'node' | 'edge' | 'group' | 'annotation';
}
export interface UiState {
  selection: Accessor<ElementRef[]>;
  setSelection: Setter<ElementRef[]>;
  hover: Accessor<ElementRef | undefined>;
  setHover: Setter<ElementRef | undefined>;
  tool: Accessor<Tool>;
  setTool: Setter<Tool>;
  viewport: Accessor<Viewport>;
  setViewport: Setter<Viewport>;
}
export type Tool = 'select' | 'hand' | 'annotation';
