// @generated by archebuild — do not edit. Regenerated each build.

import { boundsCentre, Bounds } from '@archeglyph/core/geometry/bounds';
import { Vec2 } from '@archeglyph/core/geometry/vec2';
import { Viewport } from './ui_state';

export function diagramToScreen(viewport: Viewport, containerRect: ContainerRect, diagramPt: Vec2): Vec2 {
  throw new Error('not implemented');
}
export interface ContainerRect {
  left: number;
  top: number;
  width: number;
  height: number;
}
export function zoomAboutPoint(viewport: Viewport, screenPt: Vec2, containerRect: ContainerRect, factor: number, minZoom: number, maxZoom: number): Viewport {
  throw new Error('not implemented');
}
export function screenToDiagram(viewport: Viewport, containerRect: ContainerRect, screenPt: Vec2): Vec2 {
  throw new Error('not implemented');
}
export function fitBoundsToRect(bounds: Bounds, containerRect: ContainerRect, padding: number): Viewport {
  const contentWidth = bounds.maxX - bounds.minX;
  const contentHeight = bounds.maxY - bounds.minY;
  const availWidth = containerRect.width - padding * 2;
  const availHeight = containerRect.height - padding * 2;
  const zoom = contentWidth <= 0 || contentHeight <= 0
    ? 1
    : Math.min(availWidth / contentWidth, availHeight / contentHeight);
  const centre = boundsCentre(bounds);
  return {
    zoom,
    panX: containerRect.width / 2 - centre.x * zoom,
    panY: containerRect.height / 2 - centre.y * zoom,
  };
}
