// @generated by archebuild — do not edit. Regenerated each build.

export function diagramToScreen(viewport: Viewport, containerRect: ContainerRect, diagramPt: Vec2): Vec2 {
  return {
    x: diagramPt.x * viewport.zoom + viewport.panX + containerRect.left,
    y: diagramPt.y * viewport.zoom + viewport.panY + containerRect.top,
  };
}
export interface ContainerRect {
  left: number;
  top: number;
  width: number;
  height: number;
}
export function zoomAboutPoint(viewport: Viewport, screenPt: Vec2, containerRect: ContainerRect, factor: number, minZoom: number, maxZoom: number): Viewport {
  throw new Error('not implemented');
}
export function screenToDiagram(viewport: Viewport, containerRect: ContainerRect, screenPt: Vec2): Vec2 {
  throw new Error('not implemented');
}
export function fitBoundsToRect(bounds: Bounds, containerRect: ContainerRect, padding: number): Viewport {
  throw new Error('not implemented');
}
