// @generated by archebuild — do not edit. Regenerated each build.

export function diagramToScreen(viewport: Viewport, containerRect: ContainerRect, diagramPt: Vec2): Vec2 {
  throw new Error('not implemented');
}
export interface ContainerRect {
  left: number;
  top: number;
  width: number;
  height: number;
}
export function zoomAboutPoint(viewport: Viewport, screenPt: Vec2, containerRect: ContainerRect, factor: number, minZoom: number, maxZoom: number): Viewport {
  throw new Error('not implemented');
}
export function screenToDiagram(viewport: Viewport, containerRect: ContainerRect, screenPt: Vec2): Vec2 {
  const localX = screenPt.x - containerRect.left;
  const localY = screenPt.y - containerRect.top;
  return { x: (localX - viewport.panX) / viewport.zoom, y: (localY - viewport.panY) / viewport.zoom };
}
export function fitBoundsToRect(bounds: Bounds, containerRect: ContainerRect, padding: number): Viewport {
  throw new Error('not implemented');
}
