// SPDX-License-Identifier: AGPL-3.0-or-later

// @generated by archebuild — do not edit. Regenerated each build.

import type { OpErrorCause } from '../op';

export class FormatOpError extends Error {
  stage!: string;
  cause!: OpErrorCause;
}
