// SPDX-License-Identifier: AGPL-3.0-or-later

// @generated by archebuild — do not edit. Regenerated each build.

import { Localization } from '@archeglyph/proto/gen/content_pb';

export class FilteredNode {
  id!: string;
  parentGroup?: string;
  tags!: Map<string, string>;
  label: Localization[] = [];
}
