// SPDX-License-Identifier: MPL-2.0

// @generated by archebuild — do not edit. Regenerated each build.

import { Glyph2D } from '@archeglyph/proto/gen/style_pb';
import { GroupLayout } from '@archeglyph/proto/gen/style_pb';
import { Localization } from '@archeglyph/proto/gen/content_pb';
import { Typography } from '@archeglyph/proto/gen/style_pb';

export class ResolvedGroup {
  id!: string;
  parentGroup?: string;
  shape!: Glyph2D;
  typography!: Typography;
  layout?: GroupLayout;
  label: Localization[] = [];
  isSuperNode!: boolean;
  hiddenDescendantCount!: number;
}
