// SPDX-License-Identifier: MPL-2.0
// @generated by archebuild — do not edit. Regenerated each build.

import { CanvasStyle } from '@archeglyph/proto/gen/style_pb';
import { ResolvedAnnotation } from '../resolved_annotation';
import { ResolvedEdge } from '../resolved_edge';
import { ResolvedGroup } from '../resolved_group';
import { ResolvedNode } from '../resolved_node';

export class ResolvedDiagram {
  id!: string;
  canvas!: CanvasStyle;
  nodes: Record<string, ResolvedNode> = {};
  edges: Record<string, ResolvedEdge> = {};
  groups: Record<string, ResolvedGroup> = {};
  annotations: Record<string, ResolvedAnnotation> = {};
}
