// SPDX-License-Identifier: AGPL-3.0-or-later

// @generated by archebuild — do not edit. Regenerated each build.

import { Diagram } from '@archeglyph/proto/gen/content_pb';
import { Stylesheet } from '@archeglyph/proto/gen/style_pb';
import { Theme } from '@archeglyph/proto/gen/theme_pb';
import { Err, Ok, Result } from '@archeglyph/proto/util/result';
import { CascadeRequest } from '../resolver/cascade_request';
import { FilterRequest } from '../resolver/filter_request';
import { ResolveTokensRequest } from '../resolver/resolve_tokens_request';
import { ResolvedDiagram } from '../resolver/resolved_diagram';
import { StyleCascadeImpl } from '../resolver/style_cascade';
import { TokenResolverImpl, resolveTokensIn } from '../resolver/token_resolver';
import { VisibilityFilterImpl } from '../resolver/visibility_filter';
import { PipelineError } from './pipeline_error';
import { init } from '@archeglyph/proto/util/init';

export function resolvePipeline(diagram: Diagram, stylesheet: Stylesheet | undefined, themes: ReadonlyMap<string, Theme>): Result<ResolvedDiagram, PipelineError> {
  // Each theme's components resolve against its own tokens, before the
  // cascade merges them. Two themes may name the same role with different
  // palettes behind it, and the merged element does not record which theme a
  // value came from.
  const perTheme: string[] = [];
  for (const [name, theme] of themes) {
    if (theme.tokens === undefined) continue;
    for (const ref of resolveTokensIn(theme.nodeComponents, theme.tokens)) perTheme.push(`${name}: ${ref}`);
    for (const ref of resolveTokensIn(theme.edgeComponents, theme.tokens)) perTheme.push(`${name}: ${ref}`);
    for (const ref of resolveTokensIn(theme.groupComponents, theme.tokens)) perTheme.push(`${name}: ${ref}`);
    for (const ref of resolveTokensIn(theme.annotationComponents, theme.tokens)) perTheme.push(`${name}: ${ref}`);
  }
  if (perTheme.length > 0) {
    return Err(init(new PipelineError(), { stage: 'tokens', detail: `unresolved token reference(s): ${[...new Set(perTheme)].sort().join(', ')}` }));
  }

  const filterResult = new VisibilityFilterImpl().filter(
    init(new FilterRequest(), { diagram, stylesheet })
  );
  if (filterResult.kind === 'err') {
    return Err(init(new PipelineError(), { stage: 'filter', detail: filterResult.error.message }));
  }

  const cascadeResult = new StyleCascadeImpl().cascade(
    init(new CascadeRequest(), { filtered: filterResult.value, stylesheet, themes })
  );
  if (cascadeResult.kind === 'err') {
    return Err(init(new PipelineError(), { stage: 'cascade', detail: cascadeResult.error.message }));
  }

  // Components are already resolved above; this pass is for refs a STYLESHEET
  // entry wrote, which are unqualified and so resolve against `default`.
  const tokenResult = new TokenResolverImpl().resolveTokens(
    init(new ResolveTokensRequest(), { resolved: cascadeResult.value, tokens: themes.get('default')?.tokens })
  );
  if (tokenResult.kind === 'err') {
    return Err(init(new PipelineError(), { stage: 'tokens', detail: tokenResult.error.message }));
  }

  return Ok(tokenResult.value);
}
