// @generated by archebuild — do not edit. Regenerated each build.

import { EdgeLayout } from '@archeglyph/proto/gen/style_pb';
import { EdgeSection } from '../edge_section';
import { Glyph1D } from '@archeglyph/proto/gen/style_pb';
import { Localization } from '@archeglyph/proto/gen/content_pb';
import { Typography } from '@archeglyph/proto/gen/style_pb';

export class LaidOutEdge {
  id!: string;
  source!: string;
  target!: string;
  sections: EdgeSection[] = [];
  connection!: Glyph1D;
  typography!: Typography;
  label: Localization[] = [];
  layout?: EdgeLayout;
}
