// @generated by archebuild — do not edit. Regenerated each build.

export function numberField(overrides: Array<number | undefined>, effectives: Array<number | undefined>): NumberField {
  if (overrides.length === 0) {
    return { override: undefined, effective: undefined, mixed: false };
  }

  const firstOverride = overrides[0];
  const firstEffective = effectives[0];
  let mixed = false;

  for (let index = 1; index < overrides.length; index += 1) {
    const override = overrides[index];
    if ((override === undefined) !== (firstOverride === undefined)
      || (override !== undefined && firstOverride !== undefined && override !== firstOverride)) {
      mixed = true;
    }
  }

  for (let index = 1; index < effectives.length; index += 1) {
    if (effectives[index] !== firstEffective) {
      return { override: mixed ? undefined : firstOverride, effective: undefined, mixed };
    }
  }

  return { override: mixed ? undefined : firstOverride, effective: firstEffective, mixed };
}
export function textField(overrides: Array<string | undefined>, effectives: Array<string | undefined>): TextField {
  throw new Error('not implemented');
}
export interface NumberField {
  override?: number;
  effective?: number;
  mixed: boolean;
}
export interface TextField {
  override?: string;
  effective?: string;
  mixed: boolean;
}
