// @generated by archebuild — do not edit. Regenerated each build.

export function numberField(overrides: Array<number | undefined>, effectives: Array<number | undefined>): NumberField {
  throw new Error('not implemented');
}
export function textField(overrides: Array<string | undefined>, effectives: Array<string | undefined>): TextField {
  throw new Error('not implemented');
}
export interface NumberField {
  override?: number;
  effective?: number;
  mixed: boolean;
}
export interface TextField {
  override?: string;
  effective?: string;
  mixed: boolean;
}
