// @generated by archebuild — do not edit. Regenerated each build.

export function numberField(overrides: Array<number | undefined>, effectives: Array<number | undefined>): NumberField {
  throw new Error('not implemented');
}
export function textField(overrides: Array<string | undefined>, effectives: Array<string | undefined>): TextField {
  const firstOverride = overrides[0];
  const overrideAgrees = overrides.every((override) => override === firstOverride);
  const firstEffective = effectives[0];
  const effectiveAgrees = effectives.every((effective) => effective === firstEffective);

  return {
    override: overrideAgrees ? firstOverride : undefined,
    effective: effectiveAgrees ? firstEffective : undefined,
    mixed: !overrideAgrees,
  };
}
export interface NumberField {
  override?: number;
  effective?: number;
  mixed: boolean;
}
export interface TextField {
  override?: string;
  effective?: string;
  mixed: boolean;
}
