// @generated by archebuild — do not edit. Regenerated each build.

export function layoutModel(model: InspectorModel, geometry: SceneGeometry, stylesheet: Stylesheet): LayoutModel {
  const override = (id: string): { position?: { x: number; y: number }; size?: { x: number; y: number } } | undefined => {
    if (model.kind === 'node') return stylesheet.nodes[id]?.layout;
    if (model.kind === 'group') return stylesheet.groups[id]?.layout;
    if (model.kind === 'annotation') return stylesheet.annotations[id]?.layout;
    return undefined;
  };
  const effective = (id: string): { x: number; y: number; width: number; height: number } | undefined => {
    const entry = geometry.byKey[elementKey({ kind: model.kind, id })];
    if (entry === undefined) return undefined;
    const parent = entry.parentGroup === undefined
      ? undefined
      : geometry.byKey[elementKey({ kind: 'group', id: entry.parentGroup })];
    return {
      x: entry.bounds.minX - (parent?.bounds.minX ?? 0),
      y: entry.bounds.minY - (parent?.bounds.minY ?? 0),
      width: entry.bounds.maxX - entry.bounds.minX,
      height: entry.bounds.maxY - entry.bounds.minY,
    };
  };
  const overrides = model.ids.map(override);
  const effectives = model.ids.map(effective);
  return {
    x: numberField(overrides.map((entry) => entry?.position?.x), effectives.map((entry) => entry?.x)),
    y: numberField(overrides.map((entry) => entry?.position?.y), effectives.map((entry) => entry?.y)),
    width: numberField(overrides.map((entry) => entry?.size?.x), effectives.map((entry) => entry?.width)),
    height: numberField(overrides.map((entry) => entry?.size?.y), effectives.map((entry) => entry?.height)),
  };
}
export function commitTypography(model: InspectorModel, stylesheet: Stylesheet, field: 'size' | 'color' | 'font', value: string | number | undefined): StyleEdit | undefined {
  const changes = model.ids.map((id) => {
    const existing = model.kind === 'node' ? stylesheet.nodes[id]
      : model.kind === 'edge' ? stylesheet.edges[id]
        : model.kind === 'group' ? stylesheet.groups[id] : stylesheet.annotations[id];
    const current = existing?.typography;
    const typography = create(TypographySchema, {
      ...(current === undefined ? {} : { ...current }),
      ...(field === 'size' ? { size: value as number | undefined } : {}),
      ...(field === 'font' ? { font: value as string | undefined } : {}),
      ...(field === 'color' ? { color: value === undefined ? undefined : create(ColorSchema, { value: value as string }) } : {}),
    });
    const after = createEntryWithTypography(model.kind, id, existing, typography);
    if (model.kind === 'node') return nodeChange(id, after as NodeStyleEntry);
    if (model.kind === 'edge') return edgeChange(id, after as EdgeStyleEntry);
    if (model.kind === 'group') return groupChange(id, after as GroupStyleEntry);
    return annotationChange(id, after as AnnotationEntry);
  });
  return styleEdit({
    ...(model.kind === 'node' ? { nodeChanges: changes as Array<NodeStyleChange> } : {}),
    ...(model.kind === 'edge' ? { edgeChanges: changes as Array<EdgeStyleChange> } : {}),
    ...(model.kind === 'group' ? { groupChanges: changes as Array<GroupStyleChange> } : {}),
    ...(model.kind === 'annotation' ? { annotationChanges: changes as Array<AnnotationStyleChange> } : {}),
    description: 'Edit selected typography',
  });
}
export function commitLayout(model: InspectorModel, geometry: SceneGeometry, stylesheet: Stylesheet, field: 'x' | 'y' | 'width' | 'height', value: number | undefined): StyleEdit | undefined {
  if (model.kind === 'edge' || model.ids.length === 0) {
    return undefined;
  }

  // A cleared annotation position is intentionally not passed to
  // unpinElementsEdit.  Unlike nodes and groups, annotations have no derived
  // position to return to.
  if (value === undefined && (field === 'x' || field === 'y') && model.kind === 'annotation') {
    return undefined;
  }

  const isSize = field === 'width' || field === 'height';
  const overrideValue = (id: string): number | undefined => {
    const entry = model.kind === 'node'
      ? stylesheet.nodes[id]
      : model.kind === 'group'
        ? stylesheet.groups[id]
        : stylesheet.annotations[id];
    if (entry?.layout === undefined) {
      return undefined;
    }
    if (field === 'x' || field === 'y') {
      const position = entry.layout.position;
      return position === undefined ? undefined : field === 'x' ? position.x : position.y;
    }
    const size = entry.layout.size;
    return size === undefined ? undefined : field === 'width' ? size.x : size.y;
  };

  if (model.ids.every((id) => overrideValue(id) === value)) {
    return undefined;
  }

  const refs: Array<ElementMove> = model.ids.map((id) => ({
    kind: model.kind,
    id,
    // unpinElementsEdit only uses kind and id; the position is part of the
    // shared move reference type and is deliberately ignored for unpinning.
    position: create(Vec2Schema, { x: 0, y: 0 }),
  }));
  if (!isSize && value === undefined) {
    return unpinElementsEdit(stylesheet, refs);
  }

  if (isSize && value === undefined) {
    const edits = model.ids.map((id) => {
      if (model.kind === 'node') return clearNodeSizeEdit(stylesheet, id);
      if (model.kind === 'group') return clearGroupSizeEdit(stylesheet, id);
      return clearAnnotationSizeEdit(stylesheet, id);
    });
    return styleEdit({
      nodeChanges: edits.flatMap((edit) => edit.nodeChanges),
      groupChanges: edits.flatMap((edit) => edit.groupChanges),
      annotationChanges: edits.flatMap((edit) => edit.annotationChanges),
      description: 'Clear selected size override',
    });
  }

  const edits = model.ids.map((id) => {
    const bounds = geometry.byKey[elementKey({ kind: model.kind, id })]?.bounds;
    if (bounds === undefined) {
      return undefined;
    }
    const parentId = geometry.byKey[elementKey({ kind: model.kind, id })]?.parentGroup;
    const parent = parentId === undefined
      ? undefined
      : geometry.byKey[elementKey({ kind: 'group', id: parentId })];
    const position = create(Vec2Schema, {
      x: bounds.minX - (parent?.bounds.minX ?? 0),
      y: bounds.minY - (parent?.bounds.minY ?? 0),
    });
    if (!isSize) {
      return moveElementsEdit(stylesheet, [{
        kind: model.kind,
        id,
        position: create(Vec2Schema, {
          x: field === 'x' ? value ?? position.x : position.x,
          y: field === 'y' ? value ?? position.y : position.y,
        }),
      }]);
    }
    const size = create(Vec2Schema, {
      x: field === 'width' ? value as number : bounds.maxX - bounds.minX,
      y: field === 'height' ? value as number : bounds.maxY - bounds.minY,
    });
    if (model.kind === 'node') return resizeNodeEdit(stylesheet, id, position, size);
    if (model.kind === 'group') return resizeGroupEdit(stylesheet, id, position, size);
    return resizeAnnotationEdit(stylesheet, id, position, size);
  }).filter((edit): edit is StyleEdit => edit !== undefined);

  if (edits.length === 0) {
    return undefined;
  }
  return styleEdit({
    nodeChanges: edits.flatMap((edit) => edit.nodeChanges),
    groupChanges: edits.flatMap((edit) => edit.groupChanges),
    annotationChanges: edits.flatMap((edit) => edit.annotationChanges),
    description: 'Edit selected layout',
  });
}
import {
  AnnotationEntry, AnnotationEntrySchema, AnnotationStyleChange, ColorSchema, EdgeStyleChange,
  EdgeStyleEntry, EdgeStyleEntrySchema, GroupStyleChange, GroupStyleEntry, GroupStyleEntrySchema,
  NodeStyleChange, NodeStyleEntry, NodeStyleEntrySchema, StyleEdit, Stylesheet, Typography,
  TypographySchema, Vec2Schema,
} from '@archeglyph/proto/gen/style_pb';
import { create } from '@bufbuild/protobuf';
import { InspectorModel } from './model';
import { SceneGeometry } from '../scene/scene';
import { numberField, textField } from './field_value';
import { NumberField } from './field_value';
import { TextField } from './field_value';
import { elementKey } from '../scene/element_key';
import { ElementMove, moveElementsEdit } from '../state/edits/move';
import { unpinElementsEdit } from '../state/edits/layout_command';
import {
  clearAnnotationSizeEdit,
  clearGroupSizeEdit,
  clearNodeSizeEdit,
  resizeAnnotationEdit,
  resizeGroupEdit,
  resizeNodeEdit,
} from '../state/edits/resize';
import {
  annotationChange, edgeChange, groupChange, nodeChange, styleEdit,
} from '../state/edits/edit_builder';
import { initOf } from '../state/edits/entry_patch';

function createEntryWithTypography(
  kind: InspectorModel['kind'],
  id: string,
  existing: NodeStyleEntry | EdgeStyleEntry | GroupStyleEntry | AnnotationEntry | undefined,
  typography: Typography,
): NodeStyleEntry | EdgeStyleEntry | GroupStyleEntry | AnnotationEntry {
  const entry = { ...initOf(existing), typography };
  if (kind === 'node') return create(NodeStyleEntrySchema, entry);
  if (kind === 'edge') return create(EdgeStyleEntrySchema, entry);
  if (kind === 'group') return create(GroupStyleEntrySchema, entry);
  return create(AnnotationEntrySchema, { ...entry, id });
}

export interface TypographyModel {
  size: NumberField;
  color: TextField;
  font: TextField;
}
import { NumberField } from './field_value';

export interface LayoutModel {
  x: NumberField;
  y: NumberField;
  width: NumberField;
  height: NumberField;
}
export function typographyModel(model: InspectorModel, geometry: SceneGeometry, stylesheet: Stylesheet): TypographyModel {
  const overrideTypography = (id: string): Typography | undefined => {
    switch (model.kind) {
      case 'node': return stylesheet.nodes[id]?.typography;
      case 'edge': return stylesheet.edges[id]?.typography;
      case 'group': return stylesheet.groups[id]?.typography;
      case 'annotation': return stylesheet.annotations[id]?.typography;
    }
  };

  const effectiveTypography = (id: string): Typography | undefined => {
    switch (model.kind) {
      case 'node': return geometry.diagram.nodes.find((entry) => entry.id === id)?.typography;
      case 'edge': return geometry.diagram.edges.find((entry) => entry.id === id)?.typography;
      case 'group': return geometry.diagram.groups.find((entry) => entry.id === id)?.typography;
      case 'annotation': return geometry.diagram.annotations.find((entry) => entry.id === id)?.typography;
    }
  };

  const overrides = model.ids.map(overrideTypography);
  const effectives = model.ids.map(effectiveTypography);
  return {
    size: numberField(
      overrides.map((typography) => typography?.size),
      effectives.map((typography) => typography?.size),
    ),
    color: textField(
      overrides.map((typography) => typography?.color?.value),
      effectives.map((typography) => typography?.color?.value),
    ),
    font: textField(
      overrides.map((typography) => typography?.font),
      effectives.map((typography) => typography?.font),
    ),
  };
}
