// @generated by archebuild — do not edit. Regenerated each build.

import { create } from '@bufbuild/protobuf';
import { ColorSchema, StyleEdit, Stylesheet, Typography, TypographySchema } from '@archeglyph/proto/gen/style_pb';
import { InspectorModel } from './model';
import {
  setAnnotationGlyphEdit,
  setEdgeGlyphEdit,
  setGroupGlyphEdit,
  setNodesGlyphEdit,
} from '../state/edits/glyph';
import { initOf } from '../state/edits/entry_patch';

export function layoutModel(model: InspectorModel, geometry: SceneGeometry, stylesheet: Stylesheet): LayoutModel {
  throw new Error('not implemented');
}
export function commitTypography(model: InspectorModel, stylesheet: Stylesheet, field: 'size' | 'color' | 'font', value: string | number | undefined): StyleEdit | undefined {
  const firstId = model.ids[0];
  if (firstId === undefined) {
    return undefined;
  }

  const existing = model.kind === 'node'
    ? stylesheet.nodes[firstId]?.typography
    : model.kind === 'edge'
      ? stylesheet.edges[firstId]?.typography
      : model.kind === 'group'
        ? stylesheet.groups[firstId]?.typography
        : stylesheet.annotations[firstId]?.typography;
  const current = field === 'color' ? existing?.color?.value : existing?.[field];
  if (current === value) {
    return undefined;
  }

  // Glyph builders accept the complete Typography message.  Start with the
  // existing message (rather than a message containing just the edited field)
  // so an inspector edit cannot discard weight, alignment, or background.
  const typographyInit = initOf(existing);
  if (value === undefined) {
    delete typographyInit[field];
  } else if (field === 'color') {
    typographyInit.color = create(ColorSchema, { value: String(value) });
  } else {
    typographyInit[field] = value;
  }
  const typography = create(TypographySchema, typographyInit as Partial<Typography>);

  if (model.kind === 'node') {
    return setNodesGlyphEdit(stylesheet, model.ids, { typography });
  }
  if (model.kind === 'edge') {
    return setEdgeGlyphEdit(stylesheet, firstId, { typography });
  }
  if (model.kind === 'group') {
    return setGroupGlyphEdit(stylesheet, firstId, { typography });
  }
  return setAnnotationGlyphEdit(stylesheet, firstId, { typography });
}
export function commitLayout(model: InspectorModel, geometry: SceneGeometry, stylesheet: Stylesheet, field: 'x' | 'y' | 'width' | 'height', value: number | undefined): StyleEdit | undefined {
  throw new Error('not implemented');
}
import { NumberField } from './field_value';
import { TextField } from './field_value';

export interface TypographyModel {
  size: NumberField;
  color: TextField;
  font: TextField;
}
import { NumberField } from './field_value';

export interface LayoutModel {
  x: NumberField;
  y: NumberField;
  width: NumberField;
  height: NumberField;
}
export function typographyModel(model: InspectorModel, geometry: SceneGeometry, stylesheet: Stylesheet): TypographyModel {
  throw new Error('not implemented');
}
