// SPDX-License-Identifier: AGPL-3.0-or-later
// @generated by archebuild — do not edit. Regenerated each build.

/** Character advance width as a fraction of font size, for Noto Sans Mono (and any other monospace face until a real per-font table exists). */
export const MONOSPACE_ADVANCE_WIDTH_RATIO: number = 0.6;
/** Line height as a fraction of font size. Not font-specific; a common typographic default. */
export const LINE_HEIGHT_RATIO: number = 1.2;

import type { Vec2 } from '../../geometry/vec2';

export function measureLabel(text: string, font: string, size: number): Vec2 {
  // The font argument is part of the public API so a per-font table can be
  // introduced later without changing callers. All currently supported fonts
  // use the same monospace approximation.
  void font;

  const lines: string[] = text.split('\n');
  let longestLineLength: number = 0;
  for (const line of lines) {
    longestLineLength = Math.max(longestLineLength, line.length);
  }

  return {
    x: longestLineLength * MONOSPACE_ADVANCE_WIDTH_RATIO * size,
    y: lines.length * LINE_HEIGHT_RATIO * size,
  };
}
