// @generated by archebuild — do not edit. Regenerated each build.

import type { Chord } from '../ui_state/keymap';

export function formatChord(chord: Chord): string {
  const isApple = navigator.platform.includes('Mac');
  const keyNames: Record<string, string> = {
    ArrowUp: 'Up',
    ArrowDown: 'Down',
    ArrowLeft: 'Left',
    ArrowRight: 'Right',
    Escape: 'Esc',
  };
  const key = keyNames[chord.key] ?? (chord.key.length === 1 ? chord.key.toUpperCase() : chord.key);

  if (isApple) {
    return `${chord.meta === true ? '⌘' : ''}${chord.shift === true ? '⇧' : ''}${key}`;
  }

  const modifiers: string[] = [];
  if (chord.meta === true) {
    modifiers.push('Ctrl');
  }
  if (chord.shift === true) {
    modifiers.push('Shift');
  }
  modifiers.push(key);
  return modifiers.join('+');
}
