// @generated by archebuild — do not edit. Regenerated each build.

import { PaletteAction } from './palette_item';
import { PaletteItem } from './palette_item';

export interface CommandPaletteProps {
  items: ReadonlyArray<PaletteItem>;
  onChoose: (a0: PaletteAction) => void;
  onClose: () => void;
}
