// SPDX-License-Identifier: AGPL-3.0-or-later
// @generated by archebuild — do not edit. Regenerated each build.

import { StyleEdit, Stylesheet } from '@archeglyph/proto/gen/style_pb';
import { Result } from '@archeglyph/proto/util/result';
import { diffStylesheets } from '../state/stylesheet_diff';
import { hashStylesheet } from '../state/stylesheet_hash';
import { AdapterError, FileStamp, HostAdapter, LoadResult } from '../adapters/host_adapter';

export function watchOnFocus(adapter: HostAdapter, currentStylesheet: () => Stylesheet, onChange: (change: ExternalChange) => void): () => void {
  throw new Error('not implemented');
}

export async function checkForExternalChange(
  adapter: HostAdapter,
  loaded: Stylesheet,
  lastStamp?: FileStamp,
): Promise<ExternalChange | undefined> {
  // Stat is intentionally kept separate from load: focus events are common,
  // while parsing and hashing the stylesheet is comparatively expensive.
  const stampResult: Result<FileStamp, AdapterError> = await adapter.stat();
  if (stampResult.kind === 'err') {
    return undefined;
  }

  const stamp: FileStamp = stampResult.value;
  if (
    lastStamp !== undefined &&
    stamp.lastModified === lastStamp.lastModified &&
    stamp.size === lastStamp.size
  ) {
    return undefined;
  }

  const loadResult: Result<LoadResult, AdapterError> = await adapter.load();
  if (loadResult.kind === 'err' || loadResult.value.stylesheet === undefined) {
    return undefined;
  }

  const stylesheet: Stylesheet = loadResult.value.stylesheet;
  const baseHash: string = await hashStylesheet(stylesheet);
  const edit: StyleEdit | undefined = diffStylesheets(loaded, stylesheet, 'external');
  return { edit, stylesheet, baseHash, stamp };
}

export interface ExternalChange {
  edit: StyleEdit | undefined;
  stylesheet: Stylesheet;
  baseHash: string;
  stamp?: FileStamp;
}
