// @generated by archebuild — do not edit. Regenerated each build.

import { SaveStatus } from '../save_status';

export class FileIslandProps {
  fileName!: string;
  dirty!: boolean;
  canSave!: boolean;
  status?: SaveStatus;
  errorMessage?: string;
  onSave!: () => void;
  editorTheme!: string;
  onEditorTheme!: (a0: string) => void;
}
