// @generated by archebuild — do not edit. Regenerated each build.

/**
 * Gap in CSS pixels between an island and the viewport edge. 12.
 *
 * Half the drafting grid cell, so island edges land on a half-cell and
 * read as placed rather than arbitrary.
 *
 * IslandFrame sets `--ag-island-inset` from this constant on its root
 * element, and styles.css references only that custom property, never a
 * literal 12px. Otherwise the TypeScript constant is dead -- a value with
 * no observable effect that the hand-maintained CSS silently shadows,
 * which is the failure the next person greps for and misreads.
 */
export const ISLAND_INSET: number = 12;

export class IslandFrameProps {
  canvas!: JSX.Element;
  toolbar?: JSX.Element;
  inspector?: JSX.Element;
  file?: JSX.Element;
  zoom?: JSX.Element;
  undo?: JSX.Element;
  state?: JSX.Element;
}
