// @generated by archebuild — do not edit. Regenerated each build.

import { CommandId } from '../ui_state/keymap';

export interface MenuItem {
  id: CommandId;
  label: string;
  chord: string;
}
import { Command } from '../gestures/commands';
import { ElementRef } from '../ui_state/ui_state';
import { KeymapEntry } from '../ui_state/keymap';

export function contextMenuItems(selection: ReadonlyArray<ElementRef>, commands: ReadonlyArray<Command>, keymap: ReadonlyArray<KeymapEntry>): Array<MenuItem> {
  throw new Error('not implemented');
}
