// @generated by archebuild — do not edit. Regenerated each build.

export function filterPaletteItems(items: ReadonlyArray<PaletteItem>, query: string): Array<PaletteItem> {
  const normalizedQuery = query.trim().toLowerCase();
  const prefixMatches: Array<PaletteItem> = [];
  const substringMatches: Array<PaletteItem> = [];

  for (const item of items) {
    const normalizedLabel = item.label.toLowerCase();
    if (!normalizedLabel.includes(normalizedQuery)) {
      continue;
    }

    if (normalizedLabel.startsWith(normalizedQuery)) {
      prefixMatches.push(item);
    } else {
      substringMatches.push(item);
    }
  }

  return prefixMatches.concat(substringMatches);
}
