// @generated by archebuild — do not edit. Regenerated each build.

import { PaletteAction } from './palette_item';

export interface PaletteItem {
  key: string;
  label: string;
  detail: string;
  action: PaletteAction;
}
export type PaletteAction = { kind: 'command'; command: CommandId } | { kind: 'element'; ref: ElementRef };
