// @generated by archebuild — do not edit. Regenerated each build.

import type { Command } from '../gestures/commands';
import type { KeymapEntry } from '../ui_state/keymap';
import { formatChord } from './chord_label';
import { PALETTE_EXCLUDED } from './palette_excluded';
import type { PaletteItem } from './palette_item';
import type { LaidOutDiagram } from '@archeglyph/core/layout/laid_out_diagram';

export function commandPaletteItems(commands: ReadonlyArray<Command>, keymap: ReadonlyArray<KeymapEntry>): Array<PaletteItem> {
  const items: Array<PaletteItem> = [];
  for (const command of commands) {
    if (PALETTE_EXCLUDED.has(command.id)) {
      continue;
    }
    const binding = keymap.find((entry) => entry.command === command.id);
    items.push({
      key: `command:${command.id}`,
      label: command.label,
      detail: binding === undefined ? '' : formatChord(binding.chord),
      action: { kind: 'command', command: command.id },
    });
  }
  return items;
}
export function elementPaletteItems(diagram: LaidOutDiagram): Array<PaletteItem> {
  throw new Error('not implemented');
}
