// @generated by archebuild — do not edit. Regenerated each build.

import { CommandId } from '../command_id';
import { Tool } from '../tool';

export class ToolbarProps {
  tool!: Tool;
  onCommand!: (a0: CommandId) => void;
}
