// @generated by archebuild — do not edit. Regenerated each build.

import { CommandId } from '../ui_state/keymap';
import { Tool } from '../tool';

export class ToolbarProps {
  tool!: Tool;
  onCommand!: (a0: CommandId) => void;
}
