// @generated by archebuild — do not edit. Regenerated each build.

import { CommandId } from '../command_id';

export class UndoIslandProps {
  canUndo!: boolean;
  canRedo!: boolean;
  onCommand!: (a0: CommandId) => void;
}
