// @generated by archebuild — do not edit. Regenerated each build.

import type { OpErrorCause } from '../op';

export class ValidateOpError extends Error {
  stage!: string;
  cause!: OpErrorCause;
}
