// @generated by archebuild — do not edit. Regenerated each build.

export class ValidateParams {
  diagram!: string;
  style?: string;
  theme?: string;
}
export function validateParamsSchema(): unknown {
  throw new Error('not implemented');
}
