// @generated by archebuild — do not edit. Regenerated each build.

import { create, equals } from '@bufbuild/protobuf';
import {
  ChangeType,
  Delta,
  DeltaSchema,
  Edge,
  EdgeDeltaSchema,
  EdgeSchema,
  Node,
  NodeDeltaSchema,
  NodeSchema,
  Diagram,
} from '@archeglyph/proto/gen/content_pb';

export function diff(base: Diagram, target: Diagram, options?: DiffOptions): Delta {
  const baseNodes: { [key: string]: Node } = base.graph !== undefined ? base.graph.nodes : {};
  const targetNodes: { [key: string]: Node } = target.graph !== undefined ? target.graph.nodes : {};
  const baseEdges: { [key: string]: Edge } = base.graph !== undefined ? base.graph.edges : {};
  const targetEdges: { [key: string]: Edge } = target.graph !== undefined ? target.graph.edges : {};
  const includeUnchanged = options !== undefined && options.includeUnchanged === true;

  const nodeDeltas = [];
  const nodeIds = Array.from(new Set([...Object.keys(baseNodes), ...Object.keys(targetNodes)])).sort();
  for (const nodeId of nodeIds) {
    const before = baseNodes[nodeId];
    const after = targetNodes[nodeId];
    if (before === undefined && after !== undefined) {
      nodeDeltas.push(create(NodeDeltaSchema, {
        nodeId,
        changeType: ChangeType.ADDED,
        after,
      }));
    } else if (before !== undefined && after === undefined) {
      nodeDeltas.push(create(NodeDeltaSchema, {
        nodeId,
        changeType: ChangeType.DELETED,
        before,
      }));
    } else if (before !== undefined && after !== undefined && !equals(NodeSchema, before, after)) {
      nodeDeltas.push(create(NodeDeltaSchema, {
        nodeId,
        changeType: ChangeType.MODIFIED,
        before,
        after,
      }));
    } else if (includeUnchanged && before !== undefined && after !== undefined) {
      nodeDeltas.push(create(NodeDeltaSchema, {
        nodeId,
        changeType: ChangeType.UNCHANGED,
        before,
        after,
      }));
    }
  }

  const edgeDeltas = [];
  const edgeIds = Array.from(new Set([...Object.keys(baseEdges), ...Object.keys(targetEdges)])).sort();
  for (const edgeId of edgeIds) {
    const before = baseEdges[edgeId];
    const after = targetEdges[edgeId];
    if (before === undefined && after !== undefined) {
      edgeDeltas.push(create(EdgeDeltaSchema, {
        edgeId,
        changeType: ChangeType.ADDED,
        after,
      }));
    } else if (before !== undefined && after === undefined) {
      edgeDeltas.push(create(EdgeDeltaSchema, {
        edgeId,
        changeType: ChangeType.DELETED,
        before,
      }));
    } else if (before !== undefined && after !== undefined && !equals(EdgeSchema, before, after)) {
      edgeDeltas.push(create(EdgeDeltaSchema, {
        edgeId,
        changeType: ChangeType.MODIFIED,
        before,
        after,
      }));
    } else if (includeUnchanged && before !== undefined && after !== undefined) {
      edgeDeltas.push(create(EdgeDeltaSchema, {
        edgeId,
        changeType: ChangeType.UNCHANGED,
        before,
        after,
      }));
    }
  }

  return create(DeltaSchema, {
    schemaVersion: 1,
    baseRef: base.id,
    targetRef: target.id,
    nodeDeltas,
    edgeDeltas,
  });
}
export class DiffOptions {
  includeUnchanged?: boolean;
}
