// SPDX-License-Identifier: MPL-2.0

// @generated by archebuild — do not edit. Regenerated each build.

import { Delta, DeltaSchema, Diagram, DiagramSchema } from '@archeglyph/proto/gen/content_pb';
import { LoadRequest } from '../load_request';
import { Loader } from '../loader';
import { Stylesheet, StylesheetSchema } from '@archeglyph/proto/gen/style_pb';
import { Theme, ThemeSchema } from '@archeglyph/proto/gen/theme_pb';
import { fromJson } from '@archeglyph/proto/util/json';

export class LoaderImpl implements Loader {
  async loadDiagram(request: LoadRequest): Promise<Diagram> {
    const diagram = fromJson(DiagramSchema, request.text);
    if (diagram.schemaVersion !== 1) {
      throw new Error(
        `loadDiagram: unsupported schema_version ${diagram.schemaVersion} (expected 1)`,
      );
    }
    return diagram;
  }
  async loadStylesheet(request: LoadRequest): Promise<Stylesheet> {
    const stylesheet = fromJson(StylesheetSchema, request.text);
    if (stylesheet.schemaVersion !== 1) {
      throw new Error(
        `loadStylesheet: unsupported schema_version ${stylesheet.schemaVersion} (expected 1)`,
      );
    }
    // StyleEdit carries its own schema_version; the parent's check above
    // does not cover it.
    for (const edit of stylesheet.pendingEdits) {
      if (edit.schemaVersion !== 1) {
        throw new Error(
          `loadStylesheet: pending edit '${edit.id}' has unsupported schema_version ${edit.schemaVersion} (expected 1)`,
        );
      }
    }
    return stylesheet;
  }
  async loadDelta(request: LoadRequest): Promise<Delta> {
    const delta = fromJson(DeltaSchema, request.text);
    if (delta.schemaVersion !== 1) {
      throw new Error(
        `loadDelta: unsupported schema_version ${delta.schemaVersion} (expected 1)`,
      );
    }
    return delta;
  }
  async loadTheme(request: LoadRequest): Promise<Theme> {
    const theme = fromJson(ThemeSchema, request.text);
    if (theme.schemaVersion !== 1) {
      throw new Error(
        `loadTheme: unsupported schema_version ${theme.schemaVersion} (expected 1)`,
      );
    }
    return theme;
  }
}
