// @generated by archebuild — do not edit. Regenerated each build.

import { FilterRequest } from '../filter_request';
import { FilteredDiagram } from '../filtered_diagram';
import { ResolveError } from '../resolve_error';
import { Result } from '@archeglyph/proto/util/result';
import { VisibilityFilter } from './schema_gen';

export class VisibilityFilterImpl implements VisibilityFilter {
  filter(request: FilterRequest): Result<FilteredDiagram, ResolveError> { throw new Error('not implemented'); }
}
