// SPDX-License-Identifier: AGPL-3.0-or-later

// @generated by archebuild — do not edit. Regenerated each build.

import { FilterRequest } from '../filter_request';
import { FilteredDiagram } from '../filtered_diagram';
import { ResolveError } from '../resolve_error';
import { Result } from '@archeglyph/proto/util/result';

export interface VisibilityFilter {
  filter(request: FilterRequest): Result<FilteredDiagram, ResolveError>;
}
