// @generated by archebuild — do not edit. Regenerated each build.

import { EditorState } from '../editor_state';
import { ElementKind } from './selection';
import { Vec2 } from './viewport';
import { ViewportState } from './viewport';

export class DragHandler {
  state!: EditorState;
  viewport!: ViewportState;
  dragOffset(): Vec2 | null { throw new Error('not implemented'); }
  onPointerDown(elementId: string, elementKind: ElementKind, startPt: Vec2): void { throw new Error('not implemented'); }
  onPointerMove(screenPt: Vec2): void { throw new Error('not implemented'); }
  onPointerUp(): void { throw new Error('not implemented'); }
}
