// @generated by archebuild — do not edit. Regenerated each build.

export function applyStyleEditToStylesheet(current: Stylesheet, edit: StyleEdit): Stylesheet {
  throw new Error('not implemented');
}
export function applyMapChanges<C, V>(current: { [key: string]: V }, changes: C[], getId: (change: C) => string, getChangeType: (change: C) => StyleChangeType, getAfter: (change: C) => V | undefined): { [key: string]: V } {
  throw new Error('not implemented');
}
