// SPDX-License-Identifier: AGPL-3.0-or-later
// @generated by archebuild — do not edit. Regenerated each build.

import { create, equals } from '@bufbuild/protobuf';
import {
  AnnotationStyleChange,
  AnnotationStyleChangeSchema,
  AnnotationEntrySchema,
  CanvasStyleSchema,
  EdgeStyleChange,
  EdgeStyleChangeSchema,
  EdgeStyleEntrySchema,
  GroupStyleChange,
  GroupStyleChangeSchema,
  GroupStyleEntrySchema,
  NodeStyleChange,
  NodeStyleChangeSchema,
  NodeStyleEntrySchema,
  StyleChangeType,
  StyleEdit,
  StyleEditSchema,
  StyleEditState,
  Stylesheet,
} from '@archeglyph/proto/gen/style_pb';

/**
 * Produces a pending edit containing the deterministic, whole-entry diff
 * between two stylesheets.
 */
export function diffStylesheets(base: Stylesheet, incoming: Stylesheet, author: string): StyleEdit | undefined {
  const nodeChanges: NodeStyleChange[] = [];
  const nodeIds = Array.from(new Set([...Object.keys(base.nodes), ...Object.keys(incoming.nodes)])).sort();
  for (const nodeId of nodeIds) {
    const before = base.nodes[nodeId];
    const after = incoming.nodes[nodeId];
    if (before === undefined && after !== undefined) {
      nodeChanges.push(create(NodeStyleChangeSchema, {
        nodeId,
        changeType: StyleChangeType.ADDED,
        after,
        unsetPaths: [],
        kinds: [],
      }));
    } else if (before !== undefined && after === undefined) {
      nodeChanges.push(create(NodeStyleChangeSchema, {
        nodeId,
        changeType: StyleChangeType.DELETED,
        unsetPaths: [],
        kinds: [],
      }));
    } else if (before !== undefined && after !== undefined && !equals(NodeStyleEntrySchema, before, after)) {
      nodeChanges.push(create(NodeStyleChangeSchema, {
        nodeId,
        changeType: StyleChangeType.MODIFIED,
        after,
        unsetPaths: [],
        kinds: [],
      }));
    }
  }

  const edgeChanges: EdgeStyleChange[] = [];
  const edgeIds = Array.from(new Set([...Object.keys(base.edges), ...Object.keys(incoming.edges)])).sort();
  for (const edgeId of edgeIds) {
    const before = base.edges[edgeId];
    const after = incoming.edges[edgeId];
    if (before === undefined && after !== undefined) {
      edgeChanges.push(create(EdgeStyleChangeSchema, {
        edgeId,
        changeType: StyleChangeType.ADDED,
        after,
        unsetPaths: [],
        kinds: [],
      }));
    } else if (before !== undefined && after === undefined) {
      edgeChanges.push(create(EdgeStyleChangeSchema, {
        edgeId,
        changeType: StyleChangeType.DELETED,
        unsetPaths: [],
        kinds: [],
      }));
    } else if (before !== undefined && after !== undefined && !equals(EdgeStyleEntrySchema, before, after)) {
      edgeChanges.push(create(EdgeStyleChangeSchema, {
        edgeId,
        changeType: StyleChangeType.MODIFIED,
        after,
        unsetPaths: [],
        kinds: [],
      }));
    }
  }

  const groupChanges: GroupStyleChange[] = [];
  const groupIds = Array.from(new Set([...Object.keys(base.groups), ...Object.keys(incoming.groups)])).sort();
  for (const groupId of groupIds) {
    const before = base.groups[groupId];
    const after = incoming.groups[groupId];
    if (before === undefined && after !== undefined) {
      groupChanges.push(create(GroupStyleChangeSchema, {
        groupId,
        changeType: StyleChangeType.ADDED,
        after,
        unsetPaths: [],
        kinds: [],
      }));
    } else if (before !== undefined && after === undefined) {
      groupChanges.push(create(GroupStyleChangeSchema, {
        groupId,
        changeType: StyleChangeType.DELETED,
        unsetPaths: [],
        kinds: [],
      }));
    } else if (before !== undefined && after !== undefined && !equals(GroupStyleEntrySchema, before, after)) {
      groupChanges.push(create(GroupStyleChangeSchema, {
        groupId,
        changeType: StyleChangeType.MODIFIED,
        after,
        unsetPaths: [],
        kinds: [],
      }));
    }
  }

  const annotationChanges: AnnotationStyleChange[] = [];
  const annotationIds = Array.from(new Set([...Object.keys(base.annotations), ...Object.keys(incoming.annotations)])).sort();
  for (const annotationId of annotationIds) {
    const before = base.annotations[annotationId];
    const after = incoming.annotations[annotationId];
    if (before === undefined && after !== undefined) {
      annotationChanges.push(create(AnnotationStyleChangeSchema, {
        annotationId,
        changeType: StyleChangeType.ADDED,
        after,
        unsetPaths: [],
        kinds: [],
      }));
    } else if (before !== undefined && after === undefined) {
      annotationChanges.push(create(AnnotationStyleChangeSchema, {
        annotationId,
        changeType: StyleChangeType.DELETED,
        unsetPaths: [],
        kinds: [],
      }));
    } else if (before !== undefined && after !== undefined && !equals(AnnotationEntrySchema, before, after)) {
      annotationChanges.push(create(AnnotationStyleChangeSchema, {
        annotationId,
        changeType: StyleChangeType.MODIFIED,
        after,
        unsetPaths: [],
        kinds: [],
      }));
    }
  }

  const canvasChanged = incoming.canvas !== undefined &&
    (base.canvas === undefined || !equals(CanvasStyleSchema, base.canvas, incoming.canvas));
  const themeChanged = incoming.themeRef !== undefined && incoming.themeRef !== base.themeRef;
  if (nodeChanges.length === 0 && edgeChanges.length === 0 && groupChanges.length === 0 &&
      annotationChanges.length === 0 && !canvasChanged && !themeChanged) {
    return undefined;
  }

  return create(StyleEditSchema, {
    schemaVersion: 1,
    nodeChanges,
    edgeChanges,
    groupChanges,
    annotationChanges,
    ...(canvasChanged ? { canvasAfter: incoming.canvas } : {}),
    ...(themeChanged ? { themeRefAfter: incoming.themeRef } : {}),
    author,
    timestampMs: BigInt(Date.now()),
    state: StyleEditState.PENDING,
  });
}
