// @generated by archebuild — do not edit. Regenerated each build.

export function restoreFromSnapshot(current: Stylesheet, snapshot: BeforeSnapshot): Stylesheet {
  throw new Error('not implemented');
}
import { BeforeSnapshot } from './undo_log';
import { StyleEdit } from '@archeglyph/proto/gen/style_pb';

export interface UndoEntry {
  beforeSnapshot: BeforeSnapshot;
  edit: StyleEdit;
  tsMs: number;
  coalesceKey?: string;
}
export function captureSnapshot(current: Stylesheet, edit: StyleEdit): BeforeSnapshot {
  throw new Error('not implemented');
}
export function pushUndoEntry(log: UndoEntry[], entry: UndoEntry, nowMs: number, coalesceWindowMs: number): UndoEntry[] {
  throw new Error('not implemented');
}
export interface BeforeSnapshot {
  nodes: Map<string, Option<NodeStyleEntry>>;
  edges: Map<string, Option<EdgeStyleEntry>>;
  groups: Map<string, Option<GroupStyleEntry>>;
  annotations: Map<string, Option<AnnotationEntry>>;
  canvasTouched: boolean;
  canvasBefore: Option<CanvasStyle>;
  themeRefTouched: boolean;
  themeRefBefore: Option<string>;
  pendingEditsBefore: archeglyph.style.v1.StyleEdit[];
}
