// @generated by archebuild — do not edit. Regenerated each build.

export function calloutSections(diagram: LaidOutDiagram, annotation: LaidOutAnnotation): Array<EdgeSection> {
  throw new Error('not implemented');
}
