// @generated by archebuild — do not edit. Regenerated each build.

import { Edge, Group, Node } from '@archeglyph/proto/gen/content_pb';
import { RefKind } from '@archeglyph/proto/gen/style_pb';
import { Ok, Result } from '@archeglyph/proto/util/result';
import { ValidateError } from '../validate_error';
import { ValidateRequest } from '../validate_request';
import { ValidateResponse } from '../validate_response';
import { Violation, ViolationKind, VIOLATION_KIND_ORDER } from '../violation';
import { Validator } from './';

export class ValidatorImpl implements Validator {
  validate(request: ValidateRequest): Result<ValidateResponse, ValidateError> {
    const graph = request.diagram.graph;
    const nodesMap: { [k: string]: Node } = graph !== undefined ? graph.nodes : {};
    const edgesMap: { [k: string]: Edge } = graph !== undefined ? graph.edges : {};
    const groupsMap: { [k: string]: Group } = graph !== undefined ? graph.groups : {};

    const sortedKeys = (obj: { [k: string]: unknown }): string[] => Object.keys(obj).sort();
    const normParent = (raw: string | undefined): string | undefined => {
      if (raw === undefined || raw === '') {
        return undefined;
      } else {
        return raw;
      }
    };

    const violations: Violation[] = [];

    // Check 1: Edge source/target reference existing nodes.
    const sortedEdgeIds = sortedKeys(edgesMap);
    for (const id of sortedEdgeIds) {
      const edge = edgesMap[id];
      if (nodesMap[edge.source] === undefined) {
        violations.push(Object.assign(new Violation(), {
          kind: ViolationKind.EDGE_SOURCE_MISSING,
          location: id,
          message: `edge '${id}' source '${edge.source}' does not reference an existing node`,
        }));
      } else {
        // valid source.
      }
      if (nodesMap[edge.target] === undefined) {
        violations.push(Object.assign(new Violation(), {
          kind: ViolationKind.EDGE_TARGET_MISSING,
          location: id,
          message: `edge '${id}' target '${edge.target}' does not reference an existing node`,
        }));
      } else {
        // valid target.
      }
    }

    // Check 2: Node.parent_group references existing group.
    const sortedNodeIds = sortedKeys(nodesMap);
    for (const id of sortedNodeIds) {
      const node = nodesMap[id];
      const p = normParent(node.parentGroup);
      if (p !== undefined && groupsMap[p] === undefined) {
        violations.push(Object.assign(new Violation(), {
          kind: ViolationKind.NODE_PARENT_GROUP_MISSING,
          location: id,
          message: `node '${id}' parent_group '${p}' does not reference an existing group`,
        }));
      } else {
        // valid or top-level.
      }
    }

    // Check 3: Group.parent_group references existing group AND chain is acyclic.
    const sortedGroupIds = sortedKeys(groupsMap);
    for (const id of sortedGroupIds) {
      const group = groupsMap[id];
      const p = normParent(group.parentGroup);
      if (p !== undefined && groupsMap[p] === undefined) {
        violations.push(Object.assign(new Violation(), {
          kind: ViolationKind.GROUP_PARENT_GROUP_MISSING,
          location: id,
          message: `group '${id}' parent_group '${p}' does not reference an existing group`,
        }));
      } else {
        // valid or top-level.
      }
    }

    // DFS cycle detection on group parent_group graph (WHITE/GRAY/BLACK coloring).
    type Color = 'white' | 'gray' | 'black';
    const colors = new Map<string, Color>();
    for (const id of sortedGroupIds) {
      colors.set(id, 'white');
    }

    const dfs = (id: string, stack: string[]): void => {
      colors.set(id, 'gray');
      stack.push(id);
      const group = groupsMap[id];
      const parentId = normParent(group.parentGroup);
      if (parentId !== undefined && groupsMap[parentId] !== undefined) {
        const parentColor = colors.get(parentId);
        if (parentColor === 'gray') {
          const cycleStart = stack.indexOf(parentId);
          const cyclePath = stack.slice(cycleStart);
          cyclePath.push(parentId);
          const location = cyclePath.join(', ');
          violations.push(Object.assign(new Violation(), {
            kind: ViolationKind.GROUP_CYCLE,
            location,
            message: `group cycle detected: ${location}`,
          }));
        } else if (parentColor === 'white') {
          dfs(parentId, stack);
        } else {
          // black — already fully processed, no cycle through this parent.
        }
      } else {
        // no parent or parent already reported missing — skip.
      }
      stack.pop();
      colors.set(id, 'black');
    };

    for (const id of sortedGroupIds) {
      if (colors.get(id) === 'white') {
        dfs(id, []);
      } else {
        // already visited.
      }
    }


    // The cascade looks style up from the graph, so a key naming no element
    // is never visited and styles nothing.
    const stylesheet = request.stylesheet;
    if (stylesheet !== undefined) {
      const checkStyleTargets = (
        entries: { [k: string]: unknown },
        targets: { [k: string]: unknown },
        kindLabel: string,
      ): void => {
        for (const key of sortedKeys(entries)) {
          if (targets[key] === undefined) {
            violations.push(Object.assign(new Violation(), {
              kind: ViolationKind.STYLE_TARGET_MISSING,
              location: key,
              message: `stylesheet styles ${kindLabel} '${key}', which the graph does not define`,
            }));
          }
        }
      };
      checkStyleTargets(stylesheet.nodes, nodesMap, 'node');
      checkStyleTargets(stylesheet.edges, edgesMap, 'edge');
      checkStyleTargets(stylesheet.groups, groupsMap, 'group');

      // An annotation key is its own id; only the anchor is a graph reference.
      for (const key of sortedKeys(stylesheet.annotations)) {
        const anchor = stylesheet.annotations[key].anchor;
        if (anchor === undefined) {
          continue;
        }
        const targets = anchor.refKind === RefKind.NODE ? nodesMap
          : anchor.refKind === RefKind.EDGE ? edgesMap
          : anchor.refKind === RefKind.GROUP ? groupsMap
          : undefined;
        if (targets === undefined || targets[anchor.refId] === undefined) {
          violations.push(Object.assign(new Violation(), {
            kind: ViolationKind.ANNOTATION_ANCHOR_MISSING,
            location: key,
            message: `annotation '${key}' anchors to '${anchor.refId}', which the graph does not define`,
          }));
        }
      }
    }

    violations.sort((a: Violation, b: Violation): number => {
      const kindDiff = VIOLATION_KIND_ORDER[a.kind] - VIOLATION_KIND_ORDER[b.kind];
      if (kindDiff !== 0) {
        return kindDiff;
      } else {
        return a.location < b.location ? -1 : a.location > b.location ? 1 : 0;
      }
    });

    return Ok(Object.assign(new ValidateResponse(), { violations }));
  }
}
