// @generated by archebuild — do not edit. Regenerated each build.

import { Result } from '@archeglyph/proto/util/result';
import { ValidateError } from '../validate_error';
import { ValidateRequest } from '../validate_request';
import { ValidateResponse } from '../validate_response';
import { Validator } from './';

export class ValidatorImpl implements Validator {
  validate(request: ValidateRequest): Result<ValidateResponse, ValidateError> { throw new Error('not implemented'); }
}
import { Result } from '@archeglyph/proto/util/result';
import { ValidateError } from '../validate_error';
import { ValidateRequest } from '../validate_request';
import { ValidateResponse } from '../validate_response';

export interface Validator {
  validate(request: ValidateRequest): Result<ValidateResponse, ValidateError>;
}
