// SPDX-License-Identifier: MPL-2.0

// @generated by archebuild — do not edit. Regenerated each build.

import { ValidateRequest } from '../validate_request';
import { ValidateResponse } from '../validate_response';
import { ValidateError } from '../validate_error';
import { Result } from '@archeglyph/proto/util/result';

export interface Validator {
  validate(request: ValidateRequest): Result<ValidateResponse, ValidateError>;
}
