// @generated by archebuild — do not edit. Regenerated each build.

import { LaidOutAnnotation } from '../laid_out_annotation';
import { LaidOutEdge } from '../laid_out_edge';
import { LaidOutGroup } from '../laid_out_group';
import { LaidOutNode } from '../laid_out_node';

export class LaidOutDiagram {
  id!: string;
  nodes: LaidOutNode[] = [];
  edges: LaidOutEdge[] = [];
  groups: LaidOutGroup[] = [];
  annotations: LaidOutAnnotation[] = [];
}
