// SPDX-License-Identifier: MPL-2.0
// @generated by archebuild — do not edit. Regenerated each build.

import { LaidOutAnnotation } from '../laid_out_annotation';
import { LaidOutEdge } from '../laid_out_edge';
import { LaidOutGroup } from '../laid_out_group';
import { LaidOutNode } from '../laid_out_node';
import { CanvasStyle } from '@archeglyph/proto/gen/style_pb';

export class LaidOutDiagram {
  id!: string;
  canvas!: CanvasStyle;
  nodes: Record<string, LaidOutNode> = {};
  edges: Record<string, LaidOutEdge> = {};
  groups: Record<string, LaidOutGroup> = {};
  annotations: Record<string, LaidOutAnnotation> = {};
}
