// @generated by archebuild — do not edit. Regenerated each build.

import { Stylesheet } from '@archeglyph/proto/gen/style_pb';

/**
 * Content assigned to an annotation before the user replaces it.
 *
 * An annotation's bounds are derived from its label, so an empty label would
 * make a newly-created annotation impossible to see or select.  This is
 * deliberately real content rather than a visual placeholder: it gives the
 * annotation a measurable label during creation and remains recoverable if
 * the user leaves it untouched.
 */
export const NEW_ANNOTATION_TEXT: string = 'New annotation';

export function newAnnotationId(stylesheet: Stylesheet, base: string): string {
  throw new Error('not implemented');
}
