// SPDX-License-Identifier: AGPL-3.0-or-later
// @generated by archebuild — do not edit. Regenerated each build.

import { Stylesheet, Vec2, Vec2Schema } from '@archeglyph/proto/gen/style_pb';
import { create } from '@bufbuild/protobuf';

/**
 * Content assigned to an annotation before the user replaces it.
 *
 * An annotation's bounds are derived from its label, so an empty label would
 * make a newly-created annotation impossible to see or select. This is
 * deliberately real content rather than a visual placeholder: it gives the
 * annotation a measurable label during creation and remains recoverable if
 * the user leaves it untouched.
 */
export const NEW_ANNOTATION_TEXT: string = 'New annotation';

/**
 * The box a new annotation occupies before the scene has measured its
 * label, in diagram units. 160 wide by 40 high.
 *
 * It is not written into the stylesheet and it is not the annotation's
 * real size -- layout derives that from the text. It exists only so the
 * inline editor has somewhere to render during the one scene rebuild
 * between creating an annotation and its bounds existing.
 */
export const NEW_ANNOTATION_SIZE: Vec2 = create(Vec2Schema, { x: 160, y: 40 });

export function newAnnotationId(stylesheet: Stylesheet, base: string): string {
  if (!Object.prototype.hasOwnProperty.call(stylesheet.annotations, base)) {
    return base;
  }

  let suffix = 2;
  while (Object.prototype.hasOwnProperty.call(stylesheet.annotations, `${base}-${suffix}`)) {
    suffix += 1;
  }

  return `${base}-${suffix}`;
}
