// SPDX-License-Identifier: AGPL-3.0-or-later
// @generated by archebuild — do not edit. Regenerated each build.

import { create } from '@bufbuild/protobuf';
import { type Localization, LocalizationSchema } from '@archeglyph/proto/gen/content_pb';
import { type AnnotationAnchor, type StyleEdit, type Stylesheet, type Vec2 } from '@archeglyph/proto/gen/style_pb';

import { patchAnnotationEntry } from './entry_patch';
import { annotationChange, styleEdit } from './edit_builder';

export function setAnnotationAnchorEdit(stylesheet: Stylesheet, id: string, anchor?: AnnotationAnchor): StyleEdit {
  throw new Error('not implemented');
}
export function setAnnotationTextEdit(stylesheet: Stylesheet, id: string, text: string): StyleEdit {
  const existing = stylesheet.annotations[id];
  const content = [...(existing?.content ?? [])];
  const canonicalIndex = content.findIndex((entry) => entry.locale === 'en');
  const canonical = localized(text)[0];
  if (canonicalIndex === -1) {
    content.push(canonical);
  } else {
    content[canonicalIndex] = canonical;
  }

  return styleEdit({
    annotationChanges: [
      annotationChange(id, patchAnnotationEntry(existing, { id, content })),
    ],
  });
}
export function addAnnotationEdit(stylesheet: Stylesheet, id: string, position: Vec2, text: string): StyleEdit {
  throw new Error('not implemented');
}
export function deleteAnnotationEdit(stylesheet: Stylesheet, id: string): StyleEdit {
  return styleEdit({
    annotationChanges: [annotationChange(id)],
  });
}
export function localized(text: string): Array<Localization> {
  return [create(LocalizationSchema, { locale: 'en', source: text })];
}
