// SPDX-License-Identifier: AGPL-3.0-or-later
// @generated by archebuild — do not edit. Regenerated each build.

import { Localization, LocalizationSchema } from '@archeglyph/proto/gen/content_pb';
import {
  AnnotationAnchor,
  AnnotationEntrySchema,
  StyleEdit,
  Stylesheet,
  Vec2,
  Vec2Schema
} from '@archeglyph/proto/gen/style_pb';
import { create } from '@bufbuild/protobuf';
import { newAnnotationId } from './annotation_defaults';
import { annotationChange, styleEdit } from './edit_builder';
import { patchAnnotationEntry } from './entry_patch';

export function setAnnotationAnchorEdit(stylesheet: Stylesheet, id: string, anchor?: AnnotationAnchor): StyleEdit {
  const existing = stylesheet.annotations[id];
  const patched = patchAnnotationEntry(existing, { id, ...(anchor === undefined ? {} : { anchor }) });
  const after = anchor === undefined
    ? create(AnnotationEntrySchema, { ...patched, anchor: undefined })
    : patched;
  const change = annotationChange(
    id,
    after,
  );

  // An absent optional proto field is distinct from leaving the field
  // untouched.  Record the explicit clear on the change so applying the edit
  // can detach an annotation that was previously anchored.
  if (anchor === undefined) {
    change.unsetPaths.push('anchor');
  }

  return styleEdit({ annotationChanges: [change] });
}

export function setAnnotationTextEdit(stylesheet: Stylesheet, id: string, text: string): StyleEdit {
  const existing = stylesheet.annotations[id];
  const content = [...(existing?.content ?? [])];
  const canonicalIndex = content.findIndex((entry) => entry.locale === 'en');
  const canonical = localized(text)[0];
  if (canonicalIndex === -1) {
    content.push(canonical);
  } else {
    content[canonicalIndex] = canonical;
  }

  return styleEdit({
    annotationChanges: [
      annotationChange(id, patchAnnotationEntry(existing, { id, content })),
    ],
  });
}

export function addAnnotationEdit(stylesheet: Stylesheet, id: string, position: Vec2, text: string): StyleEdit {
  const annotation = patchAnnotationEntry(undefined, {
    id,
    content: localized(text),
    position,
  });

  return styleEdit({
    annotationChanges: [annotationChange(id, annotation)],
    description: 'Add annotation',
  });
}

export function deleteAnnotationEdit(stylesheet: Stylesheet, id: string): StyleEdit {
  return styleEdit({
    annotationChanges: [annotationChange(id)],
  });
}

export function duplicateAnnotationEdit(stylesheet: Stylesheet, id: string): StyleEdit {
  const existing = stylesheet.annotations[id];
  const duplicateId = newAnnotationId(stylesheet, id);
  const position = existing?.layout?.position;
  const duplicate = patchAnnotationEntry(existing, {
    id: duplicateId,
    position: create(Vec2Schema, {
      x: (position?.x ?? 0) + 16,
      y: (position?.y ?? 0) + 16,
    }),
  });

  return styleEdit({
    annotationChanges: [annotationChange(duplicateId, duplicate)],
    description: 'Duplicate annotation',
  });
}

export function localized(text: string): Array<Localization> {
  return [create(LocalizationSchema, { locale: 'en', source: text })];
}
