// @generated by archebuild — do not edit. Regenerated each build.

import { create } from '@bufbuild/protobuf';
import {
<<<<<<< HEAD
  EdgeStyleChange,
  EdgeStyleChangeSchema,
  EdgeStyleEntry,
  StyleChangeType,
  StyleEdit,
=======
  StyleEdit,
  StyleEditSchema,
  StyleEditState,
>>>>>>> 1f88fcd65eae7b960808294cf9fdd99ab4b2bf5b
} from '@archeglyph/proto/gen/style_pb';

export function edgeChange(edgeId: string, after?: EdgeStyleEntry): EdgeStyleChange {
  return create(EdgeStyleChangeSchema, {
    edgeId,
    changeType: StyleChangeType.ADDED,
    after,
  });
}
export function nodeChange(nodeId: string, after?: NodeStyleEntry): NodeStyleChange {
  return create(NodeStyleChangeSchema, {
    nodeId,
    changeType: StyleChangeType.MODIFIED,
    ...(after === undefined ? {} : { after }),
  });
}
export function annotationChange(annotationId: string, after?: AnnotationEntry): AnnotationStyleChange {
  throw new Error('not implemented');
}
export function groupChange(groupId: string, after?: GroupStyleEntry): GroupStyleChange {
  throw new Error('not implemented');
}
import { AnnotationStyleChange } from '@archeglyph/proto/gen/style_pb';
import { GroupStyleChange } from '@archeglyph/proto/gen/style_pb';
import { NodeStyleChange } from '@archeglyph/proto/gen/style_pb';
import { NodeStyleChangeSchema } from '@archeglyph/proto/gen/style_pb';
import { NodeStyleEntry } from '@archeglyph/proto/gen/style_pb';
import { StyleChangeType } from '@archeglyph/proto/gen/style_pb';
import { create } from '@bufbuild/protobuf';

export interface EditParts {
  nodeChanges?: Array<NodeStyleChange>;
  edgeChanges?: Array<EdgeStyleChange>;
  groupChanges?: Array<GroupStyleChange>;
  annotationChanges?: Array<AnnotationStyleChange>;
  description?: string;
}
export function styleEdit(parts: EditParts): StyleEdit {
  return create(StyleEditSchema, {
    schemaVersion: 1,
    ...(parts.nodeChanges === undefined ? {} : { nodeChanges: parts.nodeChanges }),
    ...(parts.edgeChanges === undefined ? {} : { edgeChanges: parts.edgeChanges }),
    ...(parts.groupChanges === undefined ? {} : { groupChanges: parts.groupChanges }),
    ...(parts.annotationChanges === undefined ? {} : { annotationChanges: parts.annotationChanges }),
    author: 'user:local',
    description: parts.description,
    timestampMs: BigInt(Date.now()),
    state: StyleEditState.APPLIED,
  });
}
