// @generated by archebuild — do not edit. Regenerated each build.

import { create } from '@bufbuild/protobuf';
<<<<<<< HEAD
=======
import {
  StyleEdit,
  StyleEditSchema,
  StyleEditState,
} from '@archeglyph/proto/gen/style_pb';
>>>>>>> 6ab3d382b36b167f57fd7d4dcad25fecff98f184

export function edgeChange(edgeId: string, after?: EdgeStyleEntry): EdgeStyleChange {
  throw new Error('not implemented');
}
export function nodeChange(nodeId: string, after?: NodeStyleEntry): NodeStyleChange {
  return create(NodeStyleChangeSchema, {
    nodeId,
    changeType: StyleChangeType.MODIFIED,
    ...(after === undefined ? {} : { after }),
  });
}
export function annotationChange(annotationId: string, after?: AnnotationEntry): AnnotationStyleChange {
  return create(AnnotationStyleChangeSchema, {
    annotationId,
    changeType: StyleChangeType.ADDED,
    ...(after === undefined ? {} : { after }),
    unsetPaths: [],
    kinds: [],
  });
}
export function groupChange(groupId: string, after?: GroupStyleEntry): GroupStyleChange {
  throw new Error('not implemented');
}
import { AnnotationStyleChange } from '@archeglyph/proto/gen/style_pb';
import { AnnotationStyleChangeSchema, StyleChangeType } from '@archeglyph/proto/gen/style_pb';
import type { AnnotationEntry } from '@archeglyph/proto/gen/style_pb';
import { EdgeStyleChange } from '@archeglyph/proto/gen/style_pb';
import { GroupStyleChange } from '@archeglyph/proto/gen/style_pb';
import { NodeStyleChange } from '@archeglyph/proto/gen/style_pb';
import { NodeStyleChangeSchema } from '@archeglyph/proto/gen/style_pb';
import { NodeStyleEntry } from '@archeglyph/proto/gen/style_pb';
import { StyleChangeType } from '@archeglyph/proto/gen/style_pb';
import { create } from '@bufbuild/protobuf';

export interface EditParts {
  nodeChanges?: Array<NodeStyleChange>;
  edgeChanges?: Array<EdgeStyleChange>;
  groupChanges?: Array<GroupStyleChange>;
  annotationChanges?: Array<AnnotationStyleChange>;
  description?: string;
}
export function styleEdit(parts: EditParts): StyleEdit {
  return create(StyleEditSchema, {
    schemaVersion: 1,
    ...(parts.nodeChanges === undefined ? {} : { nodeChanges: parts.nodeChanges }),
    ...(parts.edgeChanges === undefined ? {} : { edgeChanges: parts.edgeChanges }),
    ...(parts.groupChanges === undefined ? {} : { groupChanges: parts.groupChanges }),
    ...(parts.annotationChanges === undefined ? {} : { annotationChanges: parts.annotationChanges }),
    author: 'user:local',
    description: parts.description,
    timestampMs: BigInt(Date.now()),
    state: StyleEditState.APPLIED,
  });
}
