// SPDX-License-Identifier: AGPL-3.0-or-later
// @generated by archebuild — do not edit. Regenerated each build.

import {
  AnnotationEntry,
  AnnotationStyleChange,
  AnnotationStyleChangeSchema,
  EdgeStyleChange,
  EdgeStyleChangeSchema,
  EdgeStyleEntry,
  GroupStyleChange,
  GroupStyleChangeSchema,
  GroupStyleEntry,
  NodeStyleChange,
  NodeStyleChangeSchema,
  NodeStyleEntry,
  StyleChangeType,
  StyleEdit,
  StyleEditSchema,
  StyleEditState
} from '@archeglyph/proto/gen/style_pb';
import { create } from '@bufbuild/protobuf';

// NOTE: every *StyleChange carries `unset_paths` (proto/style.proto:514,
// "explicit field-clearing"), and NOTHING in this repo implements it --
// applyMapChanges ignores the field entirely. Do not reach for it to clear a
// field; build an entry that lacks the field instead (see layout_command's
// withoutNodePosition). The empty arrays below are only there because the
// generated code wrote them.
export function edgeChange(edgeId: string, after?: EdgeStyleEntry): EdgeStyleChange {
  return create(EdgeStyleChangeSchema, {
    edgeId,
    // An absent `after` means "drop this entry", which the schema spells
    // DELETED -- applyMapChanges only removes on that change type, so a
    // MODIFIED change with no entry is a silent no-op.
    changeType: after === undefined ? StyleChangeType.DELETED : StyleChangeType.MODIFIED,
    ...(after === undefined ? {} : { after }),
    unsetPaths: [],
    kinds: [],
  });
}

export function nodeChange(nodeId: string, after?: NodeStyleEntry): NodeStyleChange {
  return create(NodeStyleChangeSchema, {
    nodeId,
    // An absent `after` means "drop this entry", which the schema spells
    // DELETED -- applyMapChanges only removes on that change type, so a
    // MODIFIED change with no entry is a silent no-op.
    changeType: after === undefined ? StyleChangeType.DELETED : StyleChangeType.MODIFIED,
    ...(after === undefined ? {} : { after }),
    unsetPaths: [],
    kinds: [],
  });
}

export function annotationChange(annotationId: string, after?: AnnotationEntry): AnnotationStyleChange {
  return create(AnnotationStyleChangeSchema, {
    annotationId,
    changeType: after === undefined ? StyleChangeType.DELETED : StyleChangeType.ADDED,
    ...(after === undefined ? {} : { after }),
    unsetPaths: [],
    kinds: [],
  });
}

export function groupChange(groupId: string, after?: GroupStyleEntry): GroupStyleChange {
  return create(GroupStyleChangeSchema, {
    groupId,
    // An absent `after` means "drop this entry", which the schema spells
    // DELETED -- applyMapChanges only removes on that change type, so a
    // MODIFIED change with no entry is a silent no-op.
    changeType: after === undefined ? StyleChangeType.DELETED : StyleChangeType.MODIFIED,
    ...(after === undefined ? {} : { after }),
    unsetPaths: [],
    kinds: [],
  });
}

export interface EditParts {
  nodeChanges?: Array<NodeStyleChange>;
  edgeChanges?: Array<EdgeStyleChange>;
  groupChanges?: Array<GroupStyleChange>;
  annotationChanges?: Array<AnnotationStyleChange>;
  description?: string;
}

export function styleEdit(parts: EditParts): StyleEdit {
  return create(StyleEditSchema, {
    schemaVersion: 1,
    ...(parts.nodeChanges === undefined ? {} : { nodeChanges: parts.nodeChanges }),
    ...(parts.edgeChanges === undefined ? {} : { edgeChanges: parts.edgeChanges }),
    ...(parts.groupChanges === undefined ? {} : { groupChanges: parts.groupChanges }),
    ...(parts.annotationChanges === undefined ? {} : { annotationChanges: parts.annotationChanges }),
    author: 'user:local',
    ...(parts.description === undefined ? {} : { description: parts.description }),
    timestampMs: BigInt(Date.now()),
    state: StyleEditState.APPLIED,
  });
}
