// @generated by archebuild — do not edit. Regenerated each build.

import { create } from '@bufbuild/protobuf';

import { AnnotationAnchor } from '@archeglyph/proto/gen/style_pb';
import { AnnotationEntry, AnnotationEntrySchema, AnnotationLayoutSchema } from '@archeglyph/proto/gen/style_pb';
import { Glyph1D } from '@archeglyph/proto/gen/style_pb';
import { Glyph2D } from '@archeglyph/proto/gen/style_pb';
import { Localization } from '@archeglyph/proto/gen/content_pb';
import { Typography } from '@archeglyph/proto/gen/style_pb';
import { Vec2 } from '@archeglyph/proto/gen/style_pb';

export interface AnnotationEntryPatch {
  id: string;
  content?: Array<Localization>;
  anchor?: AnnotationAnchor;
  position?: Vec2;
  size?: Vec2;
  rotation?: number;
  shape?: Glyph2D;
  typography?: Typography;
  callout?: Glyph1D;
  component?: string;
}
export function patchNodeEntry(existing: NodeStyleEntry | undefined, patch: NodeEntryPatch): NodeStyleEntry {
  throw new Error('not implemented');
}
export function patchAnnotationEntry(existing: AnnotationEntry | undefined, patch: AnnotationEntryPatch): AnnotationEntry {
  const hasLayoutPatch: boolean = patch.position !== undefined || patch.size !== undefined || patch.rotation !== undefined;
  const layout = hasLayoutPatch
    ? create(AnnotationLayoutSchema, {
        position: patch.position !== undefined ? patch.position : existing?.layout?.position,
        size: patch.size !== undefined ? patch.size : existing?.layout?.size,
        rotation: patch.rotation !== undefined ? patch.rotation : existing?.layout?.rotation,
      })
    : existing?.layout;

  return create(AnnotationEntrySchema, {
    id: patch.id,
    content: patch.content !== undefined ? patch.content : existing?.content ?? [],
    anchor: patch.anchor !== undefined ? patch.anchor : existing?.anchor,
    layout,
    shape: patch.shape !== undefined ? patch.shape : existing?.shape,
    typography: patch.typography !== undefined ? patch.typography : existing?.typography,
    callout: patch.callout !== undefined ? patch.callout : existing?.callout,
    component: patch.component !== undefined ? patch.component : existing?.component,
    tags: existing?.tags ?? {},
  });
}
import { Glyph2D } from '@archeglyph/proto/gen/style_pb';
import { GroupLabelPosition } from '@archeglyph/proto/gen/style_pb';
import { GroupRenderMode } from '@archeglyph/proto/gen/style_pb';
import { Typography } from '@archeglyph/proto/gen/style_pb';
import { Vec2 } from '@archeglyph/proto/gen/style_pb';

export interface GroupEntryPatch {
  position?: Vec2;
  size?: Vec2;
  padding?: number;
  renderMode?: GroupRenderMode;
  labelPosition?: GroupLabelPosition;
  shape?: Glyph2D;
  typography?: Typography;
  component?: string;
}
import { EdgeRouting } from '@archeglyph/proto/gen/style_pb';
import { Glyph1D } from '@archeglyph/proto/gen/style_pb';
import { Typography } from '@archeglyph/proto/gen/style_pb';
import { Vec2 } from '@archeglyph/proto/gen/style_pb';

export interface EdgeEntryPatch {
  routing?: EdgeRouting;
  waypoints?: Array<Vec2>;
  connection?: Glyph1D;
  typography?: Typography;
  component?: string;
}
import { Glyph2D } from '@archeglyph/proto/gen/style_pb';
import { NodeVisibility } from '@archeglyph/proto/gen/style_pb';
import { Typography } from '@archeglyph/proto/gen/style_pb';
import { Vec2 } from '@archeglyph/proto/gen/style_pb';

export interface NodeEntryPatch {
  position?: Vec2;
  size?: Vec2;
  rotation?: number;
  shape?: Glyph2D;
  typography?: Typography;
  component?: string;
  visibility?: NodeVisibility;
}
export function patchEdgeEntry(existing: EdgeStyleEntry | undefined, patch: EdgeEntryPatch): EdgeStyleEntry {
  throw new Error('not implemented');
}
export function patchGroupEntry(existing: GroupStyleEntry | undefined, patch: GroupEntryPatch): GroupStyleEntry {
  throw new Error('not implemented');
}
