// SPDX-License-Identifier: MPL-2.0
// @generated by archebuild — do not edit. Regenerated each build.

import { Localization } from '@archeglyph/proto/gen/content_pb';
import {
  AnnotationAnchor,
  AnnotationEntry,
  AnnotationEntrySchema,
  AnnotationLayoutSchema,
  EdgeLayoutSchema,
  EdgeRouting,
  EdgeStyleEntry,
  EdgeStyleEntrySchema,
  Glyph1D,
  Glyph2D,
  GroupLabelPosition,
  GroupLayoutSchema,
  GroupRenderMode,
  GroupStyleEntry,
  GroupStyleEntrySchema,
  NodeLayoutSchema,
  NodeStyleEntry,
  NodeStyleEntrySchema,
  NodeVisibility,
  Typography,
  Vec2
} from '@archeglyph/proto/gen/style_pb';
import { create } from '@bufbuild/protobuf';

/**
 * The fields of a protobuf message as a plain init object.
 *
 * protobuf-es `MessageInit<T>` accepts either a complete message (with a
 * required `$typeName`) or a plain object that has none. Spreading
 * `existing ?? {}` produces neither — `$typeName` comes out optional — and TS
 * rejects it against both halves of the union. Strip it and let `create`
 * stamp a fresh one.
 */
export function initOf<T extends { $typeName: string }>(message: T | undefined): Record<string, unknown> {
  if (message === undefined) {
    return {};
  }
  const rest: Record<string, unknown> = { ...message };
  delete rest['$typeName'];
  delete rest['$unknown'];
  return rest;
}

export interface AnnotationEntryPatch {
  content?: Array<Localization>; anchor?: AnnotationAnchor; position?: Vec2;
  size?: Vec2; rotation?: number; shape?: Glyph2D; typography?: Typography;
  callout?: Glyph1D; component?: string;
}

export function patchNodeEntry(existing: NodeStyleEntry | undefined, patch: NodeEntryPatch): NodeStyleEntry {
  const hasLayoutPatch = patch.position !== undefined || patch.size !== undefined || patch.rotation !== undefined;
  return create(NodeStyleEntrySchema, { ...initOf(existing), ...(hasLayoutPatch ? { layout: create(NodeLayoutSchema, {
    ...initOf(existing?.layout), ...(patch.position === undefined ? {} : { position: patch.position }),
    ...(patch.size === undefined ? {} : { size: patch.size }), ...(patch.rotation === undefined ? {} : { rotation: patch.rotation }),
  }) } : {}), ...(patch.shape === undefined ? {} : { shape: patch.shape }),
  ...(patch.typography === undefined ? {} : { typography: patch.typography }),
  ...(patch.component === undefined ? {} : { component: patch.component }),
  ...(patch.visibility === undefined ? {} : { visibility: patch.visibility }) });
}

export function patchAnnotationEntry(existing: AnnotationEntry | undefined, patch: AnnotationEntryPatch): AnnotationEntry {
  const hasLayoutPatch = patch.position !== undefined || patch.size !== undefined || patch.rotation !== undefined;
  return create(AnnotationEntrySchema, { ...initOf(existing),
    ...(patch.content === undefined ? {} : { content: patch.content }), ...(patch.anchor === undefined ? {} : { anchor: patch.anchor }),
    ...(hasLayoutPatch ? { layout: create(AnnotationLayoutSchema, { ...initOf(existing?.layout),
      ...(patch.position === undefined ? {} : { position: patch.position }), ...(patch.size === undefined ? {} : { size: patch.size }),
      ...(patch.rotation === undefined ? {} : { rotation: patch.rotation }) }) } : {}),
    ...(patch.shape === undefined ? {} : { shape: patch.shape }), ...(patch.typography === undefined ? {} : { typography: patch.typography }),
    ...(patch.callout === undefined ? {} : { callout: patch.callout }), ...(patch.component === undefined ? {} : { component: patch.component }) });
}

export interface GroupEntryPatch { position?: Vec2; size?: Vec2; padding?: number; renderMode?: GroupRenderMode; labelPosition?: GroupLabelPosition; shape?: Glyph2D; typography?: Typography; component?: string; }

export interface EdgeEntryPatch { routing?: EdgeRouting; waypoints?: Array<Vec2>; connection?: Glyph1D; typography?: Typography; component?: string; }

export interface NodeEntryPatch { position?: Vec2; size?: Vec2; rotation?: number; shape?: Glyph2D; typography?: Typography; component?: string; visibility?: NodeVisibility; }

export function patchEdgeEntry(existing: EdgeStyleEntry | undefined, patch: EdgeEntryPatch): EdgeStyleEntry {
  const hasLayoutPatch = patch.routing !== undefined || patch.waypoints !== undefined;
  return create(EdgeStyleEntrySchema, { ...initOf(existing), ...(hasLayoutPatch ? { layout: create(EdgeLayoutSchema, { ...initOf(existing?.layout),
    ...(patch.routing === undefined ? {} : { routing: patch.routing }), ...(patch.waypoints === undefined ? {} : { waypoints: patch.waypoints }) }) } : {}),
    ...(patch.connection === undefined ? {} : { connection: patch.connection }), ...(patch.typography === undefined ? {} : { typography: patch.typography }),
    ...(patch.component === undefined ? {} : { component: patch.component }) });
}

export function patchGroupEntry(existing: GroupStyleEntry | undefined, patch: GroupEntryPatch): GroupStyleEntry {
  const hasLayoutPatch = patch.position !== undefined || patch.size !== undefined || patch.padding !== undefined || patch.renderMode !== undefined || patch.labelPosition !== undefined;
  return create(GroupStyleEntrySchema, { ...initOf(existing), ...(hasLayoutPatch ? { layout: create(GroupLayoutSchema, { ...initOf(existing?.layout),
    ...(patch.position === undefined ? {} : { position: patch.position }), ...(patch.size === undefined ? {} : { size: patch.size }),
    ...(patch.padding === undefined ? {} : { padding: patch.padding }), ...(patch.renderMode === undefined ? {} : { renderMode: patch.renderMode }),
    ...(patch.labelPosition === undefined ? {} : { labelPosition: patch.labelPosition }) }) } : {}),
    ...(patch.shape === undefined ? {} : { shape: patch.shape }), ...(patch.typography === undefined ? {} : { typography: patch.typography }),
    ...(patch.component === undefined ? {} : { component: patch.component }) });
}
