// SPDX-License-Identifier: AGPL-3.0-or-later
// @generated by archebuild — do not edit. Regenerated each build.

import { Glyph2D } from '@archeglyph/proto/gen/style_pb';
import { Typography } from '@archeglyph/proto/gen/style_pb';
import { type StyleEdit, type Stylesheet } from '@archeglyph/proto/gen/style_pb';

import { patchAnnotationEntry, patchGroupEntry, patchNodeEntry } from './entry_patch';
import { annotationChange, groupChange, nodeChange, styleEdit } from './edit_builder';

export interface NodeGlyphPatch {
  shape?: Glyph2D;
  typography?: Typography;
  component?: string;
}
export function setAnnotationGlyphEdit(stylesheet: Stylesheet, annotationId: string, patch: AnnotationGlyphPatch): StyleEdit {
  const existing = stylesheet.annotations[annotationId];
  return styleEdit({
    annotationChanges: [
      annotationChange(annotationId, patchAnnotationEntry(existing, { id: annotationId, ...patch })),
    ],
  });
}
import { Glyph1D } from '@archeglyph/proto/gen/style_pb';
import { Glyph2D } from '@archeglyph/proto/gen/style_pb';
import { Typography } from '@archeglyph/proto/gen/style_pb';

export interface AnnotationGlyphPatch {
  shape?: Glyph2D;
  typography?: Typography;
  callout?: Glyph1D;
  component?: string;
}
import { Glyph1D } from '@archeglyph/proto/gen/style_pb';
import { Typography } from '@archeglyph/proto/gen/style_pb';

export interface EdgeGlyphPatch {
  connection?: Glyph1D;
  typography?: Typography;
  component?: string;
}
export function setGroupGlyphEdit(stylesheet: Stylesheet, groupId: string, patch: GroupGlyphPatch): StyleEdit {
  const existing = stylesheet.groups[groupId];
  return styleEdit({
    groupChanges: [
      groupChange(groupId, patchGroupEntry(existing, patch)),
    ],
    description: 'Set glyph on group',
  });
}
import { Glyph2D } from '@archeglyph/proto/gen/style_pb';
import { GroupLabelPosition } from '@archeglyph/proto/gen/style_pb';
import { GroupRenderMode } from '@archeglyph/proto/gen/style_pb';
import { Typography } from '@archeglyph/proto/gen/style_pb';

export interface GroupGlyphPatch {
  shape?: Glyph2D;
  typography?: Typography;
  component?: string;
  renderMode?: GroupRenderMode;
  labelPosition?: GroupLabelPosition;
}
export function setNodesGlyphEdit(stylesheet: Stylesheet, nodeIds: Array<string>, patch: NodeGlyphPatch): StyleEdit {
  const nodeChanges = nodeIds.map((nodeId) =>
    nodeChange(nodeId, patchNodeEntry(stylesheet.nodes[nodeId], patch)),
  );

  return styleEdit({
    nodeChanges,
    description: 'Set glyph on selected nodes',
  });
}
export function setNodeGlyphEdit(stylesheet: Stylesheet, nodeId: string, patch: NodeGlyphPatch): StyleEdit {
  throw new Error('not implemented');
}
export function setEdgeGlyphEdit(stylesheet: Stylesheet, edgeId: string, patch: EdgeGlyphPatch): StyleEdit {
  throw new Error('not implemented');
}
