// SPDX-License-Identifier: MPL-2.0
// @generated by archebuild — do not edit. Regenerated each build.

import {
  Glyph1D,
  Glyph2D,
  GroupLabelPosition,
  GroupRenderMode,
  StyleEdit,
  Stylesheet,
  Typography,
} from '@archeglyph/proto/gen/style_pb';
import { annotationChange, edgeChange, groupChange, nodeChange, styleEdit } from './edit_builder';
import { patchAnnotationEntry, patchEdgeEntry, patchGroupEntry, patchNodeEntry } from './entry_patch';

export interface NodeGlyphPatch {
  shape?: Glyph2D;
  typography?: Typography;
  component?: string;
}

// `after` merges, so clearing a field takes its path in `unsetPaths`.
export function setAnnotationsGlyphEdit(stylesheet: Stylesheet, annotationIds: ReadonlyArray<string>, patch: AnnotationGlyphPatch, unsetPaths: ReadonlyArray<string> = []): StyleEdit {
  return styleEdit({
    annotationChanges: annotationIds.map((annotationId) =>
      annotationChange(annotationId, patchAnnotationEntry(stylesheet.annotations[annotationId], patch), unsetPaths),
    ),
  });
}

export interface AnnotationGlyphPatch {
  shape?: Glyph2D;
  typography?: Typography;
  callout?: Glyph1D;
  component?: string;
}

export interface EdgeGlyphPatch {
  connection?: Glyph1D;
  typography?: Typography;
  component?: string;
}

export function setGroupsGlyphEdit(stylesheet: Stylesheet, groupIds: ReadonlyArray<string>, patch: GroupGlyphPatch, unsetPaths: ReadonlyArray<string> = []): StyleEdit {
  return styleEdit({
    groupChanges: groupIds.map((groupId) =>
      groupChange(groupId, patchGroupEntry(stylesheet.groups[groupId], patch), unsetPaths),
    ),
    description: 'Set glyph on selected groups',
  });
}

export interface GroupGlyphPatch {
  shape?: Glyph2D;
  typography?: Typography;
  component?: string;
  renderMode?: GroupRenderMode;
  labelPosition?: GroupLabelPosition;
}

export function setNodesGlyphEdit(stylesheet: Stylesheet, nodeIds: ReadonlyArray<string>, patch: NodeGlyphPatch, unsetPaths: ReadonlyArray<string> = []): StyleEdit {
  return styleEdit({
    nodeChanges: nodeIds.map((nodeId) =>
      nodeChange(nodeId, patchNodeEntry(stylesheet.nodes[nodeId], patch), unsetPaths),
    ),
    description: 'Set glyph on selected nodes',
  });
}

export function setEdgesGlyphEdit(stylesheet: Stylesheet, edgeIds: ReadonlyArray<string>, patch: EdgeGlyphPatch, unsetPaths: ReadonlyArray<string> = []): StyleEdit {
  return styleEdit({
    edgeChanges: edgeIds.map((edgeId) =>
      edgeChange(edgeId, patchEdgeEntry(stylesheet.edges[edgeId], patch), unsetPaths),
    ),
    description: 'Set glyph on selected edges',
  });
}
