// SPDX-License-Identifier: MPL-2.0

// @generated by archebuild — do not edit. Regenerated each build.

import { LaidOutDiagram } from '@archeglyph/core/layout/laid_out_diagram';
import {
  GroupStyleChange,
  GroupStyleEntry,
  GroupStyleEntrySchema,
  NodeStyleChange,
  NodeStyleEntry,
  NodeStyleEntrySchema,
  StyleEdit,
  StyleEditSchema,
  Stylesheet,
  Vec2,
  Vec2Schema
} from '@archeglyph/proto/gen/style_pb';
import { create } from '@bufbuild/protobuf';
import { groupChange, nodeChange, styleEdit } from './edit_builder';
import { initOf, patchGroupEntry, patchNodeEntry } from './entry_patch';
import { ElementMove } from './move';

/**
 * Which path unpinning clears. `layout` whole when position was all it held,
 * so an emptied layout does not linger; otherwise just the position.
 */
function nodePositionPath(existing: NodeStyleEntry | undefined): ReadonlyArray<string> {
  const layout = existing?.layout;
  const keepsLayout = layout !== undefined
    && (layout.size !== undefined || layout.rotation !== undefined);
  return [keepsLayout ? 'layout.position' : 'layout'];
}

function groupPositionPath(existing: GroupStyleEntry | undefined): ReadonlyArray<string> {
  const layout = existing?.layout;
  const keepsLayout = layout !== undefined
    && (layout.size !== undefined || layout.padding !== undefined
      || layout.renderMode !== undefined || layout.labelPosition !== undefined);
  return [keepsLayout ? 'layout.position' : 'layout'];
}

export function unpinAllEdit(stylesheet: Stylesheet): StyleEdit {
  return styleEdit({
    nodeChanges: Object.keys(stylesheet.nodes).map((nodeId) =>
      nodeChange(nodeId, create(NodeStyleEntrySchema, {}), nodePositionPath(stylesheet.nodes[nodeId]))),
    groupChanges: Object.keys(stylesheet.groups).map((groupId) =>
      groupChange(groupId, create(GroupStyleEntrySchema, {}), groupPositionPath(stylesheet.groups[groupId]))),
    description: 'Unpin all nodes and groups',
  });
}

export function unpinElementsEdit(stylesheet: Stylesheet, refs: Array<ElementMove>): StyleEdit {
  const nodeIds = refs.filter((ref) => ref.kind === 'node').map((ref) => ref.id);
  const groupIds = refs.filter((ref) => ref.kind === 'group').map((ref) => ref.id);
  // Annotations are always explicitly positioned (design.md) -- there is no
  // auto-layout for them to fall back to, so unpinning one would mean losing
  // its position with nothing to replace it. Skipped rather than rejected, so
  // a mixed selection still unpins the parts that can be.
  return styleEdit({
    nodeChanges: nodeIds.map((nodeId) =>
      nodeChange(nodeId, create(NodeStyleEntrySchema, {}), nodePositionPath(stylesheet.nodes[nodeId]))),
    groupChanges: groupIds.map((groupId) =>
      groupChange(groupId, create(GroupStyleEntrySchema, {}), groupPositionPath(stylesheet.groups[groupId]))),
    description: 'Unpin selection',
  });
}

/**
 * Parent-relative position for an element the layout placed at `position`.
 *
 * Layout coordinates are canvas-absolute while style positions are relative
 * to the immediate parent group, so every pin has to be converted back before
 * it is written to the stylesheet.
 */
function parentRelative(
  groupsById: Record<string, { position: { x: number; y: number } }>,
  position: { x: number; y: number },
  parentId: string | undefined,
): Vec2 {
  const parent = parentId === undefined ? undefined : groupsById[parentId];
  return parent === undefined
    ? create(Vec2Schema, { x: position.x, y: position.y })
    : create(Vec2Schema, {
        x: position.x - parent.position.x,
        y: position.y - parent.position.y,
      });
}

export function pinAllEdit(stylesheet: Stylesheet, diagram: LaidOutDiagram): StyleEdit {
  const nodeChanges = Object.values(diagram.nodes).map((node) =>
    nodeChange(
      node.id,
      patchNodeEntry(stylesheet.nodes[node.id], {
        position: parentRelative(diagram.groups, node.position, node.parentGroup),
      }),
    ),
  );
  const groupChanges = Object.values(diagram.groups).map((group) =>
    groupChange(
      group.id,
      patchGroupEntry(stylesheet.groups[group.id], {
        position: parentRelative(diagram.groups, group.position, group.parentGroup),
      }),
    ),
  );

  return styleEdit({
    nodeChanges,
    groupChanges,
    description: 'Pin all laid-out elements',
  });
}

/**
 * `edit` with a position written for every node and group that does not have
 * one yet, taken from where the layout currently puts them.
 *
 * This is pin-on-touch (editor-ui-review.md §5.2). A diagram with no explicit
 * positions is arranged by ELK; the moment one element gets a position, the
 * layout engine stops calling ELK for placement and seeds the rest beside the
 * pinned one instead -- so moving a single node would rearrange the whole
 * diagram. Materializing the current arrangement into the SAME edit keeps
 * everything else exactly where the user sees it, and keeps it to one undo
 * entry.
 *
 * The materialized changes come FIRST so the caller's own changes win for any
 * element they also touch: applyMapChanges merges each change over the one
 * before it, so a field the caller names beats the materialized position while
 * a field it leaves alone still gets pinned.
 *
 * Elements already carrying a position in the stylesheet are skipped, so this
 * is a no-op from the second gesture onwards.
 */
export function withLayoutMaterialized(
  stylesheet: Stylesheet,
  diagram: LaidOutDiagram,
  edit: StyleEdit,
): StyleEdit {
  const nodePins: Array<NodeStyleChange> = Object.values(diagram.nodes)
    .filter((node) => stylesheet.nodes[node.id]?.layout?.position === undefined)
    .map((node) =>
      nodeChange(
        node.id,
        patchNodeEntry(stylesheet.nodes[node.id], {
          position: parentRelative(diagram.groups, node.position, node.parentGroup),
        }),
      ),
    );
  const groupPins: Array<GroupStyleChange> = Object.values(diagram.groups)
    .filter((group) => stylesheet.groups[group.id]?.layout?.position === undefined)
    .map((group) =>
      groupChange(
        group.id,
        patchGroupEntry(stylesheet.groups[group.id], {
          position: parentRelative(diagram.groups, group.position, group.parentGroup),
        }),
      ),
    );

  if (nodePins.length === 0 && groupPins.length === 0) {
    return edit;
  }

  return create(StyleEditSchema, {
    ...initOf(edit),
    nodeChanges: [...nodePins, ...edit.nodeChanges],
    groupChanges: [...groupPins, ...edit.groupChanges],
  });
}
