// SPDX-License-Identifier: AGPL-3.0-or-later
// @generated by archebuild — do not edit. Regenerated each build.

import { create } from '@bufbuild/protobuf';
import { LaidOutDiagram } from '@archeglyph/core/layout/laid_out_diagram';
import {
  StyleEdit,
  Stylesheet,
  Vec2,
  Vec2Schema,
} from '@archeglyph/proto/gen/style_pb';

import { patchGroupEntry, patchNodeEntry } from './entry_patch';
import { groupChange, nodeChange, styleEdit } from './edit_builder';

type ParentGroupId = string | undefined;

export function unpinAllEdit(stylesheet: Stylesheet): StyleEdit {
  throw new Error('not implemented');
}
export function pinAllEdit(stylesheet: Stylesheet, diagram: LaidOutDiagram): StyleEdit {
  const groupsById = new Map(diagram.groups.map((group) => [group.id, group]));

  const parentRelativePosition = (position: Vec2, parentId: ParentGroupId): Vec2 => {
    const parent = parentId === undefined ? undefined : groupsById.get(parentId);
    return parent === undefined
      ? create(Vec2Schema, { x: position.x, y: position.y })
      : create(Vec2Schema, {
          x: position.x - parent.position.x,
          y: position.y - parent.position.y,
        });
  };

  const nodeChanges = diagram.nodes.map((node) =>
    nodeChange(
      node.id,
      patchNodeEntry(stylesheet.nodes[node.id], {
        position: parentRelativePosition(node.position, node.parentGroup),
      }),
    ),
  );
  const groupChanges = diagram.groups.map((group) =>
    groupChange(
      group.id,
      patchGroupEntry(stylesheet.groups[group.id], {
        position: parentRelativePosition(group.position, group.parentGroup),
      }),
    ),
  );

  return styleEdit({
    nodeChanges,
    groupChanges,
    description: 'Pin all laid-out elements',
  });
}
export function unpinElementsEdit(stylesheet: Stylesheet, refs: Array<ElementMove>): StyleEdit {
  throw new Error('not implemented');
}
