// SPDX-License-Identifier: AGPL-3.0-or-later
// @generated by archebuild — do not edit. Regenerated each build.

import { type StyleEdit, type Stylesheet, type Vec2 } from '@archeglyph/proto/gen/style_pb';

import {
  patchAnnotationEntry,
  patchGroupEntry,
  patchNodeEntry,
} from './entry_patch';
import {
  annotationChange,
  groupChange,
  nodeChange,
  styleEdit,
} from './edit_builder';

export function moveNodeEdit(stylesheet: Stylesheet, nodeId: string, position: Vec2): StyleEdit {
  return styleEdit({
    nodeChanges: [
      nodeChange(nodeId, patchNodeEntry(stylesheet.nodes[nodeId], { position })),
    ],
    description: 'Move node',
  });
}

export interface ElementMove {
  kind: 'node' | 'group' | 'annotation';
  id: string;
  position: Vec2;
}

export function moveAnnotationEdit(stylesheet: Stylesheet, annotationId: string, position: Vec2): StyleEdit {
  const existing = stylesheet.annotations[annotationId];
  return styleEdit({
    annotationChanges: [
      annotationChange(
        annotationId,
        patchAnnotationEntry(existing, { id: annotationId, position }),
      ),
    ],
    description: 'Move annotation',
  });
}

export function moveElementsEdit(stylesheet: Stylesheet, moves: Array<ElementMove>): StyleEdit {
  const nodeChanges = [];
  const groupChanges = [];
  const annotationChanges = [];

  for (const move of moves) {
    if (move.kind === 'node') {
      nodeChanges.push(
        nodeChange(move.id, patchNodeEntry(stylesheet.nodes[move.id], { position: move.position })),
      );
    } else if (move.kind === 'group') {
      groupChanges.push(
        groupChange(move.id, patchGroupEntry(stylesheet.groups[move.id], { position: move.position })),
      );
    } else {
      annotationChanges.push(
        annotationChange(
          move.id,
          patchAnnotationEntry(stylesheet.annotations[move.id], {
            id: move.id,
            position: move.position,
          }),
        ),
      );
    }
  }

  return styleEdit({
    ...(nodeChanges.length === 0 ? {} : { nodeChanges }),
    ...(groupChanges.length === 0 ? {} : { groupChanges }),
    ...(annotationChanges.length === 0 ? {} : { annotationChanges }),
    description: 'Move elements',
  });
}

export function moveGroupEdit(stylesheet: Stylesheet, groupId: string, position: Vec2): StyleEdit {
  return styleEdit({
    groupChanges: [
      groupChange(groupId, patchGroupEntry(stylesheet.groups[groupId], { position })),
    ],
    description: 'Move group',
  });
}
