// SPDX-License-Identifier: AGPL-3.0-or-later
// @generated by archebuild — do not edit. Regenerated each build.

<<<<<<< HEAD
import { type StyleEdit, type Stylesheet, type Vec2 } from '@archeglyph/proto/gen/style_pb';

import {
  patchAnnotationEntry,
  patchGroupEntry,
  patchNodeEntry,
} from './entry_patch';
import {
  annotationChange,
  groupChange,
  nodeChange,
  styleEdit,
} from './edit_builder';

export function moveNodeEdit(stylesheet: Stylesheet, nodeId: string, position: Vec2): StyleEdit {
  return styleEdit({
    nodeChanges: [
      nodeChange(nodeId, patchNodeEntry(stylesheet.nodes[nodeId], { position })),
    ],
    description: 'Move node',
  });
}
=======
import { StyleEdit, Stylesheet, Vec2 } from '@archeglyph/proto/gen/style_pb';

import { patchAnnotationEntry, patchGroupEntry, patchNodeEntry } from './entry_patch';
import { annotationChange, groupChange, nodeChange, styleEdit } from './edit_builder';
>>>>>>> 240e62a78caa92cb18dd6bd29d796afc34eadd7f

export interface ElementMove {
  kind: 'node' | 'group' | 'annotation';
  id: string;
  position: Vec2;
}

<<<<<<< HEAD
export function moveAnnotationEdit(stylesheet: Stylesheet, annotationId: string, position: Vec2): StyleEdit {
  const existing = stylesheet.annotations[annotationId];
  return styleEdit({
    annotationChanges: [
      annotationChange(
        annotationId,
        patchAnnotationEntry(existing, { id: annotationId, position }),
      ),
    ],
=======
export function moveNodeEdit(stylesheet: Stylesheet, nodeId: string, position: Vec2): StyleEdit {
  return styleEdit({
    nodeChanges: [nodeChange(nodeId, patchNodeEntry(stylesheet.nodes[nodeId], { position }))],
    description: 'Move node',
  });
}

export function moveAnnotationEdit(stylesheet: Stylesheet, annotationId: string, position: Vec2): StyleEdit {
  return styleEdit({
    annotationChanges: [annotationChange(annotationId, patchAnnotationEntry(stylesheet.annotations[annotationId], { id: annotationId, position }))],
>>>>>>> 240e62a78caa92cb18dd6bd29d796afc34eadd7f
    description: 'Move annotation',
  });
}

export function moveElementsEdit(stylesheet: Stylesheet, moves: Array<ElementMove>): StyleEdit {
<<<<<<< HEAD
  const nodeChanges = [];
  const groupChanges = [];
  const annotationChanges = [];

  for (const move of moves) {
    if (move.kind === 'node') {
      nodeChanges.push(
        nodeChange(move.id, patchNodeEntry(stylesheet.nodes[move.id], { position: move.position })),
      );
    } else if (move.kind === 'group') {
      groupChanges.push(
        groupChange(move.id, patchGroupEntry(stylesheet.groups[move.id], { position: move.position })),
      );
    } else {
      annotationChanges.push(
        annotationChange(
          move.id,
          patchAnnotationEntry(stylesheet.annotations[move.id], {
            id: move.id,
            position: move.position,
          }),
        ),
      );
    }
  }

  return styleEdit({
    ...(nodeChanges.length === 0 ? {} : { nodeChanges }),
    ...(groupChanges.length === 0 ? {} : { groupChanges }),
    ...(annotationChanges.length === 0 ? {} : { annotationChanges }),
    description: 'Move elements',
=======
  const nodeChanges = moves
    .filter((move) => move.kind === 'node')
    .map((move) => nodeChange(move.id, patchNodeEntry(stylesheet.nodes[move.id], { position: move.position })));
  const groupChanges = moves
    .filter((move) => move.kind === 'group')
    .map((move) => groupChange(move.id, patchGroupEntry(stylesheet.groups[move.id], { position: move.position })));
  const annotationChanges = moves
    .filter((move) => move.kind === 'annotation')
    .map((move) => annotationChange(move.id, patchAnnotationEntry(stylesheet.annotations[move.id], { id: move.id, position: move.position })));

  return styleEdit({
    nodeChanges,
    groupChanges,
    annotationChanges,
    description: 'Move selected elements',
>>>>>>> 240e62a78caa92cb18dd6bd29d796afc34eadd7f
  });
}

export function moveGroupEdit(stylesheet: Stylesheet, groupId: string, position: Vec2): StyleEdit {
  return styleEdit({
<<<<<<< HEAD
    groupChanges: [
      groupChange(groupId, patchGroupEntry(stylesheet.groups[groupId], { position })),
    ],
=======
    groupChanges: [groupChange(groupId, patchGroupEntry(stylesheet.groups[groupId], { position }))],
>>>>>>> 240e62a78caa92cb18dd6bd29d796afc34eadd7f
    description: 'Move group',
  });
}
