// @generated by archebuild — do not edit. Regenerated each build.

import { StyleEdit, Stylesheet, Vec2 } from '@archeglyph/proto/gen/style_pb';
import { annotationChange, groupChange, nodeChange, styleEdit } from './edit_builder';
import { patchAnnotationEntry, patchGroupEntry, patchNodeEntry } from './entry_patch';

export function moveNodeEdit(stylesheet: Stylesheet, nodeId: string, position: Vec2): StyleEdit {
  return styleEdit({
    nodeChanges: [
      nodeChange(nodeId, patchNodeEntry(stylesheet.nodes[nodeId], { position })),
    ],
    description: 'Move node',
  });
}

export interface ElementMove {
  kind: 'node' | 'group' | 'annotation';
  id: string;
  position: Vec2;
}

export function moveAnnotationEdit(stylesheet: Stylesheet, annotationId: string, position: Vec2): StyleEdit {
  const existing = stylesheet.annotations[annotationId];
  return styleEdit({
    annotationChanges: [
      annotationChange(
        annotationId,
        patchAnnotationEntry(existing, { id: annotationId, position }),
      ),
    ],
    description: 'Move annotation',
  });
}

export function moveElementsEdit(stylesheet: Stylesheet, moves: Array<ElementMove>): StyleEdit {
  const nodeChanges = moves
    .filter((move) => move.kind === 'node')
    .map((move) => nodeChange(move.id, patchNodeEntry(stylesheet.nodes[move.id], { position: move.position })));
  const groupChanges = moves
    .filter((move) => move.kind === 'group')
    .map((move) => groupChange(move.id, patchGroupEntry(stylesheet.groups[move.id], { position: move.position })));
  const annotationChanges = moves
    .filter((move) => move.kind === 'annotation')
    .map((move) => annotationChange(move.id, patchAnnotationEntry(stylesheet.annotations[move.id], { id: move.id, position: move.position })));

  return styleEdit({
    nodeChanges,
    groupChanges,
    annotationChanges,
    description: 'Move selected elements',
  });
}

export function moveGroupEdit(stylesheet: Stylesheet, groupId: string, position: Vec2): StyleEdit {
  const after = patchGroupEntry(stylesheet.groups[groupId], { position });

  return styleEdit({
    groupChanges: [groupChange(groupId, after)],
    description: 'Move group',
  });
}
