// SPDX-License-Identifier: AGPL-3.0-or-later
// @generated by archebuild — do not edit. Regenerated each build.

import { create } from '@bufbuild/protobuf';
import {
  StyleEdit,
<<<<<<< HEAD
  StyleEditSchema,
  StyleEditState,
  Stylesheet,
<<<<<<< HEAD
  StylesheetSchema,
=======
>>>>>>> 339fc02e26c01060752a173e06dc2f8a143d9151
=======
  Stylesheet,
  StylesheetSchema,
>>>>>>> 883a9dc6e733854a84ac2414049f0ad4261993d6
} from '@archeglyph/proto/gen/style_pb';

export function acceptPendingEdit(stylesheet: Stylesheet, editId: string): StyleEdit | undefined {
  const pending: StyleEdit | undefined = findPendingEdit(stylesheet, editId);
  if (pending === undefined) {
    return undefined;
  }

  return create(StyleEditSchema, {
    ...pending,
    state: StyleEditState.APPLIED,
  });
}
export function proposePendingEdit(stylesheet: Stylesheet, proposal: StyleEdit, author: string): Stylesheet {
  const pendingEdit: StyleEdit = create(StyleEditSchema, {
    ...proposal,
    author,
    state: StyleEditState.PENDING,
  });

  return create(StylesheetSchema, {
    ...stylesheet,
    pendingEdits: [...stylesheet.pendingEdits, pendingEdit],
  });
}
export function removePendingEdit(stylesheet: Stylesheet, editId: string): Stylesheet {
  return create(StylesheetSchema, {
    schemaVersion: stylesheet.schemaVersion,
    themeRef: stylesheet.themeRef,
    canvas: stylesheet.canvas,
    nodes: stylesheet.nodes,
    edges: stylesheet.edges,
    groups: stylesheet.groups,
    annotations: stylesheet.annotations,
    pendingEdits: stylesheet.pendingEdits.filter((edit: StyleEdit) => edit.id !== editId),
  });
}
export function findPendingEdit(stylesheet: Stylesheet, editId: string): StyleEdit | undefined {
  return stylesheet.pendingEdits.find((edit) => edit.id === editId);
}
