// @generated by archebuild — do not edit. Regenerated each build.

import { create } from '@bufbuild/protobuf';
import {
  StyleEdit,
  StyleEditSchema,
  StyleEditState,
  Stylesheet,
  StylesheetSchema,
} from '@archeglyph/proto/gen/style_pb';

export function acceptPendingEdit(stylesheet: Stylesheet, editId: string): StyleEdit | undefined {
  throw new Error('not implemented');
}
export function proposePendingEdit(stylesheet: Stylesheet, proposal: StyleEdit, author: string): Stylesheet {
  const pendingEdit: StyleEdit = create(StyleEditSchema, {
    ...proposal,
    author,
    state: StyleEditState.PENDING,
  });

  return create(StylesheetSchema, {
    ...stylesheet,
    pendingEdits: [...stylesheet.pendingEdits, pendingEdit],
  });
}
export function removePendingEdit(stylesheet: Stylesheet, editId: string): Stylesheet {
  throw new Error('not implemented');
}
export function findPendingEdit(stylesheet: Stylesheet, editId: string): StyleEdit | undefined {
  throw new Error('not implemented');
}
