// @generated by archebuild — do not edit. Regenerated each build.

export function acceptPendingEdit(stylesheet: Stylesheet, editId: string): StyleEdit | undefined {
  throw new Error('not implemented');
}
export function proposePendingEdit(stylesheet: Stylesheet, proposal: StyleEdit, author: string): Stylesheet {
  throw new Error('not implemented');
}
export function removePendingEdit(stylesheet: Stylesheet, editId: string): Stylesheet {
  throw new Error('not implemented');
}
export function findPendingEdit(stylesheet: Stylesheet, editId: string): StyleEdit | undefined {
  throw new Error('not implemented');
}
