// @generated by archebuild — do not edit. Regenerated each build.

import { NodeVisibility, StyleEdit, Stylesheet } from '@archeglyph/proto/gen/style_pb';
import { nodeChange, styleEdit } from './edit_builder';
import { patchNodeEntry } from './entry_patch';

export function showAllEdit(stylesheet: Stylesheet): StyleEdit {
  // Only the nodes that are actually hidden. Passing every id would stamp an
  // explicit UNSPECIFIED onto entries whose visibility was absent, rewriting
  // elements the command was never about.
  const hidden = Object.keys(stylesheet.nodes).filter(
    (nodeId) => stylesheet.nodes[nodeId].visibility === NodeVisibility.HIDDEN,
  );
  return setNodesHiddenEdit(stylesheet, hidden, false);
}

export function setNodeHiddenEdit(stylesheet: Stylesheet, nodeId: string, hidden: boolean): StyleEdit {
  return setNodesHiddenEdit(stylesheet, [nodeId], hidden);
}

export function setNodesHiddenEdit(stylesheet: Stylesheet, nodeIds: Array<string>, hidden: boolean): StyleEdit {
  const visibility = hidden ? NodeVisibility.HIDDEN : NodeVisibility.UNSPECIFIED;
  const nodeChanges = nodeIds.map((nodeId) =>
    nodeChange(nodeId, patchNodeEntry(stylesheet.nodes[nodeId], { visibility })),
  );

  return styleEdit({
    nodeChanges,
    description: hidden ? 'Hide selected nodes' : 'Show selected nodes',
  });
}
