// @generated by archebuild — do not edit. Regenerated each build.

import { NodeVisibility, StyleEdit, Stylesheet } from '@archeglyph/proto/gen/style_pb';

import { patchNodeEntry } from './entry_patch';
import { nodeChange, styleEdit } from './edit_builder';

export function showAllEdit(stylesheet: Stylesheet): StyleEdit {
  const hiddenNodeIds = Object.keys(stylesheet.nodes).filter(
    (nodeId) => stylesheet.nodes[nodeId]?.visibility === NodeVisibility.HIDDEN,
  );

  return setNodesHiddenEdit(stylesheet, hiddenNodeIds, false);
}
export function setNodeHiddenEdit(stylesheet: Stylesheet, nodeId: string, hidden: boolean): StyleEdit {
  const visibility = hidden ? NodeVisibility.HIDDEN : NodeVisibility.UNSPECIFIED;
  const nodeChanges = [
    nodeChange(nodeId, patchNodeEntry(stylesheet.nodes[nodeId], { visibility })),
  ];

  return styleEdit({
    nodeChanges,
    description: hidden ? 'Hide selected nodes' : 'Show selected nodes',
  });
}
export function setNodesHiddenEdit(stylesheet: Stylesheet, nodeIds: Array<string>, hidden: boolean): StyleEdit {
  const visibility = hidden ? NodeVisibility.HIDDEN : NodeVisibility.UNSPECIFIED;
  const nodeChanges = nodeIds.map((nodeId) =>
    nodeChange(nodeId, patchNodeEntry(stylesheet.nodes[nodeId], { visibility })),
  );

  return styleEdit({
    nodeChanges,
    description: hidden ? 'Hide selected nodes' : 'Show selected nodes',
  });
}
