// @generated by archebuild — do not edit. Regenerated each build.

export class GitHubAuth {
  isAuthenticated(): boolean { throw new Error('not implemented'); }
  getToken(): string | null { throw new Error('not implemented'); }
  authenticate(): Promise<void> { throw new Error('not implemented'); }
}
