// @generated by archebuild — do not edit. Regenerated each build.

import { Diagram } from '@archeglyph/proto/gen/content_pb';
import { Stylesheet } from '@archeglyph/proto/gen/style_pb';

export class LoadResult {
  diagram!: Diagram;
  stylesheet?: Stylesheet;
}
export interface HostAdapter {
  canSave(): boolean;
  load(): Promise<LoadResult>;
  save(stylesheet: Stylesheet): Promise<void>;
}
