// @generated by archebuild — do not edit. Regenerated each build.

export function seedNewcomers(diagram: ResolvedDiagram, pinned: Map<string, Vec2>, elk: ELK): Promise<Map<string, Vec2>> {
  throw new Error('not implemented');
}
