// SPDX-License-Identifier: AGPL-3.0-or-later
// @generated by archebuild — do not edit. Regenerated each build.

import { LaidOutDiagram } from '../../layout/laid_out_diagram';
import { EdgeSection } from '../../layout/edge_section';
import { ArrowheadVariant, Glyph2D, Typography, Vec2 } from '@archeglyph/proto/gen/style_pb';
import { Localization } from '@archeglyph/proto/gen/content_pb';

export function viewBox(diagram: LaidOutDiagram): string {
  let minX = Infinity;
  let minY = Infinity;
  let maxX = -Infinity;
  let maxY = -Infinity;

  const expandPoint = (p: Vec2): void => {
    if (p.x < minX) minX = p.x;
    if (p.y < minY) minY = p.y;
    if (p.x > maxX) maxX = p.x;
    if (p.y > maxY) maxY = p.y;
  };

  const expandRect = (pos: Vec2, sz: Vec2): void => {
    if (pos.x < minX) minX = pos.x;
    if (pos.y < minY) minY = pos.y;
    const x2 = pos.x + sz.x;
    const y2 = pos.y + sz.y;
    if (x2 > maxX) maxX = x2;
    if (y2 > maxY) maxY = y2;
  };

  for (const node of diagram.nodes) {
    expandRect(node.position, node.size);
  }
  for (const group of diagram.groups) {
    expandRect(group.position, group.size);
  }
  for (const annotation of diagram.annotations) {
    expandPoint(annotation.position);
  }
  for (const edge of diagram.edges) {
    for (const section of edge.sections) {
      expandPoint(section.startPoint);
      expandPoint(section.endPoint);
      for (const bp of section.bendPoints) {
        expandPoint(bp);
      }
    }
  }

  if (minX === Infinity) {
    return '0 0 800 600';
  }

  const pad = 8;
  return `${minX - pad} ${minY - pad} ${maxX - minX + pad * 2} ${maxY - minY + pad * 2}`;
}

export function arrowMarkers(variants: ArrowheadVariant): string {
  throw new Error('not implemented');
}

export function edgePath(sections: EdgeSection[]): string {
  throw new Error('not implemented');
}

export function textElement(label: Localization, typography: Typography, anchor: Vec2): string {
  throw new Error('not implemented');
}

export function shapePath(shape: Glyph2D, position: Vec2, size: Vec2): string {
  throw new Error('not implemented');
}
