// SPDX-License-Identifier: AGPL-3.0-or-later
// @generated by archebuild — do not edit. Regenerated each build.

import { type LaidOutDiagram } from '../../layout/laid_out_diagram';
import { type EdgeSection } from '../../layout/edge_section';
import { type Localization } from '@archeglyph/proto/gen/content_pb';
import { type ArrowheadVariant, type Glyph2D, type Vec2, type Typography, FontWeight, TextAlign } from '@archeglyph/proto/gen/style_pb';

function escapeXml(text: string): string {
  const chars: string[] = text.split("");
  const escaped: string[] = chars.map((ch: string): string => {
    if (ch === "&") { return "&amp;"; }
    else if (ch === "<") { return "&lt;"; }
    else if (ch === ">") { return "&gt;"; }
    else if (ch === '"') { return "&quot;"; }
    else { return ch; }
  });
  return escaped.join("");
}

function fontWeightValue(weight: FontWeight): string {
  if (weight === FontWeight.WEIGHT_LIGHT) { return "300"; }
  else if (weight === FontWeight.WEIGHT_NORMAL) { return "400"; }
  else if (weight === FontWeight.WEIGHT_MEDIUM) { return "500"; }
  else if (weight === FontWeight.WEIGHT_SEMIBOLD) { return "600"; }
  else if (weight === FontWeight.WEIGHT_BOLD) { return "700"; }
  else { return ""; }
}

function textAnchorValue(align: TextAlign): string {
  if (align === TextAlign.ALIGN_CENTER) { return "middle"; }
  else if (align === TextAlign.ALIGN_LEFT) { return "start"; }
  else if (align === TextAlign.ALIGN_RIGHT) { return "end"; }
  else { return ""; }
}

export function viewBox(diagram: LaidOutDiagram): string {
  throw new Error('not implemented');
}
export function arrowMarkers(variants: ArrowheadVariant): string {
  throw new Error('not implemented');
}
export function edgePath(sections: EdgeSection): string {
  throw new Error('not implemented');
}
export function textElement(label: Localization, typography: Typography, anchor: Vec2): string {
  if (typography.visible === false) {
    return "";
  } else {
    const weightStr: string = typography.weight !== undefined ? fontWeightValue(typography.weight) : "";
    const anchorStr: string = typography.align !== undefined ? textAnchorValue(typography.align) : "";
    const fillStr: string = typography.color !== undefined ? typography.color.value : "";

    const attrParts: string[] = [
      `x="${anchor.x}"`,
      `y="${anchor.y}"`,
      typography.font !== undefined ? `font-family="${typography.font}"` : "",
      typography.size !== undefined ? `font-size="${typography.size}"` : "",
      weightStr !== "" ? `font-weight="${weightStr}"` : "",
      anchorStr !== "" ? `text-anchor="${anchorStr}"` : "",
      fillStr !== "" ? `fill="${fillStr}"` : "",
    ].filter((s: string): boolean => s !== "");
    const attrs: string = attrParts.join(" ");

    const lines: string[] = label.source.split("\n");
    const lineHeight: number = typography.size !== undefined ? typography.size * 1.2 : 16;
    const tspans: string[] = lines.map((line: string, i: number): string => {
      const dy: string = i === 0 ? "0" : `${lineHeight}`;
      return `<tspan x="${anchor.x}" dy="${dy}">${escapeXml(line)}</tspan>`;
    });
    return `<text ${attrs}>${tspans.join("")}</text>`;
  }
}
export function shapePath(shape: Glyph2D, position: Vec2, size: Vec2): string {
  throw new Error('not implemented');
}
