// SPDX-License-Identifier: AGPL-3.0-or-later

// @generated by archebuild — do not edit. Regenerated each build.

import { AnnotationEntry } from '@archeglyph/proto/gen/style_pb';

export class FilteredAnnotation {
  id!: string;
  entry!: AnnotationEntry;
}
