// @generated by archebuild — do not edit. Regenerated each build.

export function lineModel(model: InspectorModel, geometry: SceneGeometry, stylesheet: Stylesheet): LineModel {
  throw new Error('not implemented');
}
import { NumberField } from '../number_field';
import { TextField } from '../text_field';

export interface LineModel {
  strokeColor: TextField;
  strokeWidth: NumberField;
  pattern: TextField;
  arrowStart: TextField;
  arrowEnd: TextField;
}
