// @generated by archebuild — do not edit. Regenerated each build.

export function commitLine(model: InspectorModel, stylesheet: Stylesheet, field: 'strokeColor' | 'strokeWidth' | 'pattern' | 'arrowStart' | 'arrowEnd', value: string | number | undefined): StyleEdit | undefined {
  throw new Error('not implemented');
}
