// @generated by archebuild — do not edit. Regenerated each build.

export function commitShape(model: InspectorModel, stylesheet: Stylesheet, field: 'shape' | 'cornerRadius' | 'fill' | 'strokeColor' | 'strokeWidth', value: string | number | undefined): StyleEdit | undefined {
  throw new Error('not implemented');
}
