// @generated by archebuild — do not edit. Regenerated each build.

import { Comment } from '../../../proto/src/gen/style_pb';

export function newComment(body: string, author: string): Promise<Comment> {
  throw new Error('not implemented');
}
