// SPDX-License-Identifier: AGPL-3.0-or-later
// @generated by archebuild — do not edit. Regenerated each build.

import { Comment, CommentSchema } from '@archeglyph/proto/gen/style_pb';
import { create } from '@bufbuild/protobuf';

export async function newComment(body: string, author: string): Promise<Comment> {
  const timestampMs: bigint = BigInt(Date.now());
  // BigInt is represented as a decimal string so that the input remains
  // valid JSON. Sorting the keys makes the representation canonical rather
  // than dependent on the order in which the object is assembled.
  const canonical: string = JSON.stringify({
    author,
    body,
    timestampMs: timestampMs.toString(),
  });
  const bytes: Uint8Array = new TextEncoder().encode(canonical);
  const digest: ArrayBuffer = await crypto.subtle.digest('SHA-256', bytes.slice().buffer);
  const hash: Uint8Array = new Uint8Array(digest);

  let id: string = '';
  for (let index: number = 0; index < 8; index += 1) {
    id += hash[index].toString(16).padStart(2, '0');
  }

  return create(CommentSchema, {
    id,
    author,
    timestampMs,
    body,
  });
}
