// @generated by archebuild — do not edit. Regenerated each build.

import { PendingItem } from './pending_model';

export interface PendingPanelProps {
  items: ReadonlyArray<PendingItem>;
  selectedId?: string;
  onSelect: (a0: string) => void;
  onAccept: (a0: string) => void;
  onReject: (a0: string) => void;
  onReply: (a0: string, a1: string) => void;
  syncError?: string;
}
