// SPDX-License-Identifier: AGPL-3.0-or-later

// @generated by archebuild — do not edit. Regenerated each build.

import { Stylesheet } from '../../../proto/src/gen/style_pb';

export function pendingItems(stylesheet: Stylesheet): Array<PendingItem> {
  return stylesheet.pendingEdits.map((edit): PendingItem => ({
    id: edit.id,
    description: edit.description !== undefined && edit.description.length > 0
      ? edit.description
      : 'Untitled change',
    author: edit.author !== undefined ? edit.author : 'unknown',
    changeCount: edit.nodeChanges.length
      + edit.edgeChanges.length
      + edit.groupChanges.length
      + edit.annotationChanges.length,
    comments: edit.thread !== undefined ? edit.thread.comments : [],
  }));
}
import { Comment } from '../../../proto/src/gen/style_pb';

export interface PendingItem {
  id: string;
  description: string;
  author: string;
  changeCount: number;
  comments: ReadonlyArray<Comment>;
}
