// @generated by archebuild — do not edit. Regenerated each build.

import { Stylesheet } from '../../../proto/src/gen/style_pb';

export function pendingItems(stylesheet: Stylesheet): Array<PendingItem> {
  throw new Error('not implemented');
}
import { Comment } from '../../../proto/src/gen/style_pb';

export interface PendingItem {
  id: string;
  description: string;
  author: string;
  changeCount: number;
  comments: ReadonlyArray<Comment>;
}
