// @generated by archebuild — do not edit. Regenerated each build.

import { Comment } from '../../../proto/src/gen/style_pb';

export interface ThreadViewProps {
  comments: ReadonlyArray<Comment>;
  onReply: (a0: string) => void;
}
